# Auto-generated by fogg. Do not edit
# Make improvements in fogg, so that everyone can benefit.

module "aws-params-reader-policy" {
  source    = "github.com/chanzuckerberg/cztack//aws-params-reader-policy?ref=v0.15.1"
  env       = local.env
  project   = local.project
  role_name = local.role_name
  service   = local.service
}
