# Auto-generated by fogg. Do not edit
# Make improvements in fogg, so that everyone can benefit.

module "aws-aurora-postgres" {
  source                = "github.com/chanzuckerberg/cztack//aws-aurora-postgres?ref=main"
  database_name         = local.database_name
  database_password     = local.database_password
  database_subnet_group = local.database_subnet_group
  database_username     = local.database_username
  env                   = var.tags.env
  owner                 = var.tags.owner
  project               = local.project
  service               = local.service
  vpc_id                = local.vpc_id



}
