# Auto-generated by fogg. Do not edit
# Make improvements in fogg, so that everyone can benefit.

output "database_name" {
  value = module.aws-aurora-postgres.database_name
}

output "endpoint" {
  value = module.aws-aurora-postgres.endpoint
}

output "port" {
  value = module.aws-aurora-postgres.port
}

output "reader_endpoint" {
  value = module.aws-aurora-postgres.reader_endpoint
}


