# Auto-generated by fogg. Do not edit
# Make improvements in fogg, so that everyone can benefit.

output "azs" {
  value = module.aws-env.azs
}

output "bastion_fqdn" {
  value = module.aws-env.bastion_fqdn
}

output "bastion_security_group_id" {
  value = module.aws-env.bastion_security_group_id
}

output "database_route_table_ids" {
  value = module.aws-env.database_route_table_ids
}

output "database_subnet_group" {
  value = module.aws-env.database_subnet_group
}

output "database_subnets" {
  value = module.aws-env.database_subnets
}

output "database_subnets_cidr_blocks" {
  value = module.aws-env.database_subnets_cidr_blocks
}

output "default_route_table_id" {
  value = module.aws-env.default_route_table_id
}

output "elasticache_route_table_ids" {
  value = module.aws-env.elasticache_route_table_ids
}

output "elasticache_subnet_group" {
  value = module.aws-env.elasticache_subnet_group
}

output "elasticache_subnets" {
  value = module.aws-env.elasticache_subnets
}

output "elasticache_subnets_cidr_blocks" {
  value = module.aws-env.elasticache_subnets_cidr_blocks
}

output "igw_id" {
  value = module.aws-env.igw_id
}

output "intra_route_table_ids" {
  value = module.aws-env.intra_route_table_ids
}

output "nat_ids" {
  value = module.aws-env.nat_ids
}

output "nat_public_ips" {
  value = module.aws-env.nat_public_ips
}

output "natgw_ids" {
  value = module.aws-env.natgw_ids
}

output "private_route_table_ids" {
  value = module.aws-env.private_route_table_ids
}

output "private_subnets" {
  value = module.aws-env.private_subnets
}

output "private_subnets_cidr_blocks" {
  value = module.aws-env.private_subnets_cidr_blocks
}

output "public_route_table_ids" {
  value = module.aws-env.public_route_table_ids
}

output "public_subnets" {
  value = module.aws-env.public_subnets
}

output "public_subnets_cidr_blocks" {
  value = module.aws-env.public_subnets_cidr_blocks
}

output "redshift_route_table_ids" {
  value = module.aws-env.redshift_route_table_ids
}

output "redshift_subnet_group" {
  value = module.aws-env.redshift_subnet_group
}

output "redshift_subnets" {
  value = module.aws-env.redshift_subnets
}

output "redshift_subnets_cidr_blocks" {
  value = module.aws-env.redshift_subnets_cidr_blocks
}

output "vgw_id" {
  value = module.aws-env.vgw_id
}

output "vpc_cidr_block" {
  value = module.aws-env.vpc_cidr_block
}

output "vpc_id" {
  value = module.aws-env.vpc_id
}


