# Auto-generated by fogg. Do not edit
# Make improvements in fogg, so that everyone can benefit.

output "aws_rds_cluster_instance_endpoint" {
  value     = module.aws-aurora-postgres.aws_rds_cluster_instance_endpoint
  sensitive = false
}

output "cluster_id" {
  value     = module.aws-aurora-postgres.cluster_id
  sensitive = false
}

output "cluster_resource_id" {
  value     = module.aws-aurora-postgres.cluster_resource_id
  sensitive = false
}

output "database_name" {
  value     = module.aws-aurora-postgres.database_name
  sensitive = false
}

output "endpoint" {
  value     = module.aws-aurora-postgres.endpoint
  sensitive = false
}

output "master_password" {
  value     = module.aws-aurora-postgres.master_password
  sensitive = true
}

output "master_username" {
  value     = module.aws-aurora-postgres.master_username
  sensitive = false
}

output "port" {
  value     = module.aws-aurora-postgres.port
  sensitive = false
}

output "reader_endpoint" {
  value     = module.aws-aurora-postgres.reader_endpoint
  sensitive = false
}


