version: 2
updates:
  - package-ecosystem: gomod
    directory: "/"
    schedule:
      interval: weekly
    open-pull-requests-limit: 10
    labels:
      - bot/merge
    commit-message:
      prefix: "chore: "
    groups:
      atlantis:
        patterns:
          - "github.com/runatlantis/*"
      terraform:
        patterns:
          - "github.com/hashicorp/*"
        exclude-patterns:
          # pin to 0.15.3 (last version with shared registry packages)
          - "github.com/hashicorp/terraform/*"
      gomod:
        patterns:
          - "*"
        exclude-patterns:
          - "github.com/runatlantis/*"
          - "github.com/hashicorp/*"
          # pin to 0.15.3 (last version with shared registry packages)
          - "github.com/hashicorp/terraform/*"
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
    labels:
      - bot/merge
    commit-message:
      prefix: "chore: "
    groups:
      github-actions:
        patterns:
          - "*"
