linters:
  enable:
    - asciicheck
    - bodyclose
    - dupl
    - errcheck
    - gocyclo
    - gofmt
    - goimports
    - misspell
    - nolintlint
    - rowserrcheck
    - unconvert
    - unparam
    - whitespace
