version: "2"

formatters:
  enable:
    - gofmt
    - goimports

linters:
  enable:
    - asciicheck
    - bodyclose
    - dupl
    - errcheck
    - gocyclo
    - misspell
    - nolintlint
    - revive
    - rowserrcheck
    - staticcheck
    - unconvert
    - unparam
    - unused
    - whitespace
