run:
  skip-dirs:
    - exp/examine
  skip-files:
    - cmd/exp/entropy.go
    - exp/examine/local.go
    - exp/examine/util.go
  linters:
    enable:
      - gofmt
      - whitespace
      - unparam
      - scopelint
