run:
  skip-files:
    - cmd/exp_examine.go
    - cmd/exp_entropy.go
    - exp/examine/local.go
    - exp/examine/util.go
  linters:
    enable:
      - gofmt
      - whitespace
      - unparam
      - scopelint
