builds:
  - binary: fogg
    env:
      - CGO_ENABLED=0
    goos:
      - darwin
      - linux
    goarch:
      - amd64
      - arm64
    ldflags:
      - '-w -s -X main.Date={{.CommitDate}} -X github.com/chanzuckerberg/fogg/util.GitSha={{.Commit}} -X github.com/chanzuckerberg/fogg/util.Version={{.Version}} -X github.com/chanzuckerberg/fogg/util.Dirty=false -X github.com/chanzuckerberg/fogg/util.Release=true'
    mod_timestamp: '{{ .CommitTimestamp }}'

archives:
  - files:
      - none*

release:
  prerelease: false

brews:
  - description: 'Terraform without pain.'
    repository:
      owner: chanzuckerberg
      name: homebrew-tap
    homepage: 'https://github.com/chanzuckerberg/fogg'
    test: system "#{bin}/fogg version"
