runner:
  golangci:
    cmd: ./bin/golangci-lint run --out-format=line-number -v --timeout 5m
    errorformat:
      - '%E%f:%l:%c: %m'
      - '%E%f:%l: %m'
      - '%C%.%#'
    level: warning
  markdownlint:
    cmd: "node_modules/.bin/markdownlint -p .gitignore -c .markdownlint.json . 2>&1"
    errorformat:
      - '%f:%l:%c %m'
    level: warning

