# Auto-generated by fogg. Do not edit
# Make improvements in fogg, so that everyone can benefit.
# tflint-ignore: terraform_unused_declarations
data "terraform_remote_state" "global" {
  backend = "http"
  config = {


    address        = "http://localhost:8080/tfstate/00000000-1111-2222-3333-444444444444"
    lock_address   = "http://localhost:8080/tfstate/00000000-1111-2222-3333-444444444444/lock"
    unlock_address = "http://localhost:8080/tfstate/00000000-1111-2222-3333-444444444444/unlock"






  }
}
