# Auto-generated by fogg. Do not edit
# Make improvements in fogg, so that everyone can benefit.


  # Default Provider
  provider "aws" {
    version = "~> 0.12.0"
    region = "us-west-2"
    profile = "profile"
    allowed_account_ids = [123]
  }

  # Aliased Providers (for doing things in every region).
  




