# Auto-generated by fogg. Do not edit
# Make improvements in fogg, so that everyone can benefit.

module "fogg-test-module" {
  source = "github.com/chanzuckerberg/fogg-test-module"
  bar    = "${local.bar}"
  foo    = "${local.foo}"

}
