# Auto-generated by fogg. Do not edit
# Make improvements in fogg, so that everyone can benefit.

output "bar" {
  value = "${module.test-module.bar}"
}

output "foo" {
  value = "${module.test-module.foo}"
}
