# Auto-generated by fogg. Do not edit
# Make improvements in fogg, so that everyone can benefit.

# module "vpc" outputs
output "azs" {
  value = { for k, v in module.vpc :
    k => v.azs
  }
  sensitive = false
}
output "cgw_arns" {
  value = { for k, v in module.vpc :
    k => v.cgw_arns
  }
  sensitive = false
}
output "cgw_ids" {
  value = { for k, v in module.vpc :
    k => v.cgw_ids
  }
  sensitive = false
}
output "database_internet_gateway_route_id" {
  value = { for k, v in module.vpc :
    k => v.database_internet_gateway_route_id
  }
  sensitive = false
}
output "database_ipv6_egress_route_id" {
  value = { for k, v in module.vpc :
    k => v.database_ipv6_egress_route_id
  }
  sensitive = false
}
output "database_nat_gateway_route_ids" {
  value = { for k, v in module.vpc :
    k => v.database_nat_gateway_route_ids
  }
  sensitive = false
}
output "database_network_acl_arn" {
  value = { for k, v in module.vpc :
    k => v.database_network_acl_arn
  }
  sensitive = false
}
output "database_network_acl_id" {
  value = { for k, v in module.vpc :
    k => v.database_network_acl_id
  }
  sensitive = false
}
output "database_route_table_association_ids" {
  value = { for k, v in module.vpc :
    k => v.database_route_table_association_ids
  }
  sensitive = false
}
output "database_route_table_ids" {
  value = { for k, v in module.vpc :
    k => v.database_route_table_ids
  }
  sensitive = false
}
output "database_subnet_arns" {
  value = { for k, v in module.vpc :
    k => v.database_subnet_arns
  }
  sensitive = false
}
output "database_subnet_group" {
  value = { for k, v in module.vpc :
    k => v.database_subnet_group
  }
  sensitive = false
}
output "database_subnet_group_name" {
  value = { for k, v in module.vpc :
    k => v.database_subnet_group_name
  }
  sensitive = false
}
output "database_subnets" {
  value = { for k, v in module.vpc :
    k => v.database_subnets
  }
  sensitive = false
}
output "database_subnets_cidr_blocks" {
  value = { for k, v in module.vpc :
    k => v.database_subnets_cidr_blocks
  }
  sensitive = false
}
output "database_subnets_ipv6_cidr_blocks" {
  value = { for k, v in module.vpc :
    k => v.database_subnets_ipv6_cidr_blocks
  }
  sensitive = false
}
output "default_network_acl_id" {
  value = { for k, v in module.vpc :
    k => v.default_network_acl_id
  }
  sensitive = false
}
output "default_route_table_id" {
  value = { for k, v in module.vpc :
    k => v.default_route_table_id
  }
  sensitive = false
}
output "default_security_group_id" {
  value = { for k, v in module.vpc :
    k => v.default_security_group_id
  }
  sensitive = false
}
output "default_vpc_arn" {
  value = { for k, v in module.vpc :
    k => v.default_vpc_arn
  }
  sensitive = false
}
output "default_vpc_cidr_block" {
  value = { for k, v in module.vpc :
    k => v.default_vpc_cidr_block
  }
  sensitive = false
}
output "default_vpc_default_network_acl_id" {
  value = { for k, v in module.vpc :
    k => v.default_vpc_default_network_acl_id
  }
  sensitive = false
}
output "default_vpc_default_route_table_id" {
  value = { for k, v in module.vpc :
    k => v.default_vpc_default_route_table_id
  }
  sensitive = false
}
output "default_vpc_default_security_group_id" {
  value = { for k, v in module.vpc :
    k => v.default_vpc_default_security_group_id
  }
  sensitive = false
}
output "default_vpc_enable_dns_hostnames" {
  value = { for k, v in module.vpc :
    k => v.default_vpc_enable_dns_hostnames
  }
  sensitive = false
}
output "default_vpc_enable_dns_support" {
  value = { for k, v in module.vpc :
    k => v.default_vpc_enable_dns_support
  }
  sensitive = false
}
output "default_vpc_id" {
  value = { for k, v in module.vpc :
    k => v.default_vpc_id
  }
  sensitive = false
}
output "default_vpc_instance_tenancy" {
  value = { for k, v in module.vpc :
    k => v.default_vpc_instance_tenancy
  }
  sensitive = false
}
output "default_vpc_main_route_table_id" {
  value = { for k, v in module.vpc :
    k => v.default_vpc_main_route_table_id
  }
  sensitive = false
}
output "dhcp_options_id" {
  value = { for k, v in module.vpc :
    k => v.dhcp_options_id
  }
  sensitive = false
}
output "egress_only_internet_gateway_id" {
  value = { for k, v in module.vpc :
    k => v.egress_only_internet_gateway_id
  }
  sensitive = false
}
output "elasticache_network_acl_arn" {
  value = { for k, v in module.vpc :
    k => v.elasticache_network_acl_arn
  }
  sensitive = false
}
output "elasticache_network_acl_id" {
  value = { for k, v in module.vpc :
    k => v.elasticache_network_acl_id
  }
  sensitive = false
}
output "elasticache_route_table_association_ids" {
  value = { for k, v in module.vpc :
    k => v.elasticache_route_table_association_ids
  }
  sensitive = false
}
output "elasticache_route_table_ids" {
  value = { for k, v in module.vpc :
    k => v.elasticache_route_table_ids
  }
  sensitive = false
}
output "elasticache_subnet_arns" {
  value = { for k, v in module.vpc :
    k => v.elasticache_subnet_arns
  }
  sensitive = false
}
output "elasticache_subnet_group" {
  value = { for k, v in module.vpc :
    k => v.elasticache_subnet_group
  }
  sensitive = false
}
output "elasticache_subnet_group_name" {
  value = { for k, v in module.vpc :
    k => v.elasticache_subnet_group_name
  }
  sensitive = false
}
output "elasticache_subnets" {
  value = { for k, v in module.vpc :
    k => v.elasticache_subnets
  }
  sensitive = false
}
output "elasticache_subnets_cidr_blocks" {
  value = { for k, v in module.vpc :
    k => v.elasticache_subnets_cidr_blocks
  }
  sensitive = false
}
output "elasticache_subnets_ipv6_cidr_blocks" {
  value = { for k, v in module.vpc :
    k => v.elasticache_subnets_ipv6_cidr_blocks
  }
  sensitive = false
}
output "igw_arn" {
  value = { for k, v in module.vpc :
    k => v.igw_arn
  }
  sensitive = false
}
output "igw_id" {
  value = { for k, v in module.vpc :
    k => v.igw_id
  }
  sensitive = false
}
output "intra_network_acl_arn" {
  value = { for k, v in module.vpc :
    k => v.intra_network_acl_arn
  }
  sensitive = false
}
output "intra_network_acl_id" {
  value = { for k, v in module.vpc :
    k => v.intra_network_acl_id
  }
  sensitive = false
}
output "intra_route_table_association_ids" {
  value = { for k, v in module.vpc :
    k => v.intra_route_table_association_ids
  }
  sensitive = false
}
output "intra_route_table_ids" {
  value = { for k, v in module.vpc :
    k => v.intra_route_table_ids
  }
  sensitive = false
}
output "intra_subnet_arns" {
  value = { for k, v in module.vpc :
    k => v.intra_subnet_arns
  }
  sensitive = false
}
output "intra_subnets" {
  value = { for k, v in module.vpc :
    k => v.intra_subnets
  }
  sensitive = false
}
output "intra_subnets_cidr_blocks" {
  value = { for k, v in module.vpc :
    k => v.intra_subnets_cidr_blocks
  }
  sensitive = false
}
output "intra_subnets_ipv6_cidr_blocks" {
  value = { for k, v in module.vpc :
    k => v.intra_subnets_ipv6_cidr_blocks
  }
  sensitive = false
}
output "name" {
  value = { for k, v in module.vpc :
    k => v.name
  }
  sensitive = false
}
output "nat_ids" {
  value = { for k, v in module.vpc :
    k => v.nat_ids
  }
  sensitive = false
}
output "nat_public_ips" {
  value = { for k, v in module.vpc :
    k => v.nat_public_ips
  }
  sensitive = false
}
output "natgw_ids" {
  value = { for k, v in module.vpc :
    k => v.natgw_ids
  }
  sensitive = false
}
output "outpost_network_acl_arn" {
  value = { for k, v in module.vpc :
    k => v.outpost_network_acl_arn
  }
  sensitive = false
}
output "outpost_network_acl_id" {
  value = { for k, v in module.vpc :
    k => v.outpost_network_acl_id
  }
  sensitive = false
}
output "outpost_subnet_arns" {
  value = { for k, v in module.vpc :
    k => v.outpost_subnet_arns
  }
  sensitive = false
}
output "outpost_subnets" {
  value = { for k, v in module.vpc :
    k => v.outpost_subnets
  }
  sensitive = false
}
output "outpost_subnets_cidr_blocks" {
  value = { for k, v in module.vpc :
    k => v.outpost_subnets_cidr_blocks
  }
  sensitive = false
}
output "outpost_subnets_ipv6_cidr_blocks" {
  value = { for k, v in module.vpc :
    k => v.outpost_subnets_ipv6_cidr_blocks
  }
  sensitive = false
}
output "private_ipv6_egress_route_ids" {
  value = { for k, v in module.vpc :
    k => v.private_ipv6_egress_route_ids
  }
  sensitive = false
}
output "private_nat_gateway_route_ids" {
  value = { for k, v in module.vpc :
    k => v.private_nat_gateway_route_ids
  }
  sensitive = false
}
output "private_network_acl_arn" {
  value = { for k, v in module.vpc :
    k => v.private_network_acl_arn
  }
  sensitive = false
}
output "private_network_acl_id" {
  value = { for k, v in module.vpc :
    k => v.private_network_acl_id
  }
  sensitive = false
}
output "private_route_table_association_ids" {
  value = { for k, v in module.vpc :
    k => v.private_route_table_association_ids
  }
  sensitive = false
}
output "private_route_table_ids" {
  value = { for k, v in module.vpc :
    k => v.private_route_table_ids
  }
  sensitive = false
}
output "private_subnet_arns" {
  value = { for k, v in module.vpc :
    k => v.private_subnet_arns
  }
  sensitive = false
}
output "private_subnets" {
  value = { for k, v in module.vpc :
    k => v.private_subnets
  }
  sensitive = false
}
output "private_subnets_cidr_blocks" {
  value = { for k, v in module.vpc :
    k => v.private_subnets_cidr_blocks
  }
  sensitive = false
}
output "private_subnets_ipv6_cidr_blocks" {
  value = { for k, v in module.vpc :
    k => v.private_subnets_ipv6_cidr_blocks
  }
  sensitive = false
}
output "public_internet_gateway_ipv6_route_id" {
  value = { for k, v in module.vpc :
    k => v.public_internet_gateway_ipv6_route_id
  }
  sensitive = false
}
output "public_internet_gateway_route_id" {
  value = { for k, v in module.vpc :
    k => v.public_internet_gateway_route_id
  }
  sensitive = false
}
output "public_network_acl_arn" {
  value = { for k, v in module.vpc :
    k => v.public_network_acl_arn
  }
  sensitive = false
}
output "public_network_acl_id" {
  value = { for k, v in module.vpc :
    k => v.public_network_acl_id
  }
  sensitive = false
}
output "public_route_table_association_ids" {
  value = { for k, v in module.vpc :
    k => v.public_route_table_association_ids
  }
  sensitive = false
}
output "public_route_table_ids" {
  value = { for k, v in module.vpc :
    k => v.public_route_table_ids
  }
  sensitive = false
}
output "public_subnet_arns" {
  value = { for k, v in module.vpc :
    k => v.public_subnet_arns
  }
  sensitive = false
}
output "public_subnets" {
  value = { for k, v in module.vpc :
    k => v.public_subnets
  }
  sensitive = false
}
output "public_subnets_cidr_blocks" {
  value = { for k, v in module.vpc :
    k => v.public_subnets_cidr_blocks
  }
  sensitive = false
}
output "public_subnets_ipv6_cidr_blocks" {
  value = { for k, v in module.vpc :
    k => v.public_subnets_ipv6_cidr_blocks
  }
  sensitive = false
}
output "redshift_network_acl_arn" {
  value = { for k, v in module.vpc :
    k => v.redshift_network_acl_arn
  }
  sensitive = false
}
output "redshift_network_acl_id" {
  value = { for k, v in module.vpc :
    k => v.redshift_network_acl_id
  }
  sensitive = false
}
output "redshift_public_route_table_association_ids" {
  value = { for k, v in module.vpc :
    k => v.redshift_public_route_table_association_ids
  }
  sensitive = false
}
output "redshift_route_table_association_ids" {
  value = { for k, v in module.vpc :
    k => v.redshift_route_table_association_ids
  }
  sensitive = false
}
output "redshift_route_table_ids" {
  value = { for k, v in module.vpc :
    k => v.redshift_route_table_ids
  }
  sensitive = false
}
output "redshift_subnet_arns" {
  value = { for k, v in module.vpc :
    k => v.redshift_subnet_arns
  }
  sensitive = false
}
output "redshift_subnet_group" {
  value = { for k, v in module.vpc :
    k => v.redshift_subnet_group
  }
  sensitive = false
}
output "redshift_subnets" {
  value = { for k, v in module.vpc :
    k => v.redshift_subnets
  }
  sensitive = false
}
output "redshift_subnets_cidr_blocks" {
  value = { for k, v in module.vpc :
    k => v.redshift_subnets_cidr_blocks
  }
  sensitive = false
}
output "redshift_subnets_ipv6_cidr_blocks" {
  value = { for k, v in module.vpc :
    k => v.redshift_subnets_ipv6_cidr_blocks
  }
  sensitive = false
}
output "this_customer_gateway" {
  value = { for k, v in module.vpc :
    k => v.this_customer_gateway
  }
  sensitive = false
}
output "vgw_arn" {
  value = { for k, v in module.vpc :
    k => v.vgw_arn
  }
  sensitive = false
}
output "vgw_id" {
  value = { for k, v in module.vpc :
    k => v.vgw_id
  }
  sensitive = false
}
output "vpc_arn" {
  value = { for k, v in module.vpc :
    k => v.vpc_arn
  }
  sensitive = false
}
output "vpc_cidr_block" {
  value = { for k, v in module.vpc :
    k => v.vpc_cidr_block
  }
  sensitive = false
}
output "vpc_enable_dns_hostnames" {
  value = { for k, v in module.vpc :
    k => v.vpc_enable_dns_hostnames
  }
  sensitive = false
}
output "vpc_enable_dns_support" {
  value = { for k, v in module.vpc :
    k => v.vpc_enable_dns_support
  }
  sensitive = false
}
output "vpc_flow_log_cloudwatch_iam_role_arn" {
  value = { for k, v in module.vpc :
    k => v.vpc_flow_log_cloudwatch_iam_role_arn
  }
  sensitive = false
}
output "vpc_flow_log_destination_arn" {
  value = { for k, v in module.vpc :
    k => v.vpc_flow_log_destination_arn
  }
  sensitive = false
}
output "vpc_flow_log_destination_type" {
  value = { for k, v in module.vpc :
    k => v.vpc_flow_log_destination_type
  }
  sensitive = false
}
output "vpc_flow_log_id" {
  value = { for k, v in module.vpc :
    k => v.vpc_flow_log_id
  }
  sensitive = false
}
output "vpc_id" {
  value = { for k, v in module.vpc :
    k => v.vpc_id
  }
  sensitive = false
}
output "vpc_instance_tenancy" {
  value = { for k, v in module.vpc :
    k => v.vpc_instance_tenancy
  }
  sensitive = false
}
output "vpc_ipv6_association_id" {
  value = { for k, v in module.vpc :
    k => v.vpc_ipv6_association_id
  }
  sensitive = false
}
output "vpc_ipv6_cidr_block" {
  value = { for k, v in module.vpc :
    k => v.vpc_ipv6_cidr_block
  }
  sensitive = false
}
output "vpc_main_route_table_id" {
  value = { for k, v in module.vpc :
    k => v.vpc_main_route_table_id
  }
  sensitive = false
}
output "vpc_owner_id" {
  value = { for k, v in module.vpc :
    k => v.vpc_owner_id
  }
  sensitive = false
}
output "vpc_secondary_cidr_blocks" {
  value = { for k, v in module.vpc :
    k => v.vpc_secondary_cidr_blocks
  }
  sensitive = false
}
# module "my_module" outputs
# module "bar" outputs
