// Auto-generated by fogg. Do not edit
// Make improvements in fogg, so that everyone can benefit.

import * as fs from "fs";
import * as path from "path";
import { App } from "cdktf";
import { ComponentStack } from "./stack";

const outdir = "cdktf.out";
const app = new App({
  outdir,
});
const stack = new ComponentStack(app, "fogg");
app.synth();

// Copy the generated Terraform code to the current directory to keep relative directory references
const stackSynthDir = path.join(
  outdir,
  app.manifest.forStack(stack).workingDirectory,
);

fs.cpSync(stackSynthDir, ".", { recursive: true });
fs.rmSync(outdir, { recursive: true });
if (process.env.CI) {
  fs.renameSync("cdk.tf.json", "ci-cdk.tf.json");
}
