# Auto-generated by fogg. Do not edit
# Make improvements in fogg, so that everyone can benefit.

module "vpc" {
  for_each        = local.map
  source          = "terraform-aws-modules/vpc/aws"
  version         = "4.0.1"
  azs             = each.value.azs
  cidr            = each.value.cidr
  name            = each.value.name
  private_subnets = each.value.private_subnets
  public_subnets  = each.value.public_subnets
  tags            = each.value.tags
}

module "foo" {
  source = "../../../modules/my_module"
}

module "bar" {
  source = "../../../modules/my_module"
}
