# Auto-generated by fogg. Do not edit
# Make improvements in fogg, so that everyone can benefit.

SELF_DIR:=$(shell dirname $(realpath $(lastword $(MAKEFILE_LIST))))

include $(SELF_DIR)/common.mk

all: fmt lint doc
.PHONY: all

fmt: terraform
	@printf "fmt: ";
	@for f in $(TF); do printf .; $(terraform_command) fmt $(TF_ARGS) $$f; done
	@echo
.PHONY: fmt

check: lint check-docs
.PHONY: check

lint: lint-tf
.PHONY: lint

lint-tf: terraform
	@printf "fmt: ";
	@for f in $(TF); do \
	  printf .; $(terraform_command) fmt $(TF_ARGS) --check=true --diff=true || exit $$? ; \
	done
	@echo
.PHONY: lint-tf

readme:
	bash $(REPO_ROOT)/scripts/update-readme.sh update
.PHONY: readme

docs: readme
.PHONY: docs

check-docs:
	@bash $(REPO_ROOT)/scripts/update-readme.sh check; \
	if [ ! $$? -eq 0 ];  then \
		echo "Docs are out of date, run \`make docs\`"; \
	fi
.PHONY: check-docs

clean:
.PHONY: clean

test:
.PHONY: test
