# Auto-generated by fogg. Do not edit
# Make improvements in fogg, so that everyone can benefit.

output database_subnet_group {
  value = module.prod-vpc.database_subnet_group
}

output database_subnets {
  value = module.prod-vpc.database_subnets
}

output database_subnets_cidr_blocks {
  value = module.prod-vpc.database_subnets_cidr_blocks
}

output default_network_acl_id {
  value = module.prod-vpc.default_network_acl_id
}

output default_route_table_id {
  value = module.prod-vpc.default_route_table_id
}

output default_security_group_id {
  value = module.prod-vpc.default_security_group_id
}

output default_vpc_cidr_block {
  value = module.prod-vpc.default_vpc_cidr_block
}

output default_vpc_default_network_acl_id {
  value = module.prod-vpc.default_vpc_default_network_acl_id
}

output default_vpc_default_route_table_id {
  value = module.prod-vpc.default_vpc_default_route_table_id
}

output default_vpc_default_security_group_id {
  value = module.prod-vpc.default_vpc_default_security_group_id
}

output default_vpc_enable_dns_hostnames {
  value = module.prod-vpc.default_vpc_enable_dns_hostnames
}

output default_vpc_enable_dns_support {
  value = module.prod-vpc.default_vpc_enable_dns_support
}

output default_vpc_id {
  value = module.prod-vpc.default_vpc_id
}

output default_vpc_instance_tenancy {
  value = module.prod-vpc.default_vpc_instance_tenancy
}

output default_vpc_main_route_table_id {
  value = module.prod-vpc.default_vpc_main_route_table_id
}

output elasticache_subnet_group {
  value = module.prod-vpc.elasticache_subnet_group
}

output elasticache_subnet_group_name {
  value = module.prod-vpc.elasticache_subnet_group_name
}

output elasticache_subnets {
  value = module.prod-vpc.elasticache_subnets
}

output elasticache_subnets_cidr_blocks {
  value = module.prod-vpc.elasticache_subnets_cidr_blocks
}

output igw_id {
  value = module.prod-vpc.igw_id
}

output nat_ids {
  value = module.prod-vpc.nat_ids
}

output nat_public_ips {
  value = module.prod-vpc.nat_public_ips
}

output natgw_ids {
  value = module.prod-vpc.natgw_ids
}

output private_route_table_ids {
  value = module.prod-vpc.private_route_table_ids
}

output private_subnets {
  value = module.prod-vpc.private_subnets
}

output private_subnets_cidr_blocks {
  value = module.prod-vpc.private_subnets_cidr_blocks
}

output public_route_table_ids {
  value = module.prod-vpc.public_route_table_ids
}

output public_subnets {
  value = module.prod-vpc.public_subnets
}

output public_subnets_cidr_blocks {
  value = module.prod-vpc.public_subnets_cidr_blocks
}

output redshift_subnet_group {
  value = module.prod-vpc.redshift_subnet_group
}

output redshift_subnets {
  value = module.prod-vpc.redshift_subnets
}

output redshift_subnets_cidr_blocks {
  value = module.prod-vpc.redshift_subnets_cidr_blocks
}

output vgw_id {
  value = module.prod-vpc.vgw_id
}

output vpc_cidr_block {
  value = module.prod-vpc.vpc_cidr_block
}

output vpc_enable_dns_hostnames {
  value = module.prod-vpc.vpc_enable_dns_hostnames
}

output vpc_enable_dns_support {
  value = module.prod-vpc.vpc_enable_dns_support
}

output vpc_endpoint_dynamodb_id {
  value = module.prod-vpc.vpc_endpoint_dynamodb_id
}

output vpc_endpoint_dynamodb_pl_id {
  value = module.prod-vpc.vpc_endpoint_dynamodb_pl_id
}

output vpc_endpoint_s3_id {
  value = module.prod-vpc.vpc_endpoint_s3_id
}

output vpc_endpoint_s3_pl_id {
  value = module.prod-vpc.vpc_endpoint_s3_pl_id
}

output vpc_id {
  value = module.prod-vpc.vpc_id
}

output vpc_instance_tenancy {
  value = module.prod-vpc.vpc_instance_tenancy
}

output vpc_main_route_table_id {
  value = module.prod-vpc.vpc_main_route_table_id
}


