# Auto-generated by fogg. Do not edit
# Make improvements in fogg, so that everyone can benefit.

module "foo_vpc" {
  source          = "terraform-aws-modules/vpc/aws"
  version         = "4.0.1"
  azs             = local.foo_azs
  cidr            = local.foo_cidr
  name            = local.foo_name
  private_subnets = local.foo_private_subnets
  public_subnets  = local.foo_public_subnets
  tags            = local.foo_tags
}

module "bar_vpc" {
  source          = "terraform-aws-modules/vpc/aws"
  version         = "4.0.1"
  azs             = local.bar_azs
  cidr            = local.bar_cidr
  name            = local.bar_name
  private_subnets = local.bar_private_subnets
  public_subnets  = local.bar_public_subnets
  tags            = local.bar_tags
}

module "baz_vpc" {
  source          = "terraform-aws-modules/vpc/aws"
  version         = "4.0.1"
  azs             = local.baz_azs
  cidr            = local.baz_cidr
  name            = local.baz_name
  private_subnets = local.baz_private_subnets
  public_subnets  = local.baz_public_subnets
  tags            = local.baz_tags
}

module "corge_vpc" {
  source          = "terraform-aws-modules/vpc/aws"
  version         = "4.0.1"
  azs             = local.corge_azs
  cidr            = local.corge_cidr
  name            = local.corge_name
  private_subnets = local.corge_private_subnets
  public_subnets  = local.corge_public_subnets
  tags            = local.corge_tags
}

module "grault_vpc" {
  source          = "terraform-aws-modules/vpc/aws"
  version         = "4.0.1"
  azs             = local.grault_azs
  cidr            = local.grault_cidr
  name            = local.grault_name
  private_subnets = local.grault_private_subnets
  public_subnets  = local.grault_public_subnets
  tags            = local.grault_tags
}

module "qux_vpc" {
  source          = "terraform-aws-modules/vpc/aws"
  version         = "4.0.1"
  azs             = local.qux_azs
  cidr            = local.qux_cidr
  name            = local.qux_name
  private_subnets = local.qux_private_subnets
  public_subnets  = local.qux_public_subnets
  tags            = local.qux_tags
}

module "vpc_map" {
  for_each        = local.vpc_map
  source          = "terraform-aws-modules/vpc/aws"
  version         = "4.0.1"
  azs             = each.value.azs
  cidr            = each.value.cidr
  name            = each.value.name
  private_subnets = each.value.private_subnets
  public_subnets  = each.value.public_subnets
  tags            = each.value.tags
}

module "vpc_map_integrate_all" {
  for_each        = local.vpc_map
  source          = "terraform-aws-modules/vpc/aws"
  version         = "4.0.1"
  azs             = each.value.azs
  cidr            = each.value.cidr
  name            = each.value.name
  private_subnets = each.value.private_subnets
  public_subnets  = each.value.public_subnets
  tags            = each.value.tags
}

module "vpc_map_integrate_selected" {
  for_each        = local.vpc_map
  source          = "terraform-aws-modules/vpc/aws"
  version         = "4.0.1"
  azs             = each.value.azs
  cidr            = each.value.cidr
  name            = each.value.name
  private_subnets = each.value.private_subnets
  public_subnets  = each.value.public_subnets
  tags            = each.value.tags
}
