# Auto-generated by fogg. Do not edit
# Make improvements in fogg, so that everyone can benefit.

// module "foo_vpc" outputs
output "foo_azs" {
  value     = module.foo_vpc.azs
  sensitive = false
}
output "foo_cgw_arns" {
  value     = module.foo_vpc.cgw_arns
  sensitive = false
}
output "foo_cgw_ids" {
  value     = module.foo_vpc.cgw_ids
  sensitive = false
}
output "foo_database_internet_gateway_route_id" {
  value     = module.foo_vpc.database_internet_gateway_route_id
  sensitive = false
}
output "foo_database_ipv6_egress_route_id" {
  value     = module.foo_vpc.database_ipv6_egress_route_id
  sensitive = false
}
output "foo_database_nat_gateway_route_ids" {
  value     = module.foo_vpc.database_nat_gateway_route_ids
  sensitive = false
}
output "foo_database_network_acl_arn" {
  value     = module.foo_vpc.database_network_acl_arn
  sensitive = false
}
output "foo_database_network_acl_id" {
  value     = module.foo_vpc.database_network_acl_id
  sensitive = false
}
output "foo_database_route_table_association_ids" {
  value     = module.foo_vpc.database_route_table_association_ids
  sensitive = false
}
output "foo_database_route_table_ids" {
  value     = module.foo_vpc.database_route_table_ids
  sensitive = false
}
output "foo_database_subnet_arns" {
  value     = module.foo_vpc.database_subnet_arns
  sensitive = false
}
output "foo_database_subnet_group" {
  value     = module.foo_vpc.database_subnet_group
  sensitive = false
}
output "foo_database_subnet_group_name" {
  value     = module.foo_vpc.database_subnet_group_name
  sensitive = false
}
output "foo_database_subnets" {
  value     = module.foo_vpc.database_subnets
  sensitive = false
}
output "foo_database_subnets_cidr_blocks" {
  value     = module.foo_vpc.database_subnets_cidr_blocks
  sensitive = false
}
output "foo_database_subnets_ipv6_cidr_blocks" {
  value     = module.foo_vpc.database_subnets_ipv6_cidr_blocks
  sensitive = false
}
output "foo_default_network_acl_id" {
  value     = module.foo_vpc.default_network_acl_id
  sensitive = false
}
output "foo_default_route_table_id" {
  value     = module.foo_vpc.default_route_table_id
  sensitive = false
}
output "foo_default_security_group_id" {
  value     = module.foo_vpc.default_security_group_id
  sensitive = false
}
output "foo_default_vpc_arn" {
  value     = module.foo_vpc.default_vpc_arn
  sensitive = false
}
output "foo_default_vpc_cidr_block" {
  value     = module.foo_vpc.default_vpc_cidr_block
  sensitive = false
}
output "foo_default_vpc_default_network_acl_id" {
  value     = module.foo_vpc.default_vpc_default_network_acl_id
  sensitive = false
}
output "foo_default_vpc_default_route_table_id" {
  value     = module.foo_vpc.default_vpc_default_route_table_id
  sensitive = false
}
output "foo_default_vpc_default_security_group_id" {
  value     = module.foo_vpc.default_vpc_default_security_group_id
  sensitive = false
}
output "foo_default_vpc_enable_dns_hostnames" {
  value     = module.foo_vpc.default_vpc_enable_dns_hostnames
  sensitive = false
}
output "foo_default_vpc_enable_dns_support" {
  value     = module.foo_vpc.default_vpc_enable_dns_support
  sensitive = false
}
output "foo_default_vpc_id" {
  value     = module.foo_vpc.default_vpc_id
  sensitive = false
}
output "foo_default_vpc_instance_tenancy" {
  value     = module.foo_vpc.default_vpc_instance_tenancy
  sensitive = false
}
output "foo_default_vpc_main_route_table_id" {
  value     = module.foo_vpc.default_vpc_main_route_table_id
  sensitive = false
}
output "foo_dhcp_options_id" {
  value     = module.foo_vpc.dhcp_options_id
  sensitive = false
}
output "foo_egress_only_internet_gateway_id" {
  value     = module.foo_vpc.egress_only_internet_gateway_id
  sensitive = false
}
output "foo_elasticache_network_acl_arn" {
  value     = module.foo_vpc.elasticache_network_acl_arn
  sensitive = false
}
output "foo_elasticache_network_acl_id" {
  value     = module.foo_vpc.elasticache_network_acl_id
  sensitive = false
}
output "foo_elasticache_route_table_association_ids" {
  value     = module.foo_vpc.elasticache_route_table_association_ids
  sensitive = false
}
output "foo_elasticache_route_table_ids" {
  value     = module.foo_vpc.elasticache_route_table_ids
  sensitive = false
}
output "foo_elasticache_subnet_arns" {
  value     = module.foo_vpc.elasticache_subnet_arns
  sensitive = false
}
output "foo_elasticache_subnet_group" {
  value     = module.foo_vpc.elasticache_subnet_group
  sensitive = false
}
output "foo_elasticache_subnet_group_name" {
  value     = module.foo_vpc.elasticache_subnet_group_name
  sensitive = false
}
output "foo_elasticache_subnets" {
  value     = module.foo_vpc.elasticache_subnets
  sensitive = false
}
output "foo_elasticache_subnets_cidr_blocks" {
  value     = module.foo_vpc.elasticache_subnets_cidr_blocks
  sensitive = false
}
output "foo_elasticache_subnets_ipv6_cidr_blocks" {
  value     = module.foo_vpc.elasticache_subnets_ipv6_cidr_blocks
  sensitive = false
}
output "foo_igw_arn" {
  value     = module.foo_vpc.igw_arn
  sensitive = false
}
output "foo_igw_id" {
  value     = module.foo_vpc.igw_id
  sensitive = false
}
output "foo_intra_network_acl_arn" {
  value     = module.foo_vpc.intra_network_acl_arn
  sensitive = false
}
output "foo_intra_network_acl_id" {
  value     = module.foo_vpc.intra_network_acl_id
  sensitive = false
}
output "foo_intra_route_table_association_ids" {
  value     = module.foo_vpc.intra_route_table_association_ids
  sensitive = false
}
output "foo_intra_route_table_ids" {
  value     = module.foo_vpc.intra_route_table_ids
  sensitive = false
}
output "foo_intra_subnet_arns" {
  value     = module.foo_vpc.intra_subnet_arns
  sensitive = false
}
output "foo_intra_subnets" {
  value     = module.foo_vpc.intra_subnets
  sensitive = false
}
output "foo_intra_subnets_cidr_blocks" {
  value     = module.foo_vpc.intra_subnets_cidr_blocks
  sensitive = false
}
output "foo_intra_subnets_ipv6_cidr_blocks" {
  value     = module.foo_vpc.intra_subnets_ipv6_cidr_blocks
  sensitive = false
}
output "foo_name" {
  value     = module.foo_vpc.name
  sensitive = false
}
output "foo_nat_ids" {
  value     = module.foo_vpc.nat_ids
  sensitive = false
}
output "foo_nat_public_ips" {
  value     = module.foo_vpc.nat_public_ips
  sensitive = false
}
output "foo_natgw_ids" {
  value     = module.foo_vpc.natgw_ids
  sensitive = false
}
output "foo_outpost_network_acl_arn" {
  value     = module.foo_vpc.outpost_network_acl_arn
  sensitive = false
}
output "foo_outpost_network_acl_id" {
  value     = module.foo_vpc.outpost_network_acl_id
  sensitive = false
}
output "foo_outpost_subnet_arns" {
  value     = module.foo_vpc.outpost_subnet_arns
  sensitive = false
}
output "foo_outpost_subnets" {
  value     = module.foo_vpc.outpost_subnets
  sensitive = false
}
output "foo_outpost_subnets_cidr_blocks" {
  value     = module.foo_vpc.outpost_subnets_cidr_blocks
  sensitive = false
}
output "foo_outpost_subnets_ipv6_cidr_blocks" {
  value     = module.foo_vpc.outpost_subnets_ipv6_cidr_blocks
  sensitive = false
}
output "foo_private_ipv6_egress_route_ids" {
  value     = module.foo_vpc.private_ipv6_egress_route_ids
  sensitive = false
}
output "foo_private_nat_gateway_route_ids" {
  value     = module.foo_vpc.private_nat_gateway_route_ids
  sensitive = false
}
output "foo_private_network_acl_arn" {
  value     = module.foo_vpc.private_network_acl_arn
  sensitive = false
}
output "foo_private_network_acl_id" {
  value     = module.foo_vpc.private_network_acl_id
  sensitive = false
}
output "foo_private_route_table_association_ids" {
  value     = module.foo_vpc.private_route_table_association_ids
  sensitive = false
}
output "foo_private_route_table_ids" {
  value     = module.foo_vpc.private_route_table_ids
  sensitive = false
}
output "foo_private_subnet_arns" {
  value     = module.foo_vpc.private_subnet_arns
  sensitive = false
}
output "foo_private_subnets" {
  value     = module.foo_vpc.private_subnets
  sensitive = false
}
output "foo_private_subnets_cidr_blocks" {
  value     = module.foo_vpc.private_subnets_cidr_blocks
  sensitive = false
}
output "foo_private_subnets_ipv6_cidr_blocks" {
  value     = module.foo_vpc.private_subnets_ipv6_cidr_blocks
  sensitive = false
}
output "foo_public_internet_gateway_ipv6_route_id" {
  value     = module.foo_vpc.public_internet_gateway_ipv6_route_id
  sensitive = false
}
output "foo_public_internet_gateway_route_id" {
  value     = module.foo_vpc.public_internet_gateway_route_id
  sensitive = false
}
output "foo_public_network_acl_arn" {
  value     = module.foo_vpc.public_network_acl_arn
  sensitive = false
}
output "foo_public_network_acl_id" {
  value     = module.foo_vpc.public_network_acl_id
  sensitive = false
}
output "foo_public_route_table_association_ids" {
  value     = module.foo_vpc.public_route_table_association_ids
  sensitive = false
}
output "foo_public_route_table_ids" {
  value     = module.foo_vpc.public_route_table_ids
  sensitive = false
}
output "foo_public_subnet_arns" {
  value     = module.foo_vpc.public_subnet_arns
  sensitive = false
}
output "foo_public_subnets" {
  value     = module.foo_vpc.public_subnets
  sensitive = false
}
output "foo_public_subnets_cidr_blocks" {
  value     = module.foo_vpc.public_subnets_cidr_blocks
  sensitive = false
}
output "foo_public_subnets_ipv6_cidr_blocks" {
  value     = module.foo_vpc.public_subnets_ipv6_cidr_blocks
  sensitive = false
}
output "foo_redshift_network_acl_arn" {
  value     = module.foo_vpc.redshift_network_acl_arn
  sensitive = false
}
output "foo_redshift_network_acl_id" {
  value     = module.foo_vpc.redshift_network_acl_id
  sensitive = false
}
output "foo_redshift_public_route_table_association_ids" {
  value     = module.foo_vpc.redshift_public_route_table_association_ids
  sensitive = false
}
output "foo_redshift_route_table_association_ids" {
  value     = module.foo_vpc.redshift_route_table_association_ids
  sensitive = false
}
output "foo_redshift_route_table_ids" {
  value     = module.foo_vpc.redshift_route_table_ids
  sensitive = false
}
output "foo_redshift_subnet_arns" {
  value     = module.foo_vpc.redshift_subnet_arns
  sensitive = false
}
output "foo_redshift_subnet_group" {
  value     = module.foo_vpc.redshift_subnet_group
  sensitive = false
}
output "foo_redshift_subnets" {
  value     = module.foo_vpc.redshift_subnets
  sensitive = false
}
output "foo_redshift_subnets_cidr_blocks" {
  value     = module.foo_vpc.redshift_subnets_cidr_blocks
  sensitive = false
}
output "foo_redshift_subnets_ipv6_cidr_blocks" {
  value     = module.foo_vpc.redshift_subnets_ipv6_cidr_blocks
  sensitive = false
}
output "foo_this_customer_gateway" {
  value     = module.foo_vpc.this_customer_gateway
  sensitive = false
}
output "foo_vgw_arn" {
  value     = module.foo_vpc.vgw_arn
  sensitive = false
}
output "foo_vgw_id" {
  value     = module.foo_vpc.vgw_id
  sensitive = false
}
output "foo_vpc_arn" {
  value     = module.foo_vpc.vpc_arn
  sensitive = false
}
output "foo_vpc_cidr_block" {
  value     = module.foo_vpc.vpc_cidr_block
  sensitive = false
}
output "foo_vpc_enable_dns_hostnames" {
  value     = module.foo_vpc.vpc_enable_dns_hostnames
  sensitive = false
}
output "foo_vpc_enable_dns_support" {
  value     = module.foo_vpc.vpc_enable_dns_support
  sensitive = false
}
output "foo_vpc_flow_log_cloudwatch_iam_role_arn" {
  value     = module.foo_vpc.vpc_flow_log_cloudwatch_iam_role_arn
  sensitive = false
}
output "foo_vpc_flow_log_destination_arn" {
  value     = module.foo_vpc.vpc_flow_log_destination_arn
  sensitive = false
}
output "foo_vpc_flow_log_destination_type" {
  value     = module.foo_vpc.vpc_flow_log_destination_type
  sensitive = false
}
output "foo_vpc_flow_log_id" {
  value     = module.foo_vpc.vpc_flow_log_id
  sensitive = false
}
output "foo_vpc_id" {
  value     = module.foo_vpc.vpc_id
  sensitive = false
}
output "foo_vpc_instance_tenancy" {
  value     = module.foo_vpc.vpc_instance_tenancy
  sensitive = false
}
output "foo_vpc_ipv6_association_id" {
  value     = module.foo_vpc.vpc_ipv6_association_id
  sensitive = false
}
output "foo_vpc_ipv6_cidr_block" {
  value     = module.foo_vpc.vpc_ipv6_cidr_block
  sensitive = false
}
output "foo_vpc_main_route_table_id" {
  value     = module.foo_vpc.vpc_main_route_table_id
  sensitive = false
}
output "foo_vpc_owner_id" {
  value     = module.foo_vpc.vpc_owner_id
  sensitive = false
}
output "foo_vpc_secondary_cidr_blocks" {
  value     = module.foo_vpc.vpc_secondary_cidr_blocks
  sensitive = false
}
// module "bar_vpc" outputs
output "bar_azs" {
  value     = module.bar_vpc.azs
  sensitive = false
}
output "bar_cgw_arns" {
  value     = module.bar_vpc.cgw_arns
  sensitive = false
}
output "bar_cgw_ids" {
  value     = module.bar_vpc.cgw_ids
  sensitive = false
}
output "bar_database_internet_gateway_route_id" {
  value     = module.bar_vpc.database_internet_gateway_route_id
  sensitive = false
}
output "bar_database_ipv6_egress_route_id" {
  value     = module.bar_vpc.database_ipv6_egress_route_id
  sensitive = false
}
output "bar_database_nat_gateway_route_ids" {
  value     = module.bar_vpc.database_nat_gateway_route_ids
  sensitive = false
}
output "bar_database_network_acl_arn" {
  value     = module.bar_vpc.database_network_acl_arn
  sensitive = false
}
output "bar_database_network_acl_id" {
  value     = module.bar_vpc.database_network_acl_id
  sensitive = false
}
output "bar_database_route_table_association_ids" {
  value     = module.bar_vpc.database_route_table_association_ids
  sensitive = false
}
output "bar_database_route_table_ids" {
  value     = module.bar_vpc.database_route_table_ids
  sensitive = false
}
output "bar_database_subnet_arns" {
  value     = module.bar_vpc.database_subnet_arns
  sensitive = false
}
output "bar_database_subnet_group" {
  value     = module.bar_vpc.database_subnet_group
  sensitive = false
}
output "bar_database_subnet_group_name" {
  value     = module.bar_vpc.database_subnet_group_name
  sensitive = false
}
output "bar_database_subnets" {
  value     = module.bar_vpc.database_subnets
  sensitive = false
}
output "bar_database_subnets_cidr_blocks" {
  value     = module.bar_vpc.database_subnets_cidr_blocks
  sensitive = false
}
output "bar_database_subnets_ipv6_cidr_blocks" {
  value     = module.bar_vpc.database_subnets_ipv6_cidr_blocks
  sensitive = false
}
output "bar_default_network_acl_id" {
  value     = module.bar_vpc.default_network_acl_id
  sensitive = false
}
output "bar_default_route_table_id" {
  value     = module.bar_vpc.default_route_table_id
  sensitive = false
}
output "bar_default_security_group_id" {
  value     = module.bar_vpc.default_security_group_id
  sensitive = false
}
output "bar_default_vpc_arn" {
  value     = module.bar_vpc.default_vpc_arn
  sensitive = false
}
output "bar_default_vpc_cidr_block" {
  value     = module.bar_vpc.default_vpc_cidr_block
  sensitive = false
}
output "bar_default_vpc_default_network_acl_id" {
  value     = module.bar_vpc.default_vpc_default_network_acl_id
  sensitive = false
}
output "bar_default_vpc_default_route_table_id" {
  value     = module.bar_vpc.default_vpc_default_route_table_id
  sensitive = false
}
output "bar_default_vpc_default_security_group_id" {
  value     = module.bar_vpc.default_vpc_default_security_group_id
  sensitive = false
}
output "bar_default_vpc_enable_dns_hostnames" {
  value     = module.bar_vpc.default_vpc_enable_dns_hostnames
  sensitive = false
}
output "bar_default_vpc_enable_dns_support" {
  value     = module.bar_vpc.default_vpc_enable_dns_support
  sensitive = false
}
output "bar_default_vpc_id" {
  value     = module.bar_vpc.default_vpc_id
  sensitive = false
}
output "bar_default_vpc_instance_tenancy" {
  value     = module.bar_vpc.default_vpc_instance_tenancy
  sensitive = false
}
output "bar_default_vpc_main_route_table_id" {
  value     = module.bar_vpc.default_vpc_main_route_table_id
  sensitive = false
}
output "bar_dhcp_options_id" {
  value     = module.bar_vpc.dhcp_options_id
  sensitive = false
}
output "bar_egress_only_internet_gateway_id" {
  value     = module.bar_vpc.egress_only_internet_gateway_id
  sensitive = false
}
output "bar_elasticache_network_acl_arn" {
  value     = module.bar_vpc.elasticache_network_acl_arn
  sensitive = false
}
output "bar_elasticache_network_acl_id" {
  value     = module.bar_vpc.elasticache_network_acl_id
  sensitive = false
}
output "bar_elasticache_route_table_association_ids" {
  value     = module.bar_vpc.elasticache_route_table_association_ids
  sensitive = false
}
output "bar_elasticache_route_table_ids" {
  value     = module.bar_vpc.elasticache_route_table_ids
  sensitive = false
}
output "bar_elasticache_subnet_arns" {
  value     = module.bar_vpc.elasticache_subnet_arns
  sensitive = false
}
output "bar_elasticache_subnet_group" {
  value     = module.bar_vpc.elasticache_subnet_group
  sensitive = false
}
output "bar_elasticache_subnet_group_name" {
  value     = module.bar_vpc.elasticache_subnet_group_name
  sensitive = false
}
output "bar_elasticache_subnets" {
  value     = module.bar_vpc.elasticache_subnets
  sensitive = false
}
output "bar_elasticache_subnets_cidr_blocks" {
  value     = module.bar_vpc.elasticache_subnets_cidr_blocks
  sensitive = false
}
output "bar_elasticache_subnets_ipv6_cidr_blocks" {
  value     = module.bar_vpc.elasticache_subnets_ipv6_cidr_blocks
  sensitive = false
}
output "bar_igw_arn" {
  value     = module.bar_vpc.igw_arn
  sensitive = false
}
output "bar_igw_id" {
  value     = module.bar_vpc.igw_id
  sensitive = false
}
output "bar_intra_network_acl_arn" {
  value     = module.bar_vpc.intra_network_acl_arn
  sensitive = false
}
output "bar_intra_network_acl_id" {
  value     = module.bar_vpc.intra_network_acl_id
  sensitive = false
}
output "bar_intra_route_table_association_ids" {
  value     = module.bar_vpc.intra_route_table_association_ids
  sensitive = false
}
output "bar_intra_route_table_ids" {
  value     = module.bar_vpc.intra_route_table_ids
  sensitive = false
}
output "bar_intra_subnet_arns" {
  value     = module.bar_vpc.intra_subnet_arns
  sensitive = false
}
output "bar_intra_subnets" {
  value     = module.bar_vpc.intra_subnets
  sensitive = false
}
output "bar_intra_subnets_cidr_blocks" {
  value     = module.bar_vpc.intra_subnets_cidr_blocks
  sensitive = false
}
output "bar_intra_subnets_ipv6_cidr_blocks" {
  value     = module.bar_vpc.intra_subnets_ipv6_cidr_blocks
  sensitive = false
}
output "bar_name" {
  value     = module.bar_vpc.name
  sensitive = false
}
output "bar_nat_ids" {
  value     = module.bar_vpc.nat_ids
  sensitive = false
}
output "bar_nat_public_ips" {
  value     = module.bar_vpc.nat_public_ips
  sensitive = false
}
output "bar_natgw_ids" {
  value     = module.bar_vpc.natgw_ids
  sensitive = false
}
output "bar_outpost_network_acl_arn" {
  value     = module.bar_vpc.outpost_network_acl_arn
  sensitive = false
}
output "bar_outpost_network_acl_id" {
  value     = module.bar_vpc.outpost_network_acl_id
  sensitive = false
}
output "bar_outpost_subnet_arns" {
  value     = module.bar_vpc.outpost_subnet_arns
  sensitive = false
}
output "bar_outpost_subnets" {
  value     = module.bar_vpc.outpost_subnets
  sensitive = false
}
output "bar_outpost_subnets_cidr_blocks" {
  value     = module.bar_vpc.outpost_subnets_cidr_blocks
  sensitive = false
}
output "bar_outpost_subnets_ipv6_cidr_blocks" {
  value     = module.bar_vpc.outpost_subnets_ipv6_cidr_blocks
  sensitive = false
}
output "bar_private_ipv6_egress_route_ids" {
  value     = module.bar_vpc.private_ipv6_egress_route_ids
  sensitive = false
}
output "bar_private_nat_gateway_route_ids" {
  value     = module.bar_vpc.private_nat_gateway_route_ids
  sensitive = false
}
output "bar_private_network_acl_arn" {
  value     = module.bar_vpc.private_network_acl_arn
  sensitive = false
}
output "bar_private_network_acl_id" {
  value     = module.bar_vpc.private_network_acl_id
  sensitive = false
}
output "bar_private_route_table_association_ids" {
  value     = module.bar_vpc.private_route_table_association_ids
  sensitive = false
}
output "bar_private_route_table_ids" {
  value     = module.bar_vpc.private_route_table_ids
  sensitive = false
}
output "bar_private_subnet_arns" {
  value     = module.bar_vpc.private_subnet_arns
  sensitive = false
}
output "bar_private_subnets" {
  value     = module.bar_vpc.private_subnets
  sensitive = false
}
output "bar_private_subnets_cidr_blocks" {
  value     = module.bar_vpc.private_subnets_cidr_blocks
  sensitive = false
}
output "bar_private_subnets_ipv6_cidr_blocks" {
  value     = module.bar_vpc.private_subnets_ipv6_cidr_blocks
  sensitive = false
}
output "bar_public_internet_gateway_ipv6_route_id" {
  value     = module.bar_vpc.public_internet_gateway_ipv6_route_id
  sensitive = false
}
output "bar_public_internet_gateway_route_id" {
  value     = module.bar_vpc.public_internet_gateway_route_id
  sensitive = false
}
output "bar_public_network_acl_arn" {
  value     = module.bar_vpc.public_network_acl_arn
  sensitive = false
}
output "bar_public_network_acl_id" {
  value     = module.bar_vpc.public_network_acl_id
  sensitive = false
}
output "bar_public_route_table_association_ids" {
  value     = module.bar_vpc.public_route_table_association_ids
  sensitive = false
}
output "bar_public_route_table_ids" {
  value     = module.bar_vpc.public_route_table_ids
  sensitive = false
}
output "bar_public_subnet_arns" {
  value     = module.bar_vpc.public_subnet_arns
  sensitive = false
}
output "bar_public_subnets" {
  value     = module.bar_vpc.public_subnets
  sensitive = false
}
output "bar_public_subnets_cidr_blocks" {
  value     = module.bar_vpc.public_subnets_cidr_blocks
  sensitive = false
}
output "bar_public_subnets_ipv6_cidr_blocks" {
  value     = module.bar_vpc.public_subnets_ipv6_cidr_blocks
  sensitive = false
}
output "bar_redshift_network_acl_arn" {
  value     = module.bar_vpc.redshift_network_acl_arn
  sensitive = false
}
output "bar_redshift_network_acl_id" {
  value     = module.bar_vpc.redshift_network_acl_id
  sensitive = false
}
output "bar_redshift_public_route_table_association_ids" {
  value     = module.bar_vpc.redshift_public_route_table_association_ids
  sensitive = false
}
output "bar_redshift_route_table_association_ids" {
  value     = module.bar_vpc.redshift_route_table_association_ids
  sensitive = false
}
output "bar_redshift_route_table_ids" {
  value     = module.bar_vpc.redshift_route_table_ids
  sensitive = false
}
output "bar_redshift_subnet_arns" {
  value     = module.bar_vpc.redshift_subnet_arns
  sensitive = false
}
output "bar_redshift_subnet_group" {
  value     = module.bar_vpc.redshift_subnet_group
  sensitive = false
}
output "bar_redshift_subnets" {
  value     = module.bar_vpc.redshift_subnets
  sensitive = false
}
output "bar_redshift_subnets_cidr_blocks" {
  value     = module.bar_vpc.redshift_subnets_cidr_blocks
  sensitive = false
}
output "bar_redshift_subnets_ipv6_cidr_blocks" {
  value     = module.bar_vpc.redshift_subnets_ipv6_cidr_blocks
  sensitive = false
}
output "bar_this_customer_gateway" {
  value     = module.bar_vpc.this_customer_gateway
  sensitive = false
}
output "bar_vgw_arn" {
  value     = module.bar_vpc.vgw_arn
  sensitive = false
}
output "bar_vgw_id" {
  value     = module.bar_vpc.vgw_id
  sensitive = false
}
output "bar_vpc_arn" {
  value     = module.bar_vpc.vpc_arn
  sensitive = false
}
output "bar_vpc_cidr_block" {
  value     = module.bar_vpc.vpc_cidr_block
  sensitive = false
}
output "bar_vpc_enable_dns_hostnames" {
  value     = module.bar_vpc.vpc_enable_dns_hostnames
  sensitive = false
}
output "bar_vpc_enable_dns_support" {
  value     = module.bar_vpc.vpc_enable_dns_support
  sensitive = false
}
output "bar_vpc_flow_log_cloudwatch_iam_role_arn" {
  value     = module.bar_vpc.vpc_flow_log_cloudwatch_iam_role_arn
  sensitive = false
}
output "bar_vpc_flow_log_destination_arn" {
  value     = module.bar_vpc.vpc_flow_log_destination_arn
  sensitive = false
}
output "bar_vpc_flow_log_destination_type" {
  value     = module.bar_vpc.vpc_flow_log_destination_type
  sensitive = false
}
output "bar_vpc_flow_log_id" {
  value     = module.bar_vpc.vpc_flow_log_id
  sensitive = false
}
output "bar_vpc_id" {
  value     = module.bar_vpc.vpc_id
  sensitive = false
}
output "bar_vpc_instance_tenancy" {
  value     = module.bar_vpc.vpc_instance_tenancy
  sensitive = false
}
output "bar_vpc_ipv6_association_id" {
  value     = module.bar_vpc.vpc_ipv6_association_id
  sensitive = false
}
output "bar_vpc_ipv6_cidr_block" {
  value     = module.bar_vpc.vpc_ipv6_cidr_block
  sensitive = false
}
output "bar_vpc_main_route_table_id" {
  value     = module.bar_vpc.vpc_main_route_table_id
  sensitive = false
}
output "bar_vpc_owner_id" {
  value     = module.bar_vpc.vpc_owner_id
  sensitive = false
}
output "bar_vpc_secondary_cidr_blocks" {
  value     = module.bar_vpc.vpc_secondary_cidr_blocks
  sensitive = false
}
// module "baz_vpc" outputs
output "baz_azs" {
  value     = module.baz_vpc.azs
  sensitive = false
}
output "baz_cgw_arns" {
  value     = module.baz_vpc.cgw_arns
  sensitive = false
}
output "baz_cgw_ids" {
  value     = module.baz_vpc.cgw_ids
  sensitive = false
}
output "baz_database_internet_gateway_route_id" {
  value     = module.baz_vpc.database_internet_gateway_route_id
  sensitive = false
}
output "baz_database_ipv6_egress_route_id" {
  value     = module.baz_vpc.database_ipv6_egress_route_id
  sensitive = false
}
output "baz_database_nat_gateway_route_ids" {
  value     = module.baz_vpc.database_nat_gateway_route_ids
  sensitive = false
}
output "baz_database_network_acl_arn" {
  value     = module.baz_vpc.database_network_acl_arn
  sensitive = false
}
output "baz_database_network_acl_id" {
  value     = module.baz_vpc.database_network_acl_id
  sensitive = false
}
output "baz_database_route_table_association_ids" {
  value     = module.baz_vpc.database_route_table_association_ids
  sensitive = false
}
output "baz_database_route_table_ids" {
  value     = module.baz_vpc.database_route_table_ids
  sensitive = false
}
output "baz_database_subnet_arns" {
  value     = module.baz_vpc.database_subnet_arns
  sensitive = false
}
output "baz_database_subnet_group" {
  value     = module.baz_vpc.database_subnet_group
  sensitive = false
}
output "baz_database_subnet_group_name" {
  value     = module.baz_vpc.database_subnet_group_name
  sensitive = false
}
output "baz_database_subnets" {
  value     = module.baz_vpc.database_subnets
  sensitive = false
}
output "baz_database_subnets_cidr_blocks" {
  value     = module.baz_vpc.database_subnets_cidr_blocks
  sensitive = false
}
output "baz_database_subnets_ipv6_cidr_blocks" {
  value     = module.baz_vpc.database_subnets_ipv6_cidr_blocks
  sensitive = false
}
output "baz_default_network_acl_id" {
  value     = module.baz_vpc.default_network_acl_id
  sensitive = false
}
output "baz_default_route_table_id" {
  value     = module.baz_vpc.default_route_table_id
  sensitive = false
}
output "baz_default_security_group_id" {
  value     = module.baz_vpc.default_security_group_id
  sensitive = false
}
output "baz_default_vpc_arn" {
  value     = module.baz_vpc.default_vpc_arn
  sensitive = false
}
output "baz_default_vpc_cidr_block" {
  value     = module.baz_vpc.default_vpc_cidr_block
  sensitive = false
}
output "baz_default_vpc_default_network_acl_id" {
  value     = module.baz_vpc.default_vpc_default_network_acl_id
  sensitive = false
}
output "baz_default_vpc_default_route_table_id" {
  value     = module.baz_vpc.default_vpc_default_route_table_id
  sensitive = false
}
output "baz_default_vpc_default_security_group_id" {
  value     = module.baz_vpc.default_vpc_default_security_group_id
  sensitive = false
}
output "baz_default_vpc_enable_dns_hostnames" {
  value     = module.baz_vpc.default_vpc_enable_dns_hostnames
  sensitive = false
}
output "baz_default_vpc_enable_dns_support" {
  value     = module.baz_vpc.default_vpc_enable_dns_support
  sensitive = false
}
output "baz_default_vpc_id" {
  value     = module.baz_vpc.default_vpc_id
  sensitive = false
}
output "baz_default_vpc_instance_tenancy" {
  value     = module.baz_vpc.default_vpc_instance_tenancy
  sensitive = false
}
output "baz_default_vpc_main_route_table_id" {
  value     = module.baz_vpc.default_vpc_main_route_table_id
  sensitive = false
}
output "baz_dhcp_options_id" {
  value     = module.baz_vpc.dhcp_options_id
  sensitive = false
}
output "baz_egress_only_internet_gateway_id" {
  value     = module.baz_vpc.egress_only_internet_gateway_id
  sensitive = false
}
output "baz_elasticache_network_acl_arn" {
  value     = module.baz_vpc.elasticache_network_acl_arn
  sensitive = false
}
output "baz_elasticache_network_acl_id" {
  value     = module.baz_vpc.elasticache_network_acl_id
  sensitive = false
}
output "baz_elasticache_route_table_association_ids" {
  value     = module.baz_vpc.elasticache_route_table_association_ids
  sensitive = false
}
output "baz_elasticache_route_table_ids" {
  value     = module.baz_vpc.elasticache_route_table_ids
  sensitive = false
}
output "baz_elasticache_subnet_arns" {
  value     = module.baz_vpc.elasticache_subnet_arns
  sensitive = false
}
output "baz_elasticache_subnet_group" {
  value     = module.baz_vpc.elasticache_subnet_group
  sensitive = false
}
output "baz_elasticache_subnet_group_name" {
  value     = module.baz_vpc.elasticache_subnet_group_name
  sensitive = false
}
output "baz_elasticache_subnets" {
  value     = module.baz_vpc.elasticache_subnets
  sensitive = false
}
output "baz_elasticache_subnets_cidr_blocks" {
  value     = module.baz_vpc.elasticache_subnets_cidr_blocks
  sensitive = false
}
output "baz_elasticache_subnets_ipv6_cidr_blocks" {
  value     = module.baz_vpc.elasticache_subnets_ipv6_cidr_blocks
  sensitive = false
}
output "baz_igw_arn" {
  value     = module.baz_vpc.igw_arn
  sensitive = false
}
output "baz_igw_id" {
  value     = module.baz_vpc.igw_id
  sensitive = false
}
output "baz_intra_network_acl_arn" {
  value     = module.baz_vpc.intra_network_acl_arn
  sensitive = false
}
output "baz_intra_network_acl_id" {
  value     = module.baz_vpc.intra_network_acl_id
  sensitive = false
}
output "baz_intra_route_table_association_ids" {
  value     = module.baz_vpc.intra_route_table_association_ids
  sensitive = false
}
output "baz_intra_route_table_ids" {
  value     = module.baz_vpc.intra_route_table_ids
  sensitive = false
}
output "baz_intra_subnet_arns" {
  value     = module.baz_vpc.intra_subnet_arns
  sensitive = false
}
output "baz_intra_subnets" {
  value     = module.baz_vpc.intra_subnets
  sensitive = false
}
output "baz_intra_subnets_cidr_blocks" {
  value     = module.baz_vpc.intra_subnets_cidr_blocks
  sensitive = false
}
output "baz_intra_subnets_ipv6_cidr_blocks" {
  value     = module.baz_vpc.intra_subnets_ipv6_cidr_blocks
  sensitive = false
}
output "baz_name" {
  value     = module.baz_vpc.name
  sensitive = false
}
output "baz_nat_ids" {
  value     = module.baz_vpc.nat_ids
  sensitive = false
}
output "baz_nat_public_ips" {
  value     = module.baz_vpc.nat_public_ips
  sensitive = false
}
output "baz_natgw_ids" {
  value     = module.baz_vpc.natgw_ids
  sensitive = false
}
output "baz_outpost_network_acl_arn" {
  value     = module.baz_vpc.outpost_network_acl_arn
  sensitive = false
}
output "baz_outpost_network_acl_id" {
  value     = module.baz_vpc.outpost_network_acl_id
  sensitive = false
}
output "baz_outpost_subnet_arns" {
  value     = module.baz_vpc.outpost_subnet_arns
  sensitive = false
}
output "baz_outpost_subnets" {
  value     = module.baz_vpc.outpost_subnets
  sensitive = false
}
output "baz_outpost_subnets_cidr_blocks" {
  value     = module.baz_vpc.outpost_subnets_cidr_blocks
  sensitive = false
}
output "baz_outpost_subnets_ipv6_cidr_blocks" {
  value     = module.baz_vpc.outpost_subnets_ipv6_cidr_blocks
  sensitive = false
}
output "baz_private_ipv6_egress_route_ids" {
  value     = module.baz_vpc.private_ipv6_egress_route_ids
  sensitive = false
}
output "baz_private_nat_gateway_route_ids" {
  value     = module.baz_vpc.private_nat_gateway_route_ids
  sensitive = false
}
output "baz_private_network_acl_arn" {
  value     = module.baz_vpc.private_network_acl_arn
  sensitive = false
}
output "baz_private_network_acl_id" {
  value     = module.baz_vpc.private_network_acl_id
  sensitive = false
}
output "baz_private_route_table_association_ids" {
  value     = module.baz_vpc.private_route_table_association_ids
  sensitive = false
}
output "baz_private_route_table_ids" {
  value     = module.baz_vpc.private_route_table_ids
  sensitive = false
}
output "baz_private_subnet_arns" {
  value     = module.baz_vpc.private_subnet_arns
  sensitive = false
}
output "baz_private_subnets" {
  value     = module.baz_vpc.private_subnets
  sensitive = false
}
output "baz_private_subnets_cidr_blocks" {
  value     = module.baz_vpc.private_subnets_cidr_blocks
  sensitive = false
}
output "baz_private_subnets_ipv6_cidr_blocks" {
  value     = module.baz_vpc.private_subnets_ipv6_cidr_blocks
  sensitive = false
}
output "baz_public_internet_gateway_ipv6_route_id" {
  value     = module.baz_vpc.public_internet_gateway_ipv6_route_id
  sensitive = false
}
output "baz_public_internet_gateway_route_id" {
  value     = module.baz_vpc.public_internet_gateway_route_id
  sensitive = false
}
output "baz_public_network_acl_arn" {
  value     = module.baz_vpc.public_network_acl_arn
  sensitive = false
}
output "baz_public_network_acl_id" {
  value     = module.baz_vpc.public_network_acl_id
  sensitive = false
}
output "baz_public_route_table_association_ids" {
  value     = module.baz_vpc.public_route_table_association_ids
  sensitive = false
}
output "baz_public_route_table_ids" {
  value     = module.baz_vpc.public_route_table_ids
  sensitive = false
}
output "baz_public_subnet_arns" {
  value     = module.baz_vpc.public_subnet_arns
  sensitive = false
}
output "baz_public_subnets" {
  value     = module.baz_vpc.public_subnets
  sensitive = false
}
output "baz_public_subnets_cidr_blocks" {
  value     = module.baz_vpc.public_subnets_cidr_blocks
  sensitive = false
}
output "baz_public_subnets_ipv6_cidr_blocks" {
  value     = module.baz_vpc.public_subnets_ipv6_cidr_blocks
  sensitive = false
}
output "baz_redshift_network_acl_arn" {
  value     = module.baz_vpc.redshift_network_acl_arn
  sensitive = false
}
output "baz_redshift_network_acl_id" {
  value     = module.baz_vpc.redshift_network_acl_id
  sensitive = false
}
output "baz_redshift_public_route_table_association_ids" {
  value     = module.baz_vpc.redshift_public_route_table_association_ids
  sensitive = false
}
output "baz_redshift_route_table_association_ids" {
  value     = module.baz_vpc.redshift_route_table_association_ids
  sensitive = false
}
output "baz_redshift_route_table_ids" {
  value     = module.baz_vpc.redshift_route_table_ids
  sensitive = false
}
output "baz_redshift_subnet_arns" {
  value     = module.baz_vpc.redshift_subnet_arns
  sensitive = false
}
output "baz_redshift_subnet_group" {
  value     = module.baz_vpc.redshift_subnet_group
  sensitive = false
}
output "baz_redshift_subnets" {
  value     = module.baz_vpc.redshift_subnets
  sensitive = false
}
output "baz_redshift_subnets_cidr_blocks" {
  value     = module.baz_vpc.redshift_subnets_cidr_blocks
  sensitive = false
}
output "baz_redshift_subnets_ipv6_cidr_blocks" {
  value     = module.baz_vpc.redshift_subnets_ipv6_cidr_blocks
  sensitive = false
}
output "baz_this_customer_gateway" {
  value     = module.baz_vpc.this_customer_gateway
  sensitive = false
}
output "baz_vgw_arn" {
  value     = module.baz_vpc.vgw_arn
  sensitive = false
}
output "baz_vgw_id" {
  value     = module.baz_vpc.vgw_id
  sensitive = false
}
output "baz_vpc_arn" {
  value     = module.baz_vpc.vpc_arn
  sensitive = false
}
output "baz_vpc_cidr_block" {
  value     = module.baz_vpc.vpc_cidr_block
  sensitive = false
}
output "baz_vpc_enable_dns_hostnames" {
  value     = module.baz_vpc.vpc_enable_dns_hostnames
  sensitive = false
}
output "baz_vpc_enable_dns_support" {
  value     = module.baz_vpc.vpc_enable_dns_support
  sensitive = false
}
output "baz_vpc_flow_log_cloudwatch_iam_role_arn" {
  value     = module.baz_vpc.vpc_flow_log_cloudwatch_iam_role_arn
  sensitive = false
}
output "baz_vpc_flow_log_destination_arn" {
  value     = module.baz_vpc.vpc_flow_log_destination_arn
  sensitive = false
}
output "baz_vpc_flow_log_destination_type" {
  value     = module.baz_vpc.vpc_flow_log_destination_type
  sensitive = false
}
output "baz_vpc_flow_log_id" {
  value     = module.baz_vpc.vpc_flow_log_id
  sensitive = false
}
output "baz_vpc_id" {
  value     = module.baz_vpc.vpc_id
  sensitive = false
}
output "baz_vpc_instance_tenancy" {
  value     = module.baz_vpc.vpc_instance_tenancy
  sensitive = false
}
output "baz_vpc_ipv6_association_id" {
  value     = module.baz_vpc.vpc_ipv6_association_id
  sensitive = false
}
output "baz_vpc_ipv6_cidr_block" {
  value     = module.baz_vpc.vpc_ipv6_cidr_block
  sensitive = false
}
output "baz_vpc_main_route_table_id" {
  value     = module.baz_vpc.vpc_main_route_table_id
  sensitive = false
}
output "baz_vpc_owner_id" {
  value     = module.baz_vpc.vpc_owner_id
  sensitive = false
}
output "baz_vpc_secondary_cidr_blocks" {
  value     = module.baz_vpc.vpc_secondary_cidr_blocks
  sensitive = false
}
// module "corge_vpc" outputs
output "corge_azs" {
  value     = module.corge_vpc.azs
  sensitive = false
}
output "corge_cgw_arns" {
  value     = module.corge_vpc.cgw_arns
  sensitive = false
}
output "corge_cgw_ids" {
  value     = module.corge_vpc.cgw_ids
  sensitive = false
}
output "corge_database_internet_gateway_route_id" {
  value     = module.corge_vpc.database_internet_gateway_route_id
  sensitive = false
}
output "corge_database_ipv6_egress_route_id" {
  value     = module.corge_vpc.database_ipv6_egress_route_id
  sensitive = false
}
output "corge_database_nat_gateway_route_ids" {
  value     = module.corge_vpc.database_nat_gateway_route_ids
  sensitive = false
}
output "corge_database_network_acl_arn" {
  value     = module.corge_vpc.database_network_acl_arn
  sensitive = false
}
output "corge_database_network_acl_id" {
  value     = module.corge_vpc.database_network_acl_id
  sensitive = false
}
output "corge_database_route_table_association_ids" {
  value     = module.corge_vpc.database_route_table_association_ids
  sensitive = false
}
output "corge_database_route_table_ids" {
  value     = module.corge_vpc.database_route_table_ids
  sensitive = false
}
output "corge_database_subnet_arns" {
  value     = module.corge_vpc.database_subnet_arns
  sensitive = false
}
output "corge_database_subnet_group" {
  value     = module.corge_vpc.database_subnet_group
  sensitive = false
}
output "corge_database_subnet_group_name" {
  value     = module.corge_vpc.database_subnet_group_name
  sensitive = false
}
output "corge_database_subnets" {
  value     = module.corge_vpc.database_subnets
  sensitive = false
}
output "corge_database_subnets_cidr_blocks" {
  value     = module.corge_vpc.database_subnets_cidr_blocks
  sensitive = false
}
output "corge_database_subnets_ipv6_cidr_blocks" {
  value     = module.corge_vpc.database_subnets_ipv6_cidr_blocks
  sensitive = false
}
output "corge_default_network_acl_id" {
  value     = module.corge_vpc.default_network_acl_id
  sensitive = false
}
output "corge_default_route_table_id" {
  value     = module.corge_vpc.default_route_table_id
  sensitive = false
}
output "corge_default_security_group_id" {
  value     = module.corge_vpc.default_security_group_id
  sensitive = false
}
output "corge_default_vpc_arn" {
  value     = module.corge_vpc.default_vpc_arn
  sensitive = false
}
output "corge_default_vpc_cidr_block" {
  value     = module.corge_vpc.default_vpc_cidr_block
  sensitive = false
}
output "corge_default_vpc_default_network_acl_id" {
  value     = module.corge_vpc.default_vpc_default_network_acl_id
  sensitive = false
}
output "corge_default_vpc_default_route_table_id" {
  value     = module.corge_vpc.default_vpc_default_route_table_id
  sensitive = false
}
output "corge_default_vpc_default_security_group_id" {
  value     = module.corge_vpc.default_vpc_default_security_group_id
  sensitive = false
}
output "corge_default_vpc_enable_dns_hostnames" {
  value     = module.corge_vpc.default_vpc_enable_dns_hostnames
  sensitive = false
}
output "corge_default_vpc_enable_dns_support" {
  value     = module.corge_vpc.default_vpc_enable_dns_support
  sensitive = false
}
output "corge_default_vpc_id" {
  value     = module.corge_vpc.default_vpc_id
  sensitive = false
}
output "corge_default_vpc_instance_tenancy" {
  value     = module.corge_vpc.default_vpc_instance_tenancy
  sensitive = false
}
output "corge_default_vpc_main_route_table_id" {
  value     = module.corge_vpc.default_vpc_main_route_table_id
  sensitive = false
}
output "corge_dhcp_options_id" {
  value     = module.corge_vpc.dhcp_options_id
  sensitive = false
}
output "corge_egress_only_internet_gateway_id" {
  value     = module.corge_vpc.egress_only_internet_gateway_id
  sensitive = false
}
output "corge_elasticache_network_acl_arn" {
  value     = module.corge_vpc.elasticache_network_acl_arn
  sensitive = false
}
output "corge_elasticache_network_acl_id" {
  value     = module.corge_vpc.elasticache_network_acl_id
  sensitive = false
}
output "corge_elasticache_route_table_association_ids" {
  value     = module.corge_vpc.elasticache_route_table_association_ids
  sensitive = false
}
output "corge_elasticache_route_table_ids" {
  value     = module.corge_vpc.elasticache_route_table_ids
  sensitive = false
}
output "corge_elasticache_subnet_arns" {
  value     = module.corge_vpc.elasticache_subnet_arns
  sensitive = false
}
output "corge_elasticache_subnet_group" {
  value     = module.corge_vpc.elasticache_subnet_group
  sensitive = false
}
output "corge_elasticache_subnet_group_name" {
  value     = module.corge_vpc.elasticache_subnet_group_name
  sensitive = false
}
output "corge_elasticache_subnets" {
  value     = module.corge_vpc.elasticache_subnets
  sensitive = false
}
output "corge_elasticache_subnets_cidr_blocks" {
  value     = module.corge_vpc.elasticache_subnets_cidr_blocks
  sensitive = false
}
output "corge_elasticache_subnets_ipv6_cidr_blocks" {
  value     = module.corge_vpc.elasticache_subnets_ipv6_cidr_blocks
  sensitive = false
}
output "corge_igw_arn" {
  value     = module.corge_vpc.igw_arn
  sensitive = false
}
output "corge_igw_id" {
  value     = module.corge_vpc.igw_id
  sensitive = false
}
output "corge_intra_network_acl_arn" {
  value     = module.corge_vpc.intra_network_acl_arn
  sensitive = false
}
output "corge_intra_network_acl_id" {
  value     = module.corge_vpc.intra_network_acl_id
  sensitive = false
}
output "corge_intra_route_table_association_ids" {
  value     = module.corge_vpc.intra_route_table_association_ids
  sensitive = false
}
output "corge_intra_route_table_ids" {
  value     = module.corge_vpc.intra_route_table_ids
  sensitive = false
}
output "corge_intra_subnet_arns" {
  value     = module.corge_vpc.intra_subnet_arns
  sensitive = false
}
output "corge_intra_subnets" {
  value     = module.corge_vpc.intra_subnets
  sensitive = false
}
output "corge_intra_subnets_cidr_blocks" {
  value     = module.corge_vpc.intra_subnets_cidr_blocks
  sensitive = false
}
output "corge_intra_subnets_ipv6_cidr_blocks" {
  value     = module.corge_vpc.intra_subnets_ipv6_cidr_blocks
  sensitive = false
}
output "corge_name" {
  value     = module.corge_vpc.name
  sensitive = false
}
output "corge_nat_ids" {
  value     = module.corge_vpc.nat_ids
  sensitive = false
}
output "corge_nat_public_ips" {
  value     = module.corge_vpc.nat_public_ips
  sensitive = false
}
output "corge_natgw_ids" {
  value     = module.corge_vpc.natgw_ids
  sensitive = false
}
output "corge_outpost_network_acl_arn" {
  value     = module.corge_vpc.outpost_network_acl_arn
  sensitive = false
}
output "corge_outpost_network_acl_id" {
  value     = module.corge_vpc.outpost_network_acl_id
  sensitive = false
}
output "corge_outpost_subnet_arns" {
  value     = module.corge_vpc.outpost_subnet_arns
  sensitive = false
}
output "corge_outpost_subnets" {
  value     = module.corge_vpc.outpost_subnets
  sensitive = false
}
output "corge_outpost_subnets_cidr_blocks" {
  value     = module.corge_vpc.outpost_subnets_cidr_blocks
  sensitive = false
}
output "corge_outpost_subnets_ipv6_cidr_blocks" {
  value     = module.corge_vpc.outpost_subnets_ipv6_cidr_blocks
  sensitive = false
}
output "corge_private_ipv6_egress_route_ids" {
  value     = module.corge_vpc.private_ipv6_egress_route_ids
  sensitive = false
}
output "corge_private_nat_gateway_route_ids" {
  value     = module.corge_vpc.private_nat_gateway_route_ids
  sensitive = false
}
output "corge_private_network_acl_arn" {
  value     = module.corge_vpc.private_network_acl_arn
  sensitive = false
}
output "corge_private_network_acl_id" {
  value     = module.corge_vpc.private_network_acl_id
  sensitive = false
}
output "corge_private_route_table_association_ids" {
  value     = module.corge_vpc.private_route_table_association_ids
  sensitive = false
}
output "corge_private_route_table_ids" {
  value     = module.corge_vpc.private_route_table_ids
  sensitive = false
}
output "corge_private_subnet_arns" {
  value     = module.corge_vpc.private_subnet_arns
  sensitive = false
}
output "corge_private_subnets" {
  value     = module.corge_vpc.private_subnets
  sensitive = false
}
output "corge_private_subnets_cidr_blocks" {
  value     = module.corge_vpc.private_subnets_cidr_blocks
  sensitive = false
}
output "corge_private_subnets_ipv6_cidr_blocks" {
  value     = module.corge_vpc.private_subnets_ipv6_cidr_blocks
  sensitive = false
}
output "corge_public_internet_gateway_ipv6_route_id" {
  value     = module.corge_vpc.public_internet_gateway_ipv6_route_id
  sensitive = false
}
output "corge_public_internet_gateway_route_id" {
  value     = module.corge_vpc.public_internet_gateway_route_id
  sensitive = false
}
output "corge_public_network_acl_arn" {
  value     = module.corge_vpc.public_network_acl_arn
  sensitive = false
}
output "corge_public_network_acl_id" {
  value     = module.corge_vpc.public_network_acl_id
  sensitive = false
}
output "corge_public_route_table_association_ids" {
  value     = module.corge_vpc.public_route_table_association_ids
  sensitive = false
}
output "corge_public_route_table_ids" {
  value     = module.corge_vpc.public_route_table_ids
  sensitive = false
}
output "corge_public_subnet_arns" {
  value     = module.corge_vpc.public_subnet_arns
  sensitive = false
}
output "corge_public_subnets" {
  value     = module.corge_vpc.public_subnets
  sensitive = false
}
output "corge_public_subnets_cidr_blocks" {
  value     = module.corge_vpc.public_subnets_cidr_blocks
  sensitive = false
}
output "corge_public_subnets_ipv6_cidr_blocks" {
  value     = module.corge_vpc.public_subnets_ipv6_cidr_blocks
  sensitive = false
}
output "corge_redshift_network_acl_arn" {
  value     = module.corge_vpc.redshift_network_acl_arn
  sensitive = false
}
output "corge_redshift_network_acl_id" {
  value     = module.corge_vpc.redshift_network_acl_id
  sensitive = false
}
output "corge_redshift_public_route_table_association_ids" {
  value     = module.corge_vpc.redshift_public_route_table_association_ids
  sensitive = false
}
output "corge_redshift_route_table_association_ids" {
  value     = module.corge_vpc.redshift_route_table_association_ids
  sensitive = false
}
output "corge_redshift_route_table_ids" {
  value     = module.corge_vpc.redshift_route_table_ids
  sensitive = false
}
output "corge_redshift_subnet_arns" {
  value     = module.corge_vpc.redshift_subnet_arns
  sensitive = false
}
output "corge_redshift_subnet_group" {
  value     = module.corge_vpc.redshift_subnet_group
  sensitive = false
}
output "corge_redshift_subnets" {
  value     = module.corge_vpc.redshift_subnets
  sensitive = false
}
output "corge_redshift_subnets_cidr_blocks" {
  value     = module.corge_vpc.redshift_subnets_cidr_blocks
  sensitive = false
}
output "corge_redshift_subnets_ipv6_cidr_blocks" {
  value     = module.corge_vpc.redshift_subnets_ipv6_cidr_blocks
  sensitive = false
}
output "corge_this_customer_gateway" {
  value     = module.corge_vpc.this_customer_gateway
  sensitive = false
}
output "corge_vgw_arn" {
  value     = module.corge_vpc.vgw_arn
  sensitive = false
}
output "corge_vgw_id" {
  value     = module.corge_vpc.vgw_id
  sensitive = false
}
output "corge_vpc_arn" {
  value     = module.corge_vpc.vpc_arn
  sensitive = false
}
output "corge_vpc_cidr_block" {
  value     = module.corge_vpc.vpc_cidr_block
  sensitive = false
}
output "corge_vpc_enable_dns_hostnames" {
  value     = module.corge_vpc.vpc_enable_dns_hostnames
  sensitive = false
}
output "corge_vpc_enable_dns_support" {
  value     = module.corge_vpc.vpc_enable_dns_support
  sensitive = false
}
output "corge_vpc_flow_log_cloudwatch_iam_role_arn" {
  value     = module.corge_vpc.vpc_flow_log_cloudwatch_iam_role_arn
  sensitive = false
}
output "corge_vpc_flow_log_destination_arn" {
  value     = module.corge_vpc.vpc_flow_log_destination_arn
  sensitive = false
}
output "corge_vpc_flow_log_destination_type" {
  value     = module.corge_vpc.vpc_flow_log_destination_type
  sensitive = false
}
output "corge_vpc_flow_log_id" {
  value     = module.corge_vpc.vpc_flow_log_id
  sensitive = false
}
output "corge_vpc_id" {
  value     = module.corge_vpc.vpc_id
  sensitive = false
}
output "corge_vpc_instance_tenancy" {
  value     = module.corge_vpc.vpc_instance_tenancy
  sensitive = false
}
output "corge_vpc_ipv6_association_id" {
  value     = module.corge_vpc.vpc_ipv6_association_id
  sensitive = false
}
output "corge_vpc_ipv6_cidr_block" {
  value     = module.corge_vpc.vpc_ipv6_cidr_block
  sensitive = false
}
output "corge_vpc_main_route_table_id" {
  value     = module.corge_vpc.vpc_main_route_table_id
  sensitive = false
}
output "corge_vpc_owner_id" {
  value     = module.corge_vpc.vpc_owner_id
  sensitive = false
}
output "corge_vpc_secondary_cidr_blocks" {
  value     = module.corge_vpc.vpc_secondary_cidr_blocks
  sensitive = false
}
// module "grault_vpc" outputs
output "grault_azs" {
  value     = module.grault_vpc.azs
  sensitive = false
}
output "grault_cgw_arns" {
  value     = module.grault_vpc.cgw_arns
  sensitive = false
}
output "grault_cgw_ids" {
  value     = module.grault_vpc.cgw_ids
  sensitive = false
}
output "grault_database_internet_gateway_route_id" {
  value     = module.grault_vpc.database_internet_gateway_route_id
  sensitive = false
}
output "grault_database_ipv6_egress_route_id" {
  value     = module.grault_vpc.database_ipv6_egress_route_id
  sensitive = false
}
output "grault_database_nat_gateway_route_ids" {
  value     = module.grault_vpc.database_nat_gateway_route_ids
  sensitive = false
}
output "grault_database_network_acl_arn" {
  value     = module.grault_vpc.database_network_acl_arn
  sensitive = false
}
output "grault_database_network_acl_id" {
  value     = module.grault_vpc.database_network_acl_id
  sensitive = false
}
output "grault_database_route_table_association_ids" {
  value     = module.grault_vpc.database_route_table_association_ids
  sensitive = false
}
output "grault_database_route_table_ids" {
  value     = module.grault_vpc.database_route_table_ids
  sensitive = false
}
output "grault_database_subnet_arns" {
  value     = module.grault_vpc.database_subnet_arns
  sensitive = false
}
output "grault_database_subnet_group" {
  value     = module.grault_vpc.database_subnet_group
  sensitive = false
}
output "grault_database_subnet_group_name" {
  value     = module.grault_vpc.database_subnet_group_name
  sensitive = false
}
output "grault_database_subnets" {
  value     = module.grault_vpc.database_subnets
  sensitive = false
}
output "grault_database_subnets_cidr_blocks" {
  value     = module.grault_vpc.database_subnets_cidr_blocks
  sensitive = false
}
output "grault_database_subnets_ipv6_cidr_blocks" {
  value     = module.grault_vpc.database_subnets_ipv6_cidr_blocks
  sensitive = false
}
output "grault_default_network_acl_id" {
  value     = module.grault_vpc.default_network_acl_id
  sensitive = false
}
output "grault_default_route_table_id" {
  value     = module.grault_vpc.default_route_table_id
  sensitive = false
}
output "grault_default_security_group_id" {
  value     = module.grault_vpc.default_security_group_id
  sensitive = false
}
output "grault_default_vpc_arn" {
  value     = module.grault_vpc.default_vpc_arn
  sensitive = false
}
output "grault_default_vpc_cidr_block" {
  value     = module.grault_vpc.default_vpc_cidr_block
  sensitive = false
}
output "grault_default_vpc_default_network_acl_id" {
  value     = module.grault_vpc.default_vpc_default_network_acl_id
  sensitive = false
}
output "grault_default_vpc_default_route_table_id" {
  value     = module.grault_vpc.default_vpc_default_route_table_id
  sensitive = false
}
output "grault_default_vpc_default_security_group_id" {
  value     = module.grault_vpc.default_vpc_default_security_group_id
  sensitive = false
}
output "grault_default_vpc_enable_dns_hostnames" {
  value     = module.grault_vpc.default_vpc_enable_dns_hostnames
  sensitive = false
}
output "grault_default_vpc_enable_dns_support" {
  value     = module.grault_vpc.default_vpc_enable_dns_support
  sensitive = false
}
output "grault_default_vpc_id" {
  value     = module.grault_vpc.default_vpc_id
  sensitive = false
}
output "grault_default_vpc_instance_tenancy" {
  value     = module.grault_vpc.default_vpc_instance_tenancy
  sensitive = false
}
output "grault_default_vpc_main_route_table_id" {
  value     = module.grault_vpc.default_vpc_main_route_table_id
  sensitive = false
}
output "grault_dhcp_options_id" {
  value     = module.grault_vpc.dhcp_options_id
  sensitive = false
}
output "grault_egress_only_internet_gateway_id" {
  value     = module.grault_vpc.egress_only_internet_gateway_id
  sensitive = false
}
output "grault_elasticache_network_acl_arn" {
  value     = module.grault_vpc.elasticache_network_acl_arn
  sensitive = false
}
output "grault_elasticache_network_acl_id" {
  value     = module.grault_vpc.elasticache_network_acl_id
  sensitive = false
}
output "grault_elasticache_route_table_association_ids" {
  value     = module.grault_vpc.elasticache_route_table_association_ids
  sensitive = false
}
output "grault_elasticache_route_table_ids" {
  value     = module.grault_vpc.elasticache_route_table_ids
  sensitive = false
}
output "grault_elasticache_subnet_arns" {
  value     = module.grault_vpc.elasticache_subnet_arns
  sensitive = false
}
output "grault_elasticache_subnet_group" {
  value     = module.grault_vpc.elasticache_subnet_group
  sensitive = false
}
output "grault_elasticache_subnet_group_name" {
  value     = module.grault_vpc.elasticache_subnet_group_name
  sensitive = false
}
output "grault_elasticache_subnets" {
  value     = module.grault_vpc.elasticache_subnets
  sensitive = false
}
output "grault_elasticache_subnets_cidr_blocks" {
  value     = module.grault_vpc.elasticache_subnets_cidr_blocks
  sensitive = false
}
output "grault_elasticache_subnets_ipv6_cidr_blocks" {
  value     = module.grault_vpc.elasticache_subnets_ipv6_cidr_blocks
  sensitive = false
}
output "grault_igw_arn" {
  value     = module.grault_vpc.igw_arn
  sensitive = false
}
output "grault_igw_id" {
  value     = module.grault_vpc.igw_id
  sensitive = false
}
output "grault_intra_network_acl_arn" {
  value     = module.grault_vpc.intra_network_acl_arn
  sensitive = false
}
output "grault_intra_network_acl_id" {
  value     = module.grault_vpc.intra_network_acl_id
  sensitive = false
}
output "grault_intra_route_table_association_ids" {
  value     = module.grault_vpc.intra_route_table_association_ids
  sensitive = false
}
output "grault_intra_route_table_ids" {
  value     = module.grault_vpc.intra_route_table_ids
  sensitive = false
}
output "grault_intra_subnet_arns" {
  value     = module.grault_vpc.intra_subnet_arns
  sensitive = false
}
output "grault_intra_subnets" {
  value     = module.grault_vpc.intra_subnets
  sensitive = false
}
output "grault_intra_subnets_cidr_blocks" {
  value     = module.grault_vpc.intra_subnets_cidr_blocks
  sensitive = false
}
output "grault_intra_subnets_ipv6_cidr_blocks" {
  value     = module.grault_vpc.intra_subnets_ipv6_cidr_blocks
  sensitive = false
}
output "grault_name" {
  value     = module.grault_vpc.name
  sensitive = false
}
output "grault_nat_ids" {
  value     = module.grault_vpc.nat_ids
  sensitive = false
}
output "grault_nat_public_ips" {
  value     = module.grault_vpc.nat_public_ips
  sensitive = false
}
output "grault_natgw_ids" {
  value     = module.grault_vpc.natgw_ids
  sensitive = false
}
output "grault_outpost_network_acl_arn" {
  value     = module.grault_vpc.outpost_network_acl_arn
  sensitive = false
}
output "grault_outpost_network_acl_id" {
  value     = module.grault_vpc.outpost_network_acl_id
  sensitive = false
}
output "grault_outpost_subnet_arns" {
  value     = module.grault_vpc.outpost_subnet_arns
  sensitive = false
}
output "grault_outpost_subnets" {
  value     = module.grault_vpc.outpost_subnets
  sensitive = false
}
output "grault_outpost_subnets_cidr_blocks" {
  value     = module.grault_vpc.outpost_subnets_cidr_blocks
  sensitive = false
}
output "grault_outpost_subnets_ipv6_cidr_blocks" {
  value     = module.grault_vpc.outpost_subnets_ipv6_cidr_blocks
  sensitive = false
}
output "grault_private_ipv6_egress_route_ids" {
  value     = module.grault_vpc.private_ipv6_egress_route_ids
  sensitive = false
}
output "grault_private_nat_gateway_route_ids" {
  value     = module.grault_vpc.private_nat_gateway_route_ids
  sensitive = false
}
output "grault_private_network_acl_arn" {
  value     = module.grault_vpc.private_network_acl_arn
  sensitive = false
}
output "grault_private_network_acl_id" {
  value     = module.grault_vpc.private_network_acl_id
  sensitive = false
}
output "grault_private_route_table_association_ids" {
  value     = module.grault_vpc.private_route_table_association_ids
  sensitive = false
}
output "grault_private_route_table_ids" {
  value     = module.grault_vpc.private_route_table_ids
  sensitive = false
}
output "grault_private_subnet_arns" {
  value     = module.grault_vpc.private_subnet_arns
  sensitive = false
}
output "grault_private_subnets" {
  value     = module.grault_vpc.private_subnets
  sensitive = false
}
output "grault_private_subnets_cidr_blocks" {
  value     = module.grault_vpc.private_subnets_cidr_blocks
  sensitive = false
}
output "grault_private_subnets_ipv6_cidr_blocks" {
  value     = module.grault_vpc.private_subnets_ipv6_cidr_blocks
  sensitive = false
}
output "grault_public_internet_gateway_ipv6_route_id" {
  value     = module.grault_vpc.public_internet_gateway_ipv6_route_id
  sensitive = false
}
output "grault_public_internet_gateway_route_id" {
  value     = module.grault_vpc.public_internet_gateway_route_id
  sensitive = false
}
output "grault_public_network_acl_arn" {
  value     = module.grault_vpc.public_network_acl_arn
  sensitive = false
}
output "grault_public_network_acl_id" {
  value     = module.grault_vpc.public_network_acl_id
  sensitive = false
}
output "grault_public_route_table_association_ids" {
  value     = module.grault_vpc.public_route_table_association_ids
  sensitive = false
}
output "grault_public_route_table_ids" {
  value     = module.grault_vpc.public_route_table_ids
  sensitive = false
}
output "grault_public_subnet_arns" {
  value     = module.grault_vpc.public_subnet_arns
  sensitive = false
}
output "grault_public_subnets" {
  value     = module.grault_vpc.public_subnets
  sensitive = false
}
output "grault_public_subnets_cidr_blocks" {
  value     = module.grault_vpc.public_subnets_cidr_blocks
  sensitive = false
}
output "grault_public_subnets_ipv6_cidr_blocks" {
  value     = module.grault_vpc.public_subnets_ipv6_cidr_blocks
  sensitive = false
}
output "grault_redshift_network_acl_arn" {
  value     = module.grault_vpc.redshift_network_acl_arn
  sensitive = false
}
output "grault_redshift_network_acl_id" {
  value     = module.grault_vpc.redshift_network_acl_id
  sensitive = false
}
output "grault_redshift_public_route_table_association_ids" {
  value     = module.grault_vpc.redshift_public_route_table_association_ids
  sensitive = false
}
output "grault_redshift_route_table_association_ids" {
  value     = module.grault_vpc.redshift_route_table_association_ids
  sensitive = false
}
output "grault_redshift_route_table_ids" {
  value     = module.grault_vpc.redshift_route_table_ids
  sensitive = false
}
output "grault_redshift_subnet_arns" {
  value     = module.grault_vpc.redshift_subnet_arns
  sensitive = false
}
output "grault_redshift_subnet_group" {
  value     = module.grault_vpc.redshift_subnet_group
  sensitive = false
}
output "grault_redshift_subnets" {
  value     = module.grault_vpc.redshift_subnets
  sensitive = false
}
output "grault_redshift_subnets_cidr_blocks" {
  value     = module.grault_vpc.redshift_subnets_cidr_blocks
  sensitive = false
}
output "grault_redshift_subnets_ipv6_cidr_blocks" {
  value     = module.grault_vpc.redshift_subnets_ipv6_cidr_blocks
  sensitive = false
}
output "grault_this_customer_gateway" {
  value     = module.grault_vpc.this_customer_gateway
  sensitive = false
}
output "grault_vgw_arn" {
  value     = module.grault_vpc.vgw_arn
  sensitive = false
}
output "grault_vgw_id" {
  value     = module.grault_vpc.vgw_id
  sensitive = false
}
output "grault_vpc_arn" {
  value     = module.grault_vpc.vpc_arn
  sensitive = false
}
output "grault_vpc_cidr_block" {
  value     = module.grault_vpc.vpc_cidr_block
  sensitive = false
}
output "grault_vpc_enable_dns_hostnames" {
  value     = module.grault_vpc.vpc_enable_dns_hostnames
  sensitive = false
}
output "grault_vpc_enable_dns_support" {
  value     = module.grault_vpc.vpc_enable_dns_support
  sensitive = false
}
output "grault_vpc_flow_log_cloudwatch_iam_role_arn" {
  value     = module.grault_vpc.vpc_flow_log_cloudwatch_iam_role_arn
  sensitive = false
}
output "grault_vpc_flow_log_destination_arn" {
  value     = module.grault_vpc.vpc_flow_log_destination_arn
  sensitive = false
}
output "grault_vpc_flow_log_destination_type" {
  value     = module.grault_vpc.vpc_flow_log_destination_type
  sensitive = false
}
output "grault_vpc_flow_log_id" {
  value     = module.grault_vpc.vpc_flow_log_id
  sensitive = false
}
output "grault_vpc_id" {
  value     = module.grault_vpc.vpc_id
  sensitive = false
}
output "grault_vpc_instance_tenancy" {
  value     = module.grault_vpc.vpc_instance_tenancy
  sensitive = false
}
output "grault_vpc_ipv6_association_id" {
  value     = module.grault_vpc.vpc_ipv6_association_id
  sensitive = false
}
output "grault_vpc_ipv6_cidr_block" {
  value     = module.grault_vpc.vpc_ipv6_cidr_block
  sensitive = false
}
output "grault_vpc_main_route_table_id" {
  value     = module.grault_vpc.vpc_main_route_table_id
  sensitive = false
}
output "grault_vpc_owner_id" {
  value     = module.grault_vpc.vpc_owner_id
  sensitive = false
}
output "grault_vpc_secondary_cidr_blocks" {
  value     = module.grault_vpc.vpc_secondary_cidr_blocks
  sensitive = false
}
// module "qux_vpc" outputs
output "qux_azs" {
  value     = module.qux_vpc.azs
  sensitive = false
}
output "qux_cgw_arns" {
  value     = module.qux_vpc.cgw_arns
  sensitive = false
}
output "qux_cgw_ids" {
  value     = module.qux_vpc.cgw_ids
  sensitive = false
}
output "qux_database_internet_gateway_route_id" {
  value     = module.qux_vpc.database_internet_gateway_route_id
  sensitive = false
}
output "qux_database_ipv6_egress_route_id" {
  value     = module.qux_vpc.database_ipv6_egress_route_id
  sensitive = false
}
output "qux_database_nat_gateway_route_ids" {
  value     = module.qux_vpc.database_nat_gateway_route_ids
  sensitive = false
}
output "qux_database_network_acl_arn" {
  value     = module.qux_vpc.database_network_acl_arn
  sensitive = false
}
output "qux_database_network_acl_id" {
  value     = module.qux_vpc.database_network_acl_id
  sensitive = false
}
output "qux_database_route_table_association_ids" {
  value     = module.qux_vpc.database_route_table_association_ids
  sensitive = false
}
output "qux_database_route_table_ids" {
  value     = module.qux_vpc.database_route_table_ids
  sensitive = false
}
output "qux_database_subnet_arns" {
  value     = module.qux_vpc.database_subnet_arns
  sensitive = false
}
output "qux_database_subnet_group" {
  value     = module.qux_vpc.database_subnet_group
  sensitive = false
}
output "qux_database_subnet_group_name" {
  value     = module.qux_vpc.database_subnet_group_name
  sensitive = false
}
output "qux_database_subnets" {
  value     = module.qux_vpc.database_subnets
  sensitive = false
}
output "qux_database_subnets_cidr_blocks" {
  value     = module.qux_vpc.database_subnets_cidr_blocks
  sensitive = false
}
output "qux_database_subnets_ipv6_cidr_blocks" {
  value     = module.qux_vpc.database_subnets_ipv6_cidr_blocks
  sensitive = false
}
output "qux_default_network_acl_id" {
  value     = module.qux_vpc.default_network_acl_id
  sensitive = false
}
output "qux_default_route_table_id" {
  value     = module.qux_vpc.default_route_table_id
  sensitive = false
}
output "qux_default_security_group_id" {
  value     = module.qux_vpc.default_security_group_id
  sensitive = false
}
output "qux_default_vpc_arn" {
  value     = module.qux_vpc.default_vpc_arn
  sensitive = false
}
output "qux_default_vpc_cidr_block" {
  value     = module.qux_vpc.default_vpc_cidr_block
  sensitive = false
}
output "qux_default_vpc_default_network_acl_id" {
  value     = module.qux_vpc.default_vpc_default_network_acl_id
  sensitive = false
}
output "qux_default_vpc_default_route_table_id" {
  value     = module.qux_vpc.default_vpc_default_route_table_id
  sensitive = false
}
output "qux_default_vpc_default_security_group_id" {
  value     = module.qux_vpc.default_vpc_default_security_group_id
  sensitive = false
}
output "qux_default_vpc_enable_dns_hostnames" {
  value     = module.qux_vpc.default_vpc_enable_dns_hostnames
  sensitive = false
}
output "qux_default_vpc_enable_dns_support" {
  value     = module.qux_vpc.default_vpc_enable_dns_support
  sensitive = false
}
output "qux_default_vpc_id" {
  value     = module.qux_vpc.default_vpc_id
  sensitive = false
}
output "qux_default_vpc_instance_tenancy" {
  value     = module.qux_vpc.default_vpc_instance_tenancy
  sensitive = false
}
output "qux_default_vpc_main_route_table_id" {
  value     = module.qux_vpc.default_vpc_main_route_table_id
  sensitive = false
}
output "qux_dhcp_options_id" {
  value     = module.qux_vpc.dhcp_options_id
  sensitive = false
}
output "qux_egress_only_internet_gateway_id" {
  value     = module.qux_vpc.egress_only_internet_gateway_id
  sensitive = false
}
output "qux_elasticache_network_acl_arn" {
  value     = module.qux_vpc.elasticache_network_acl_arn
  sensitive = false
}
output "qux_elasticache_network_acl_id" {
  value     = module.qux_vpc.elasticache_network_acl_id
  sensitive = false
}
output "qux_elasticache_route_table_association_ids" {
  value     = module.qux_vpc.elasticache_route_table_association_ids
  sensitive = false
}
output "qux_elasticache_route_table_ids" {
  value     = module.qux_vpc.elasticache_route_table_ids
  sensitive = false
}
output "qux_elasticache_subnet_arns" {
  value     = module.qux_vpc.elasticache_subnet_arns
  sensitive = false
}
output "qux_elasticache_subnet_group" {
  value     = module.qux_vpc.elasticache_subnet_group
  sensitive = false
}
output "qux_elasticache_subnet_group_name" {
  value     = module.qux_vpc.elasticache_subnet_group_name
  sensitive = false
}
output "qux_elasticache_subnets" {
  value     = module.qux_vpc.elasticache_subnets
  sensitive = false
}
output "qux_elasticache_subnets_cidr_blocks" {
  value     = module.qux_vpc.elasticache_subnets_cidr_blocks
  sensitive = false
}
output "qux_elasticache_subnets_ipv6_cidr_blocks" {
  value     = module.qux_vpc.elasticache_subnets_ipv6_cidr_blocks
  sensitive = false
}
output "qux_igw_arn" {
  value     = module.qux_vpc.igw_arn
  sensitive = false
}
output "qux_igw_id" {
  value     = module.qux_vpc.igw_id
  sensitive = false
}
output "qux_intra_network_acl_arn" {
  value     = module.qux_vpc.intra_network_acl_arn
  sensitive = false
}
output "qux_intra_network_acl_id" {
  value     = module.qux_vpc.intra_network_acl_id
  sensitive = false
}
output "qux_intra_route_table_association_ids" {
  value     = module.qux_vpc.intra_route_table_association_ids
  sensitive = false
}
output "qux_intra_route_table_ids" {
  value     = module.qux_vpc.intra_route_table_ids
  sensitive = false
}
output "qux_intra_subnet_arns" {
  value     = module.qux_vpc.intra_subnet_arns
  sensitive = false
}
output "qux_intra_subnets" {
  value     = module.qux_vpc.intra_subnets
  sensitive = false
}
output "qux_intra_subnets_cidr_blocks" {
  value     = module.qux_vpc.intra_subnets_cidr_blocks
  sensitive = false
}
output "qux_intra_subnets_ipv6_cidr_blocks" {
  value     = module.qux_vpc.intra_subnets_ipv6_cidr_blocks
  sensitive = false
}
output "qux_name" {
  value     = module.qux_vpc.name
  sensitive = false
}
output "qux_nat_ids" {
  value     = module.qux_vpc.nat_ids
  sensitive = false
}
output "qux_nat_public_ips" {
  value     = module.qux_vpc.nat_public_ips
  sensitive = false
}
output "qux_natgw_ids" {
  value     = module.qux_vpc.natgw_ids
  sensitive = false
}
output "qux_outpost_network_acl_arn" {
  value     = module.qux_vpc.outpost_network_acl_arn
  sensitive = false
}
output "qux_outpost_network_acl_id" {
  value     = module.qux_vpc.outpost_network_acl_id
  sensitive = false
}
output "qux_outpost_subnet_arns" {
  value     = module.qux_vpc.outpost_subnet_arns
  sensitive = false
}
output "qux_outpost_subnets" {
  value     = module.qux_vpc.outpost_subnets
  sensitive = false
}
output "qux_outpost_subnets_cidr_blocks" {
  value     = module.qux_vpc.outpost_subnets_cidr_blocks
  sensitive = false
}
output "qux_outpost_subnets_ipv6_cidr_blocks" {
  value     = module.qux_vpc.outpost_subnets_ipv6_cidr_blocks
  sensitive = false
}
output "qux_private_ipv6_egress_route_ids" {
  value     = module.qux_vpc.private_ipv6_egress_route_ids
  sensitive = false
}
output "qux_private_nat_gateway_route_ids" {
  value     = module.qux_vpc.private_nat_gateway_route_ids
  sensitive = false
}
output "qux_private_network_acl_arn" {
  value     = module.qux_vpc.private_network_acl_arn
  sensitive = false
}
output "qux_private_network_acl_id" {
  value     = module.qux_vpc.private_network_acl_id
  sensitive = false
}
output "qux_private_route_table_association_ids" {
  value     = module.qux_vpc.private_route_table_association_ids
  sensitive = false
}
output "qux_private_route_table_ids" {
  value     = module.qux_vpc.private_route_table_ids
  sensitive = false
}
output "qux_private_subnet_arns" {
  value     = module.qux_vpc.private_subnet_arns
  sensitive = false
}
output "qux_private_subnets" {
  value     = module.qux_vpc.private_subnets
  sensitive = false
}
output "qux_private_subnets_cidr_blocks" {
  value     = module.qux_vpc.private_subnets_cidr_blocks
  sensitive = false
}
output "qux_private_subnets_ipv6_cidr_blocks" {
  value     = module.qux_vpc.private_subnets_ipv6_cidr_blocks
  sensitive = false
}
output "qux_public_internet_gateway_ipv6_route_id" {
  value     = module.qux_vpc.public_internet_gateway_ipv6_route_id
  sensitive = false
}
output "qux_public_internet_gateway_route_id" {
  value     = module.qux_vpc.public_internet_gateway_route_id
  sensitive = false
}
output "qux_public_network_acl_arn" {
  value     = module.qux_vpc.public_network_acl_arn
  sensitive = false
}
output "qux_public_network_acl_id" {
  value     = module.qux_vpc.public_network_acl_id
  sensitive = false
}
output "qux_public_route_table_association_ids" {
  value     = module.qux_vpc.public_route_table_association_ids
  sensitive = false
}
output "qux_public_route_table_ids" {
  value     = module.qux_vpc.public_route_table_ids
  sensitive = false
}
output "qux_public_subnet_arns" {
  value     = module.qux_vpc.public_subnet_arns
  sensitive = false
}
output "qux_public_subnets" {
  value     = module.qux_vpc.public_subnets
  sensitive = false
}
output "qux_public_subnets_cidr_blocks" {
  value     = module.qux_vpc.public_subnets_cidr_blocks
  sensitive = false
}
output "qux_public_subnets_ipv6_cidr_blocks" {
  value     = module.qux_vpc.public_subnets_ipv6_cidr_blocks
  sensitive = false
}
output "qux_redshift_network_acl_arn" {
  value     = module.qux_vpc.redshift_network_acl_arn
  sensitive = false
}
output "qux_redshift_network_acl_id" {
  value     = module.qux_vpc.redshift_network_acl_id
  sensitive = false
}
output "qux_redshift_public_route_table_association_ids" {
  value     = module.qux_vpc.redshift_public_route_table_association_ids
  sensitive = false
}
output "qux_redshift_route_table_association_ids" {
  value     = module.qux_vpc.redshift_route_table_association_ids
  sensitive = false
}
output "qux_redshift_route_table_ids" {
  value     = module.qux_vpc.redshift_route_table_ids
  sensitive = false
}
output "qux_redshift_subnet_arns" {
  value     = module.qux_vpc.redshift_subnet_arns
  sensitive = false
}
output "qux_redshift_subnet_group" {
  value     = module.qux_vpc.redshift_subnet_group
  sensitive = false
}
output "qux_redshift_subnets" {
  value     = module.qux_vpc.redshift_subnets
  sensitive = false
}
output "qux_redshift_subnets_cidr_blocks" {
  value     = module.qux_vpc.redshift_subnets_cidr_blocks
  sensitive = false
}
output "qux_redshift_subnets_ipv6_cidr_blocks" {
  value     = module.qux_vpc.redshift_subnets_ipv6_cidr_blocks
  sensitive = false
}
output "qux_this_customer_gateway" {
  value     = module.qux_vpc.this_customer_gateway
  sensitive = false
}
output "qux_vgw_arn" {
  value     = module.qux_vpc.vgw_arn
  sensitive = false
}
output "qux_vgw_id" {
  value     = module.qux_vpc.vgw_id
  sensitive = false
}
output "qux_vpc_arn" {
  value     = module.qux_vpc.vpc_arn
  sensitive = false
}
output "qux_vpc_cidr_block" {
  value     = module.qux_vpc.vpc_cidr_block
  sensitive = false
}
output "qux_vpc_enable_dns_hostnames" {
  value     = module.qux_vpc.vpc_enable_dns_hostnames
  sensitive = false
}
output "qux_vpc_enable_dns_support" {
  value     = module.qux_vpc.vpc_enable_dns_support
  sensitive = false
}
output "qux_vpc_flow_log_cloudwatch_iam_role_arn" {
  value     = module.qux_vpc.vpc_flow_log_cloudwatch_iam_role_arn
  sensitive = false
}
output "qux_vpc_flow_log_destination_arn" {
  value     = module.qux_vpc.vpc_flow_log_destination_arn
  sensitive = false
}
output "qux_vpc_flow_log_destination_type" {
  value     = module.qux_vpc.vpc_flow_log_destination_type
  sensitive = false
}
output "qux_vpc_flow_log_id" {
  value     = module.qux_vpc.vpc_flow_log_id
  sensitive = false
}
output "qux_vpc_id" {
  value     = module.qux_vpc.vpc_id
  sensitive = false
}
output "qux_vpc_instance_tenancy" {
  value     = module.qux_vpc.vpc_instance_tenancy
  sensitive = false
}
output "qux_vpc_ipv6_association_id" {
  value     = module.qux_vpc.vpc_ipv6_association_id
  sensitive = false
}
output "qux_vpc_ipv6_cidr_block" {
  value     = module.qux_vpc.vpc_ipv6_cidr_block
  sensitive = false
}
output "qux_vpc_main_route_table_id" {
  value     = module.qux_vpc.vpc_main_route_table_id
  sensitive = false
}
output "qux_vpc_owner_id" {
  value     = module.qux_vpc.vpc_owner_id
  sensitive = false
}
output "qux_vpc_secondary_cidr_blocks" {
  value     = module.qux_vpc.vpc_secondary_cidr_blocks
  sensitive = false
}
