# Auto-generated by fogg. Do not edit
# Make improvements in fogg, so that everyone can benefit.

// module "foo_vpc" ssm Parameter Store integration registry entries (non sensitive)
resource "aws_ssm_parameter" "foo_azs" {
  name           = "/${var.env}/${var.component}/foo_azs"
  type           = "String"
  tier           = "Standard"
  insecure_value = jsonencode(module.foo_vpc.azs)
  tags           = var.tags
}

resource "aws_ssm_parameter" "foo_cgw_arns" {
  name           = "/${var.env}/${var.component}/foo_cgw_arns"
  type           = "String"
  tier           = "Standard"
  insecure_value = jsonencode(module.foo_vpc.cgw_arns)
  tags           = var.tags
}

resource "aws_ssm_parameter" "foo_cgw_ids" {
  name           = "/${var.env}/${var.component}/foo_cgw_ids"
  type           = "String"
  tier           = "Standard"
  insecure_value = jsonencode(module.foo_vpc.cgw_ids)
  tags           = var.tags
}

resource "aws_ssm_parameter" "foo_database_internet_gateway_route_id" {
  name           = "/${var.env}/${var.component}/foo_database_internet_gateway_route_id"
  type           = "String"
  tier           = "Standard"
  insecure_value = jsonencode(module.foo_vpc.database_internet_gateway_route_id)
  tags           = var.tags
}

resource "aws_ssm_parameter" "foo_database_ipv6_egress_route_id" {
  name           = "/${var.env}/${var.component}/foo_database_ipv6_egress_route_id"
  type           = "String"
  tier           = "Standard"
  insecure_value = jsonencode(module.foo_vpc.database_ipv6_egress_route_id)
  tags           = var.tags
}

resource "aws_ssm_parameter" "foo_database_nat_gateway_route_ids" {
  name           = "/${var.env}/${var.component}/foo_database_nat_gateway_route_ids"
  type           = "String"
  tier           = "Standard"
  insecure_value = jsonencode(module.foo_vpc.database_nat_gateway_route_ids)
  tags           = var.tags
}

resource "aws_ssm_parameter" "foo_database_network_acl_arn" {
  name           = "/${var.env}/${var.component}/foo_database_network_acl_arn"
  type           = "String"
  tier           = "Standard"
  insecure_value = jsonencode(module.foo_vpc.database_network_acl_arn)
  tags           = var.tags
}

resource "aws_ssm_parameter" "foo_database_network_acl_id" {
  name           = "/${var.env}/${var.component}/foo_database_network_acl_id"
  type           = "String"
  tier           = "Standard"
  insecure_value = jsonencode(module.foo_vpc.database_network_acl_id)
  tags           = var.tags
}

resource "aws_ssm_parameter" "foo_database_route_table_association_ids" {
  name           = "/${var.env}/${var.component}/foo_database_route_table_association_ids"
  type           = "String"
  tier           = "Standard"
  insecure_value = jsonencode(module.foo_vpc.database_route_table_association_ids)
  tags           = var.tags
}

resource "aws_ssm_parameter" "foo_database_route_table_ids" {
  name           = "/${var.env}/${var.component}/foo_database_route_table_ids"
  type           = "String"
  tier           = "Standard"
  insecure_value = jsonencode(module.foo_vpc.database_route_table_ids)
  tags           = var.tags
}

resource "aws_ssm_parameter" "foo_database_subnet_arns" {
  name           = "/${var.env}/${var.component}/foo_database_subnet_arns"
  type           = "String"
  tier           = "Standard"
  insecure_value = jsonencode(module.foo_vpc.database_subnet_arns)
  tags           = var.tags
}

resource "aws_ssm_parameter" "foo_database_subnet_group" {
  name           = "/${var.env}/${var.component}/foo_database_subnet_group"
  type           = "String"
  tier           = "Standard"
  insecure_value = jsonencode(module.foo_vpc.database_subnet_group)
  tags           = var.tags
}

resource "aws_ssm_parameter" "foo_database_subnet_group_name" {
  name           = "/${var.env}/${var.component}/foo_database_subnet_group_name"
  type           = "String"
  tier           = "Standard"
  insecure_value = jsonencode(module.foo_vpc.database_subnet_group_name)
  tags           = var.tags
}

resource "aws_ssm_parameter" "foo_database_subnets" {
  name           = "/${var.env}/${var.component}/foo_database_subnets"
  type           = "String"
  tier           = "Standard"
  insecure_value = jsonencode(module.foo_vpc.database_subnets)
  tags           = var.tags
}

resource "aws_ssm_parameter" "foo_database_subnets_cidr_blocks" {
  name           = "/${var.env}/${var.component}/foo_database_subnets_cidr_blocks"
  type           = "String"
  tier           = "Standard"
  insecure_value = jsonencode(module.foo_vpc.database_subnets_cidr_blocks)
  tags           = var.tags
}

resource "aws_ssm_parameter" "foo_database_subnets_ipv6_cidr_blocks" {
  name           = "/${var.env}/${var.component}/foo_database_subnets_ipv6_cidr_blocks"
  type           = "String"
  tier           = "Standard"
  insecure_value = jsonencode(module.foo_vpc.database_subnets_ipv6_cidr_blocks)
  tags           = var.tags
}

resource "aws_ssm_parameter" "foo_default_network_acl_id" {
  name           = "/${var.env}/${var.component}/foo_default_network_acl_id"
  type           = "String"
  tier           = "Standard"
  insecure_value = jsonencode(module.foo_vpc.default_network_acl_id)
  tags           = var.tags
}

resource "aws_ssm_parameter" "foo_default_route_table_id" {
  name           = "/${var.env}/${var.component}/foo_default_route_table_id"
  type           = "String"
  tier           = "Standard"
  insecure_value = jsonencode(module.foo_vpc.default_route_table_id)
  tags           = var.tags
}

resource "aws_ssm_parameter" "foo_default_security_group_id" {
  name           = "/${var.env}/${var.component}/foo_default_security_group_id"
  type           = "String"
  tier           = "Standard"
  insecure_value = jsonencode(module.foo_vpc.default_security_group_id)
  tags           = var.tags
}

resource "aws_ssm_parameter" "foo_default_vpc_arn" {
  name           = "/${var.env}/${var.component}/foo_default_vpc_arn"
  type           = "String"
  tier           = "Standard"
  insecure_value = jsonencode(module.foo_vpc.default_vpc_arn)
  tags           = var.tags
}

resource "aws_ssm_parameter" "foo_default_vpc_cidr_block" {
  name           = "/${var.env}/${var.component}/foo_default_vpc_cidr_block"
  type           = "String"
  tier           = "Standard"
  insecure_value = jsonencode(module.foo_vpc.default_vpc_cidr_block)
  tags           = var.tags
}

resource "aws_ssm_parameter" "foo_default_vpc_default_network_acl_id" {
  name           = "/${var.env}/${var.component}/foo_default_vpc_default_network_acl_id"
  type           = "String"
  tier           = "Standard"
  insecure_value = jsonencode(module.foo_vpc.default_vpc_default_network_acl_id)
  tags           = var.tags
}

resource "aws_ssm_parameter" "foo_default_vpc_default_route_table_id" {
  name           = "/${var.env}/${var.component}/foo_default_vpc_default_route_table_id"
  type           = "String"
  tier           = "Standard"
  insecure_value = jsonencode(module.foo_vpc.default_vpc_default_route_table_id)
  tags           = var.tags
}

resource "aws_ssm_parameter" "foo_default_vpc_default_security_group_id" {
  name           = "/${var.env}/${var.component}/foo_default_vpc_default_security_group_id"
  type           = "String"
  tier           = "Standard"
  insecure_value = jsonencode(module.foo_vpc.default_vpc_default_security_group_id)
  tags           = var.tags
}

resource "aws_ssm_parameter" "foo_default_vpc_enable_dns_hostnames" {
  name           = "/${var.env}/${var.component}/foo_default_vpc_enable_dns_hostnames"
  type           = "String"
  tier           = "Standard"
  insecure_value = jsonencode(module.foo_vpc.default_vpc_enable_dns_hostnames)
  tags           = var.tags
}

resource "aws_ssm_parameter" "foo_default_vpc_enable_dns_support" {
  name           = "/${var.env}/${var.component}/foo_default_vpc_enable_dns_support"
  type           = "String"
  tier           = "Standard"
  insecure_value = jsonencode(module.foo_vpc.default_vpc_enable_dns_support)
  tags           = var.tags
}

resource "aws_ssm_parameter" "foo_default_vpc_id" {
  name           = "/${var.env}/${var.component}/foo_default_vpc_id"
  type           = "String"
  tier           = "Standard"
  insecure_value = jsonencode(module.foo_vpc.default_vpc_id)
  tags           = var.tags
}

resource "aws_ssm_parameter" "foo_default_vpc_instance_tenancy" {
  name           = "/${var.env}/${var.component}/foo_default_vpc_instance_tenancy"
  type           = "String"
  tier           = "Standard"
  insecure_value = jsonencode(module.foo_vpc.default_vpc_instance_tenancy)
  tags           = var.tags
}

resource "aws_ssm_parameter" "foo_default_vpc_main_route_table_id" {
  name           = "/${var.env}/${var.component}/foo_default_vpc_main_route_table_id"
  type           = "String"
  tier           = "Standard"
  insecure_value = jsonencode(module.foo_vpc.default_vpc_main_route_table_id)
  tags           = var.tags
}

resource "aws_ssm_parameter" "foo_dhcp_options_id" {
  name           = "/${var.env}/${var.component}/foo_dhcp_options_id"
  type           = "String"
  tier           = "Standard"
  insecure_value = jsonencode(module.foo_vpc.dhcp_options_id)
  tags           = var.tags
}

resource "aws_ssm_parameter" "foo_egress_only_internet_gateway_id" {
  name           = "/${var.env}/${var.component}/foo_egress_only_internet_gateway_id"
  type           = "String"
  tier           = "Standard"
  insecure_value = jsonencode(module.foo_vpc.egress_only_internet_gateway_id)
  tags           = var.tags
}

resource "aws_ssm_parameter" "foo_elasticache_network_acl_arn" {
  name           = "/${var.env}/${var.component}/foo_elasticache_network_acl_arn"
  type           = "String"
  tier           = "Standard"
  insecure_value = jsonencode(module.foo_vpc.elasticache_network_acl_arn)
  tags           = var.tags
}

resource "aws_ssm_parameter" "foo_elasticache_network_acl_id" {
  name           = "/${var.env}/${var.component}/foo_elasticache_network_acl_id"
  type           = "String"
  tier           = "Standard"
  insecure_value = jsonencode(module.foo_vpc.elasticache_network_acl_id)
  tags           = var.tags
}

resource "aws_ssm_parameter" "foo_elasticache_route_table_association_ids" {
  name           = "/${var.env}/${var.component}/foo_elasticache_route_table_association_ids"
  type           = "String"
  tier           = "Standard"
  insecure_value = jsonencode(module.foo_vpc.elasticache_route_table_association_ids)
  tags           = var.tags
}

resource "aws_ssm_parameter" "foo_elasticache_route_table_ids" {
  name           = "/${var.env}/${var.component}/foo_elasticache_route_table_ids"
  type           = "String"
  tier           = "Standard"
  insecure_value = jsonencode(module.foo_vpc.elasticache_route_table_ids)
  tags           = var.tags
}

resource "aws_ssm_parameter" "foo_elasticache_subnet_arns" {
  name           = "/${var.env}/${var.component}/foo_elasticache_subnet_arns"
  type           = "String"
  tier           = "Standard"
  insecure_value = jsonencode(module.foo_vpc.elasticache_subnet_arns)
  tags           = var.tags
}

resource "aws_ssm_parameter" "foo_elasticache_subnet_group" {
  name           = "/${var.env}/${var.component}/foo_elasticache_subnet_group"
  type           = "String"
  tier           = "Standard"
  insecure_value = jsonencode(module.foo_vpc.elasticache_subnet_group)
  tags           = var.tags
}

resource "aws_ssm_parameter" "foo_elasticache_subnet_group_name" {
  name           = "/${var.env}/${var.component}/foo_elasticache_subnet_group_name"
  type           = "String"
  tier           = "Standard"
  insecure_value = jsonencode(module.foo_vpc.elasticache_subnet_group_name)
  tags           = var.tags
}

resource "aws_ssm_parameter" "foo_elasticache_subnets" {
  name           = "/${var.env}/${var.component}/foo_elasticache_subnets"
  type           = "String"
  tier           = "Standard"
  insecure_value = jsonencode(module.foo_vpc.elasticache_subnets)
  tags           = var.tags
}

resource "aws_ssm_parameter" "foo_elasticache_subnets_cidr_blocks" {
  name           = "/${var.env}/${var.component}/foo_elasticache_subnets_cidr_blocks"
  type           = "String"
  tier           = "Standard"
  insecure_value = jsonencode(module.foo_vpc.elasticache_subnets_cidr_blocks)
  tags           = var.tags
}

resource "aws_ssm_parameter" "foo_elasticache_subnets_ipv6_cidr_blocks" {
  name           = "/${var.env}/${var.component}/foo_elasticache_subnets_ipv6_cidr_blocks"
  type           = "String"
  tier           = "Standard"
  insecure_value = jsonencode(module.foo_vpc.elasticache_subnets_ipv6_cidr_blocks)
  tags           = var.tags
}

resource "aws_ssm_parameter" "foo_igw_arn" {
  name           = "/${var.env}/${var.component}/foo_igw_arn"
  type           = "String"
  tier           = "Standard"
  insecure_value = jsonencode(module.foo_vpc.igw_arn)
  tags           = var.tags
}

resource "aws_ssm_parameter" "foo_igw_id" {
  name           = "/${var.env}/${var.component}/foo_igw_id"
  type           = "String"
  tier           = "Standard"
  insecure_value = jsonencode(module.foo_vpc.igw_id)
  tags           = var.tags
}

resource "aws_ssm_parameter" "foo_intra_network_acl_arn" {
  name           = "/${var.env}/${var.component}/foo_intra_network_acl_arn"
  type           = "String"
  tier           = "Standard"
  insecure_value = jsonencode(module.foo_vpc.intra_network_acl_arn)
  tags           = var.tags
}

resource "aws_ssm_parameter" "foo_intra_network_acl_id" {
  name           = "/${var.env}/${var.component}/foo_intra_network_acl_id"
  type           = "String"
  tier           = "Standard"
  insecure_value = jsonencode(module.foo_vpc.intra_network_acl_id)
  tags           = var.tags
}

resource "aws_ssm_parameter" "foo_intra_route_table_association_ids" {
  name           = "/${var.env}/${var.component}/foo_intra_route_table_association_ids"
  type           = "String"
  tier           = "Standard"
  insecure_value = jsonencode(module.foo_vpc.intra_route_table_association_ids)
  tags           = var.tags
}

resource "aws_ssm_parameter" "foo_intra_route_table_ids" {
  name           = "/${var.env}/${var.component}/foo_intra_route_table_ids"
  type           = "String"
  tier           = "Standard"
  insecure_value = jsonencode(module.foo_vpc.intra_route_table_ids)
  tags           = var.tags
}

resource "aws_ssm_parameter" "foo_intra_subnet_arns" {
  name           = "/${var.env}/${var.component}/foo_intra_subnet_arns"
  type           = "String"
  tier           = "Standard"
  insecure_value = jsonencode(module.foo_vpc.intra_subnet_arns)
  tags           = var.tags
}

resource "aws_ssm_parameter" "foo_intra_subnets" {
  name           = "/${var.env}/${var.component}/foo_intra_subnets"
  type           = "String"
  tier           = "Standard"
  insecure_value = jsonencode(module.foo_vpc.intra_subnets)
  tags           = var.tags
}

resource "aws_ssm_parameter" "foo_intra_subnets_cidr_blocks" {
  name           = "/${var.env}/${var.component}/foo_intra_subnets_cidr_blocks"
  type           = "String"
  tier           = "Standard"
  insecure_value = jsonencode(module.foo_vpc.intra_subnets_cidr_blocks)
  tags           = var.tags
}

resource "aws_ssm_parameter" "foo_intra_subnets_ipv6_cidr_blocks" {
  name           = "/${var.env}/${var.component}/foo_intra_subnets_ipv6_cidr_blocks"
  type           = "String"
  tier           = "Standard"
  insecure_value = jsonencode(module.foo_vpc.intra_subnets_ipv6_cidr_blocks)
  tags           = var.tags
}

resource "aws_ssm_parameter" "foo_name" {
  name           = "/${var.env}/${var.component}/foo_name"
  type           = "String"
  tier           = "Standard"
  insecure_value = jsonencode(module.foo_vpc.name)
  tags           = var.tags
}

resource "aws_ssm_parameter" "foo_nat_ids" {
  name           = "/${var.env}/${var.component}/foo_nat_ids"
  type           = "String"
  tier           = "Standard"
  insecure_value = jsonencode(module.foo_vpc.nat_ids)
  tags           = var.tags
}

resource "aws_ssm_parameter" "foo_nat_public_ips" {
  name           = "/${var.env}/${var.component}/foo_nat_public_ips"
  type           = "String"
  tier           = "Standard"
  insecure_value = jsonencode(module.foo_vpc.nat_public_ips)
  tags           = var.tags
}

resource "aws_ssm_parameter" "foo_natgw_ids" {
  name           = "/${var.env}/${var.component}/foo_natgw_ids"
  type           = "String"
  tier           = "Standard"
  insecure_value = jsonencode(module.foo_vpc.natgw_ids)
  tags           = var.tags
}

resource "aws_ssm_parameter" "foo_outpost_network_acl_arn" {
  name           = "/${var.env}/${var.component}/foo_outpost_network_acl_arn"
  type           = "String"
  tier           = "Standard"
  insecure_value = jsonencode(module.foo_vpc.outpost_network_acl_arn)
  tags           = var.tags
}

resource "aws_ssm_parameter" "foo_outpost_network_acl_id" {
  name           = "/${var.env}/${var.component}/foo_outpost_network_acl_id"
  type           = "String"
  tier           = "Standard"
  insecure_value = jsonencode(module.foo_vpc.outpost_network_acl_id)
  tags           = var.tags
}

resource "aws_ssm_parameter" "foo_outpost_subnet_arns" {
  name           = "/${var.env}/${var.component}/foo_outpost_subnet_arns"
  type           = "String"
  tier           = "Standard"
  insecure_value = jsonencode(module.foo_vpc.outpost_subnet_arns)
  tags           = var.tags
}

resource "aws_ssm_parameter" "foo_outpost_subnets" {
  name           = "/${var.env}/${var.component}/foo_outpost_subnets"
  type           = "String"
  tier           = "Standard"
  insecure_value = jsonencode(module.foo_vpc.outpost_subnets)
  tags           = var.tags
}

resource "aws_ssm_parameter" "foo_outpost_subnets_cidr_blocks" {
  name           = "/${var.env}/${var.component}/foo_outpost_subnets_cidr_blocks"
  type           = "String"
  tier           = "Standard"
  insecure_value = jsonencode(module.foo_vpc.outpost_subnets_cidr_blocks)
  tags           = var.tags
}

resource "aws_ssm_parameter" "foo_outpost_subnets_ipv6_cidr_blocks" {
  name           = "/${var.env}/${var.component}/foo_outpost_subnets_ipv6_cidr_blocks"
  type           = "String"
  tier           = "Standard"
  insecure_value = jsonencode(module.foo_vpc.outpost_subnets_ipv6_cidr_blocks)
  tags           = var.tags
}

resource "aws_ssm_parameter" "foo_private_ipv6_egress_route_ids" {
  name           = "/${var.env}/${var.component}/foo_private_ipv6_egress_route_ids"
  type           = "String"
  tier           = "Standard"
  insecure_value = jsonencode(module.foo_vpc.private_ipv6_egress_route_ids)
  tags           = var.tags
}

resource "aws_ssm_parameter" "foo_private_nat_gateway_route_ids" {
  name           = "/${var.env}/${var.component}/foo_private_nat_gateway_route_ids"
  type           = "String"
  tier           = "Standard"
  insecure_value = jsonencode(module.foo_vpc.private_nat_gateway_route_ids)
  tags           = var.tags
}

resource "aws_ssm_parameter" "foo_private_network_acl_arn" {
  name           = "/${var.env}/${var.component}/foo_private_network_acl_arn"
  type           = "String"
  tier           = "Standard"
  insecure_value = jsonencode(module.foo_vpc.private_network_acl_arn)
  tags           = var.tags
}

resource "aws_ssm_parameter" "foo_private_network_acl_id" {
  name           = "/${var.env}/${var.component}/foo_private_network_acl_id"
  type           = "String"
  tier           = "Standard"
  insecure_value = jsonencode(module.foo_vpc.private_network_acl_id)
  tags           = var.tags
}

resource "aws_ssm_parameter" "foo_private_route_table_association_ids" {
  name           = "/${var.env}/${var.component}/foo_private_route_table_association_ids"
  type           = "String"
  tier           = "Standard"
  insecure_value = jsonencode(module.foo_vpc.private_route_table_association_ids)
  tags           = var.tags
}

resource "aws_ssm_parameter" "foo_private_route_table_ids" {
  name           = "/${var.env}/${var.component}/foo_private_route_table_ids"
  type           = "String"
  tier           = "Standard"
  insecure_value = jsonencode(module.foo_vpc.private_route_table_ids)
  tags           = var.tags
}

resource "aws_ssm_parameter" "foo_private_subnet_arns" {
  name           = "/${var.env}/${var.component}/foo_private_subnet_arns"
  type           = "String"
  tier           = "Standard"
  insecure_value = jsonencode(module.foo_vpc.private_subnet_arns)
  tags           = var.tags
}

resource "aws_ssm_parameter" "foo_private_subnets" {
  name           = "/${var.env}/${var.component}/foo_private_subnets"
  type           = "String"
  tier           = "Standard"
  insecure_value = jsonencode(module.foo_vpc.private_subnets)
  tags           = var.tags
}

resource "aws_ssm_parameter" "foo_private_subnets_cidr_blocks" {
  name           = "/${var.env}/${var.component}/foo_private_subnets_cidr_blocks"
  type           = "String"
  tier           = "Standard"
  insecure_value = jsonencode(module.foo_vpc.private_subnets_cidr_blocks)
  tags           = var.tags
}

resource "aws_ssm_parameter" "foo_private_subnets_ipv6_cidr_blocks" {
  name           = "/${var.env}/${var.component}/foo_private_subnets_ipv6_cidr_blocks"
  type           = "String"
  tier           = "Standard"
  insecure_value = jsonencode(module.foo_vpc.private_subnets_ipv6_cidr_blocks)
  tags           = var.tags
}

resource "aws_ssm_parameter" "foo_public_internet_gateway_ipv6_route_id" {
  name           = "/${var.env}/${var.component}/foo_public_internet_gateway_ipv6_route_id"
  type           = "String"
  tier           = "Standard"
  insecure_value = jsonencode(module.foo_vpc.public_internet_gateway_ipv6_route_id)
  tags           = var.tags
}

resource "aws_ssm_parameter" "foo_public_internet_gateway_route_id" {
  name           = "/${var.env}/${var.component}/foo_public_internet_gateway_route_id"
  type           = "String"
  tier           = "Standard"
  insecure_value = jsonencode(module.foo_vpc.public_internet_gateway_route_id)
  tags           = var.tags
}

resource "aws_ssm_parameter" "foo_public_network_acl_arn" {
  name           = "/${var.env}/${var.component}/foo_public_network_acl_arn"
  type           = "String"
  tier           = "Standard"
  insecure_value = jsonencode(module.foo_vpc.public_network_acl_arn)
  tags           = var.tags
}

resource "aws_ssm_parameter" "foo_public_network_acl_id" {
  name           = "/${var.env}/${var.component}/foo_public_network_acl_id"
  type           = "String"
  tier           = "Standard"
  insecure_value = jsonencode(module.foo_vpc.public_network_acl_id)
  tags           = var.tags
}

resource "aws_ssm_parameter" "foo_public_route_table_association_ids" {
  name           = "/${var.env}/${var.component}/foo_public_route_table_association_ids"
  type           = "String"
  tier           = "Standard"
  insecure_value = jsonencode(module.foo_vpc.public_route_table_association_ids)
  tags           = var.tags
}

resource "aws_ssm_parameter" "foo_public_route_table_ids" {
  name           = "/${var.env}/${var.component}/foo_public_route_table_ids"
  type           = "String"
  tier           = "Standard"
  insecure_value = jsonencode(module.foo_vpc.public_route_table_ids)
  tags           = var.tags
}

resource "aws_ssm_parameter" "foo_public_subnet_arns" {
  name           = "/${var.env}/${var.component}/foo_public_subnet_arns"
  type           = "String"
  tier           = "Standard"
  insecure_value = jsonencode(module.foo_vpc.public_subnet_arns)
  tags           = var.tags
}

resource "aws_ssm_parameter" "foo_public_subnets" {
  name           = "/${var.env}/${var.component}/foo_public_subnets"
  type           = "String"
  tier           = "Standard"
  insecure_value = jsonencode(module.foo_vpc.public_subnets)
  tags           = var.tags
}

resource "aws_ssm_parameter" "foo_public_subnets_cidr_blocks" {
  name           = "/${var.env}/${var.component}/foo_public_subnets_cidr_blocks"
  type           = "String"
  tier           = "Standard"
  insecure_value = jsonencode(module.foo_vpc.public_subnets_cidr_blocks)
  tags           = var.tags
}

resource "aws_ssm_parameter" "foo_public_subnets_ipv6_cidr_blocks" {
  name           = "/${var.env}/${var.component}/foo_public_subnets_ipv6_cidr_blocks"
  type           = "String"
  tier           = "Standard"
  insecure_value = jsonencode(module.foo_vpc.public_subnets_ipv6_cidr_blocks)
  tags           = var.tags
}

resource "aws_ssm_parameter" "foo_redshift_network_acl_arn" {
  name           = "/${var.env}/${var.component}/foo_redshift_network_acl_arn"
  type           = "String"
  tier           = "Standard"
  insecure_value = jsonencode(module.foo_vpc.redshift_network_acl_arn)
  tags           = var.tags
}

resource "aws_ssm_parameter" "foo_redshift_network_acl_id" {
  name           = "/${var.env}/${var.component}/foo_redshift_network_acl_id"
  type           = "String"
  tier           = "Standard"
  insecure_value = jsonencode(module.foo_vpc.redshift_network_acl_id)
  tags           = var.tags
}

resource "aws_ssm_parameter" "foo_redshift_public_route_table_association_ids" {
  name           = "/${var.env}/${var.component}/foo_redshift_public_route_table_association_ids"
  type           = "String"
  tier           = "Standard"
  insecure_value = jsonencode(module.foo_vpc.redshift_public_route_table_association_ids)
  tags           = var.tags
}

resource "aws_ssm_parameter" "foo_redshift_route_table_association_ids" {
  name           = "/${var.env}/${var.component}/foo_redshift_route_table_association_ids"
  type           = "String"
  tier           = "Standard"
  insecure_value = jsonencode(module.foo_vpc.redshift_route_table_association_ids)
  tags           = var.tags
}

resource "aws_ssm_parameter" "foo_redshift_route_table_ids" {
  name           = "/${var.env}/${var.component}/foo_redshift_route_table_ids"
  type           = "String"
  tier           = "Standard"
  insecure_value = jsonencode(module.foo_vpc.redshift_route_table_ids)
  tags           = var.tags
}

resource "aws_ssm_parameter" "foo_redshift_subnet_arns" {
  name           = "/${var.env}/${var.component}/foo_redshift_subnet_arns"
  type           = "String"
  tier           = "Standard"
  insecure_value = jsonencode(module.foo_vpc.redshift_subnet_arns)
  tags           = var.tags
}

resource "aws_ssm_parameter" "foo_redshift_subnet_group" {
  name           = "/${var.env}/${var.component}/foo_redshift_subnet_group"
  type           = "String"
  tier           = "Standard"
  insecure_value = jsonencode(module.foo_vpc.redshift_subnet_group)
  tags           = var.tags
}

resource "aws_ssm_parameter" "foo_redshift_subnets" {
  name           = "/${var.env}/${var.component}/foo_redshift_subnets"
  type           = "String"
  tier           = "Standard"
  insecure_value = jsonencode(module.foo_vpc.redshift_subnets)
  tags           = var.tags
}

resource "aws_ssm_parameter" "foo_redshift_subnets_cidr_blocks" {
  name           = "/${var.env}/${var.component}/foo_redshift_subnets_cidr_blocks"
  type           = "String"
  tier           = "Standard"
  insecure_value = jsonencode(module.foo_vpc.redshift_subnets_cidr_blocks)
  tags           = var.tags
}

resource "aws_ssm_parameter" "foo_redshift_subnets_ipv6_cidr_blocks" {
  name           = "/${var.env}/${var.component}/foo_redshift_subnets_ipv6_cidr_blocks"
  type           = "String"
  tier           = "Standard"
  insecure_value = jsonencode(module.foo_vpc.redshift_subnets_ipv6_cidr_blocks)
  tags           = var.tags
}

resource "aws_ssm_parameter" "foo_this_customer_gateway" {
  name           = "/${var.env}/${var.component}/foo_this_customer_gateway"
  type           = "String"
  tier           = "Standard"
  insecure_value = jsonencode(module.foo_vpc.this_customer_gateway)
  tags           = var.tags
}

resource "aws_ssm_parameter" "foo_vgw_arn" {
  name           = "/${var.env}/${var.component}/foo_vgw_arn"
  type           = "String"
  tier           = "Standard"
  insecure_value = jsonencode(module.foo_vpc.vgw_arn)
  tags           = var.tags
}

resource "aws_ssm_parameter" "foo_vgw_id" {
  name           = "/${var.env}/${var.component}/foo_vgw_id"
  type           = "String"
  tier           = "Standard"
  insecure_value = jsonencode(module.foo_vpc.vgw_id)
  tags           = var.tags
}

resource "aws_ssm_parameter" "foo_vpc_arn" {
  name           = "/${var.env}/${var.component}/foo_vpc_arn"
  type           = "String"
  tier           = "Standard"
  insecure_value = jsonencode(module.foo_vpc.vpc_arn)
  tags           = var.tags
}

resource "aws_ssm_parameter" "foo_vpc_cidr_block" {
  name           = "/${var.env}/${var.component}/foo_vpc_cidr_block"
  type           = "String"
  tier           = "Standard"
  insecure_value = jsonencode(module.foo_vpc.vpc_cidr_block)
  tags           = var.tags
}

resource "aws_ssm_parameter" "foo_vpc_enable_dns_hostnames" {
  name           = "/${var.env}/${var.component}/foo_vpc_enable_dns_hostnames"
  type           = "String"
  tier           = "Standard"
  insecure_value = jsonencode(module.foo_vpc.vpc_enable_dns_hostnames)
  tags           = var.tags
}

resource "aws_ssm_parameter" "foo_vpc_enable_dns_support" {
  name           = "/${var.env}/${var.component}/foo_vpc_enable_dns_support"
  type           = "String"
  tier           = "Standard"
  insecure_value = jsonencode(module.foo_vpc.vpc_enable_dns_support)
  tags           = var.tags
}

resource "aws_ssm_parameter" "foo_vpc_flow_log_cloudwatch_iam_role_arn" {
  name           = "/${var.env}/${var.component}/foo_vpc_flow_log_cloudwatch_iam_role_arn"
  type           = "String"
  tier           = "Standard"
  insecure_value = jsonencode(module.foo_vpc.vpc_flow_log_cloudwatch_iam_role_arn)
  tags           = var.tags
}

resource "aws_ssm_parameter" "foo_vpc_flow_log_destination_arn" {
  name           = "/${var.env}/${var.component}/foo_vpc_flow_log_destination_arn"
  type           = "String"
  tier           = "Standard"
  insecure_value = jsonencode(module.foo_vpc.vpc_flow_log_destination_arn)
  tags           = var.tags
}

resource "aws_ssm_parameter" "foo_vpc_flow_log_destination_type" {
  name           = "/${var.env}/${var.component}/foo_vpc_flow_log_destination_type"
  type           = "String"
  tier           = "Standard"
  insecure_value = jsonencode(module.foo_vpc.vpc_flow_log_destination_type)
  tags           = var.tags
}

resource "aws_ssm_parameter" "foo_vpc_flow_log_id" {
  name           = "/${var.env}/${var.component}/foo_vpc_flow_log_id"
  type           = "String"
  tier           = "Standard"
  insecure_value = jsonencode(module.foo_vpc.vpc_flow_log_id)
  tags           = var.tags
}

resource "aws_ssm_parameter" "foo_vpc_id" {
  name           = "/${var.env}/${var.component}/foo_vpc_id"
  type           = "String"
  tier           = "Standard"
  insecure_value = jsonencode(module.foo_vpc.vpc_id)
  tags           = var.tags
}

resource "aws_ssm_parameter" "foo_vpc_instance_tenancy" {
  name           = "/${var.env}/${var.component}/foo_vpc_instance_tenancy"
  type           = "String"
  tier           = "Standard"
  insecure_value = jsonencode(module.foo_vpc.vpc_instance_tenancy)
  tags           = var.tags
}

resource "aws_ssm_parameter" "foo_vpc_ipv6_association_id" {
  name           = "/${var.env}/${var.component}/foo_vpc_ipv6_association_id"
  type           = "String"
  tier           = "Standard"
  insecure_value = jsonencode(module.foo_vpc.vpc_ipv6_association_id)
  tags           = var.tags
}

resource "aws_ssm_parameter" "foo_vpc_ipv6_cidr_block" {
  name           = "/${var.env}/${var.component}/foo_vpc_ipv6_cidr_block"
  type           = "String"
  tier           = "Standard"
  insecure_value = jsonencode(module.foo_vpc.vpc_ipv6_cidr_block)
  tags           = var.tags
}

resource "aws_ssm_parameter" "foo_vpc_main_route_table_id" {
  name           = "/${var.env}/${var.component}/foo_vpc_main_route_table_id"
  type           = "String"
  tier           = "Standard"
  insecure_value = jsonencode(module.foo_vpc.vpc_main_route_table_id)
  tags           = var.tags
}

resource "aws_ssm_parameter" "foo_vpc_owner_id" {
  name           = "/${var.env}/${var.component}/foo_vpc_owner_id"
  type           = "String"
  tier           = "Standard"
  insecure_value = jsonencode(module.foo_vpc.vpc_owner_id)
  tags           = var.tags
}

resource "aws_ssm_parameter" "foo_vpc_secondary_cidr_blocks" {
  name           = "/${var.env}/${var.component}/foo_vpc_secondary_cidr_blocks"
  type           = "String"
  tier           = "Standard"
  insecure_value = jsonencode(module.foo_vpc.vpc_secondary_cidr_blocks)
  tags           = var.tags
}

// module "bar_vpc" ssm Parameter Store integration registry entries (non sensitive)
resource "aws_ssm_parameter" "bar_azs" {
  name           = "/${var.env}/${var.component}/bar_azs"
  type           = "String"
  tier           = "Standard"
  insecure_value = jsonencode(module.bar_vpc.azs)
  tags           = var.tags
}

resource "aws_ssm_parameter" "bar_cgw_arns" {
  name           = "/${var.env}/${var.component}/customer_gateways"
  type           = "String"
  tier           = "Standard"
  insecure_value = jsonencode(module.bar_vpc.cgw_arns)
  tags           = var.tags
}

resource "aws_ssm_parameter" "bar_cgw_ids" {
  name           = "/${var.env}/${var.component}/bar_cgw_ids"
  type           = "String"
  tier           = "Standard"
  insecure_value = jsonencode(module.bar_vpc.cgw_ids)
  tags           = var.tags
}

resource "aws_ssm_parameter" "bar_database_internet_gateway_route_id" {
  name           = "/${var.env}/${var.component}/bar_database_internet_gateway_route_id"
  type           = "String"
  tier           = "Standard"
  insecure_value = jsonencode(module.bar_vpc.database_internet_gateway_route_id)
  tags           = var.tags
}

resource "aws_ssm_parameter" "bar_database_ipv6_egress_route_id" {
  name           = "/${var.env}/${var.component}/bar_database_ipv6_egress_route_id"
  type           = "String"
  tier           = "Standard"
  insecure_value = jsonencode(module.bar_vpc.database_ipv6_egress_route_id)
  tags           = var.tags
}

resource "aws_ssm_parameter" "bar_database_nat_gateway_route_ids" {
  name           = "/${var.env}/${var.component}/bar_database_nat_gateway_route_ids"
  type           = "String"
  tier           = "Standard"
  insecure_value = jsonencode(module.bar_vpc.database_nat_gateway_route_ids)
  tags           = var.tags
}

resource "aws_ssm_parameter" "bar_database_network_acl_arn" {
  name           = "/${var.env}/${var.component}/bar_database_network_acl_arn"
  type           = "String"
  tier           = "Standard"
  insecure_value = jsonencode(module.bar_vpc.database_network_acl_arn)
  tags           = var.tags
}

resource "aws_ssm_parameter" "bar_database_network_acl_id" {
  name           = "/${var.env}/${var.component}/bar_database_network_acl_id"
  type           = "String"
  tier           = "Standard"
  insecure_value = jsonencode(module.bar_vpc.database_network_acl_id)
  tags           = var.tags
}

resource "aws_ssm_parameter" "bar_database_route_table_association_ids" {
  name           = "/${var.env}/${var.component}/bar_database_route_table_association_ids"
  type           = "String"
  tier           = "Standard"
  insecure_value = jsonencode(module.bar_vpc.database_route_table_association_ids)
  tags           = var.tags
}

resource "aws_ssm_parameter" "bar_database_route_table_ids" {
  name           = "/${var.env}/${var.component}/bar_database_route_table_ids"
  type           = "String"
  tier           = "Standard"
  insecure_value = jsonencode(module.bar_vpc.database_route_table_ids)
  tags           = var.tags
}

resource "aws_ssm_parameter" "bar_database_subnet_arns" {
  name           = "/${var.env}/${var.component}/bar_database_subnet_arns"
  type           = "String"
  tier           = "Standard"
  insecure_value = jsonencode(module.bar_vpc.database_subnet_arns)
  tags           = var.tags
}

resource "aws_ssm_parameter" "bar_database_subnet_group" {
  name           = "/${var.env}/${var.component}/bar_database_subnet_group"
  type           = "String"
  tier           = "Standard"
  insecure_value = jsonencode(module.bar_vpc.database_subnet_group)
  tags           = var.tags
}

resource "aws_ssm_parameter" "bar_database_subnet_group_name" {
  name           = "/${var.env}/${var.component}/bar_database_subnet_group_name"
  type           = "String"
  tier           = "Standard"
  insecure_value = jsonencode(module.bar_vpc.database_subnet_group_name)
  tags           = var.tags
}

resource "aws_ssm_parameter" "bar_database_subnets" {
  name           = "/${var.env}/${var.component}/bar_database_subnets"
  type           = "String"
  tier           = "Standard"
  insecure_value = jsonencode(module.bar_vpc.database_subnets)
  tags           = var.tags
}

resource "aws_ssm_parameter" "bar_database_subnets_cidr_blocks" {
  name           = "/${var.env}/${var.component}/bar_database_subnets_cidr_blocks"
  type           = "String"
  tier           = "Standard"
  insecure_value = jsonencode(module.bar_vpc.database_subnets_cidr_blocks)
  tags           = var.tags
}

resource "aws_ssm_parameter" "bar_database_subnets_ipv6_cidr_blocks" {
  name           = "/${var.env}/${var.component}/bar_database_subnets_ipv6_cidr_blocks"
  type           = "String"
  tier           = "Standard"
  insecure_value = jsonencode(module.bar_vpc.database_subnets_ipv6_cidr_blocks)
  tags           = var.tags
}

resource "aws_ssm_parameter" "bar_default_network_acl_id" {
  name           = "/${var.env}/${var.component}/bar_default_network_acl_id"
  type           = "String"
  tier           = "Standard"
  insecure_value = jsonencode(module.bar_vpc.default_network_acl_id)
  tags           = var.tags
}

resource "aws_ssm_parameter" "bar_default_route_table_id" {
  name           = "/${var.env}/${var.component}/bar_default_route_table_id"
  type           = "String"
  tier           = "Standard"
  insecure_value = jsonencode(module.bar_vpc.default_route_table_id)
  tags           = var.tags
}

resource "aws_ssm_parameter" "bar_default_security_group_id" {
  name           = "/${var.env}/${var.component}/bar_default_security_group_id"
  type           = "String"
  tier           = "Standard"
  insecure_value = jsonencode(module.bar_vpc.default_security_group_id)
  tags           = var.tags
}

resource "aws_ssm_parameter" "bar_default_vpc_arn" {
  name           = "/${var.env}/${var.component}/bar_default_vpc_arn"
  type           = "String"
  tier           = "Standard"
  insecure_value = jsonencode(module.bar_vpc.default_vpc_arn)
  tags           = var.tags
}

resource "aws_ssm_parameter" "bar_default_vpc_cidr_block" {
  name           = "/${var.env}/${var.component}/bar_default_vpc_cidr_block"
  type           = "String"
  tier           = "Standard"
  insecure_value = jsonencode(module.bar_vpc.default_vpc_cidr_block)
  tags           = var.tags
}

resource "aws_ssm_parameter" "bar_default_vpc_default_network_acl_id" {
  name           = "/${var.env}/${var.component}/bar_default_vpc_default_network_acl_id"
  type           = "String"
  tier           = "Standard"
  insecure_value = jsonencode(module.bar_vpc.default_vpc_default_network_acl_id)
  tags           = var.tags
}

resource "aws_ssm_parameter" "bar_default_vpc_default_route_table_id" {
  name           = "/${var.env}/${var.component}/bar_default_vpc_default_route_table_id"
  type           = "String"
  tier           = "Standard"
  insecure_value = jsonencode(module.bar_vpc.default_vpc_default_route_table_id)
  tags           = var.tags
}

resource "aws_ssm_parameter" "bar_default_vpc_default_security_group_id" {
  name           = "/${var.env}/${var.component}/bar_default_vpc_default_security_group_id"
  type           = "String"
  tier           = "Standard"
  insecure_value = jsonencode(module.bar_vpc.default_vpc_default_security_group_id)
  tags           = var.tags
}

resource "aws_ssm_parameter" "bar_default_vpc_enable_dns_hostnames" {
  name           = "/${var.env}/${var.component}/bar_default_vpc_enable_dns_hostnames"
  type           = "String"
  tier           = "Standard"
  insecure_value = jsonencode(module.bar_vpc.default_vpc_enable_dns_hostnames)
  tags           = var.tags
}

resource "aws_ssm_parameter" "bar_default_vpc_enable_dns_support" {
  name           = "/${var.env}/${var.component}/bar_default_vpc_enable_dns_support"
  type           = "String"
  tier           = "Standard"
  insecure_value = jsonencode(module.bar_vpc.default_vpc_enable_dns_support)
  tags           = var.tags
}

resource "aws_ssm_parameter" "bar_default_vpc_id" {
  name           = "/${var.env}/${var.component}/bar_default_vpc_id"
  type           = "String"
  tier           = "Standard"
  insecure_value = jsonencode(module.bar_vpc.default_vpc_id)
  tags           = var.tags
}

resource "aws_ssm_parameter" "bar_default_vpc_instance_tenancy" {
  name           = "/${var.env}/${var.component}/bar_default_vpc_instance_tenancy"
  type           = "String"
  tier           = "Standard"
  insecure_value = jsonencode(module.bar_vpc.default_vpc_instance_tenancy)
  tags           = var.tags
}

resource "aws_ssm_parameter" "bar_default_vpc_main_route_table_id" {
  name           = "/${var.env}/${var.component}/bar_default_vpc_main_route_table_id"
  type           = "String"
  tier           = "Standard"
  insecure_value = jsonencode(module.bar_vpc.default_vpc_main_route_table_id)
  tags           = var.tags
}

resource "aws_ssm_parameter" "bar_dhcp_options_id" {
  name           = "/${var.env}/${var.component}/bar_dhcp_options_id"
  type           = "String"
  tier           = "Standard"
  insecure_value = jsonencode(module.bar_vpc.dhcp_options_id)
  tags           = var.tags
}

resource "aws_ssm_parameter" "bar_egress_only_internet_gateway_id" {
  name           = "/${var.env}/${var.component}/bar_egress_only_internet_gateway_id"
  type           = "String"
  tier           = "Standard"
  insecure_value = jsonencode(module.bar_vpc.egress_only_internet_gateway_id)
  tags           = var.tags
}

resource "aws_ssm_parameter" "bar_elasticache_network_acl_arn" {
  name           = "/${var.env}/${var.component}/bar_elasticache_network_acl_arn"
  type           = "String"
  tier           = "Standard"
  insecure_value = jsonencode(module.bar_vpc.elasticache_network_acl_arn)
  tags           = var.tags
}

resource "aws_ssm_parameter" "bar_elasticache_network_acl_id" {
  name           = "/${var.env}/${var.component}/bar_elasticache_network_acl_id"
  type           = "String"
  tier           = "Standard"
  insecure_value = jsonencode(module.bar_vpc.elasticache_network_acl_id)
  tags           = var.tags
}

resource "aws_ssm_parameter" "bar_elasticache_route_table_association_ids" {
  name           = "/${var.env}/${var.component}/bar_elasticache_route_table_association_ids"
  type           = "String"
  tier           = "Standard"
  insecure_value = jsonencode(module.bar_vpc.elasticache_route_table_association_ids)
  tags           = var.tags
}

resource "aws_ssm_parameter" "bar_elasticache_route_table_ids" {
  name           = "/${var.env}/${var.component}/bar_elasticache_route_table_ids"
  type           = "String"
  tier           = "Standard"
  insecure_value = jsonencode(module.bar_vpc.elasticache_route_table_ids)
  tags           = var.tags
}

resource "aws_ssm_parameter" "bar_elasticache_subnet_arns" {
  name           = "/${var.env}/${var.component}/bar_elasticache_subnet_arns"
  type           = "String"
  tier           = "Standard"
  insecure_value = jsonencode(module.bar_vpc.elasticache_subnet_arns)
  tags           = var.tags
}

resource "aws_ssm_parameter" "bar_elasticache_subnet_group" {
  name           = "/${var.env}/${var.component}/bar_elasticache_subnet_group"
  type           = "String"
  tier           = "Standard"
  insecure_value = jsonencode(module.bar_vpc.elasticache_subnet_group)
  tags           = var.tags
}

resource "aws_ssm_parameter" "bar_elasticache_subnet_group_name" {
  name           = "/${var.env}/${var.component}/bar_elasticache_subnet_group_name"
  type           = "String"
  tier           = "Standard"
  insecure_value = jsonencode(module.bar_vpc.elasticache_subnet_group_name)
  tags           = var.tags
}

resource "aws_ssm_parameter" "bar_elasticache_subnets" {
  name           = "/${var.env}/${var.component}/bar_elasticache_subnets"
  type           = "String"
  tier           = "Standard"
  insecure_value = yamlencode(module.bar_vpc.elasticache_subnets)
  tags           = var.tags
}

resource "aws_ssm_parameter" "bar_elasticache_subnets_cidr_blocks" {
  name           = "/${var.env}/${var.component}/bar_elasticache_subnets_cidr_blocks"
  type           = "String"
  tier           = "Standard"
  insecure_value = jsonencode(module.bar_vpc.elasticache_subnets_cidr_blocks)
  tags           = var.tags
}

resource "aws_ssm_parameter" "bar_elasticache_subnets_ipv6_cidr_blocks" {
  name           = "/${var.env}/${var.component}/bar_elasticache_subnets_ipv6_cidr_blocks"
  type           = "String"
  tier           = "Standard"
  insecure_value = jsonencode(module.bar_vpc.elasticache_subnets_ipv6_cidr_blocks)
  tags           = var.tags
}

resource "aws_ssm_parameter" "bar_igw_arn" {
  name           = "/${var.env}/${var.component}/bar_igw_arn"
  type           = "String"
  tier           = "Standard"
  insecure_value = jsonencode(module.bar_vpc.igw_arn)
  tags           = var.tags
}

resource "aws_ssm_parameter" "bar_igw_id" {
  name           = "/${var.env}/${var.component}/bar_igw_id"
  type           = "String"
  tier           = "Standard"
  insecure_value = jsonencode(module.bar_vpc.igw_id)
  tags           = var.tags
}

resource "aws_ssm_parameter" "bar_intra_network_acl_arn" {
  name           = "/${var.env}/${var.component}/bar_intra_network_acl_arn"
  type           = "String"
  tier           = "Standard"
  insecure_value = jsonencode(module.bar_vpc.intra_network_acl_arn)
  tags           = var.tags
}

resource "aws_ssm_parameter" "bar_intra_network_acl_id" {
  name           = "/${var.env}/${var.component}/bar_intra_network_acl_id"
  type           = "String"
  tier           = "Standard"
  insecure_value = jsonencode(module.bar_vpc.intra_network_acl_id)
  tags           = var.tags
}

resource "aws_ssm_parameter" "bar_intra_route_table_association_ids" {
  name           = "/${var.env}/${var.component}/bar_intra_route_table_association_ids"
  type           = "String"
  tier           = "Standard"
  insecure_value = jsonencode(module.bar_vpc.intra_route_table_association_ids)
  tags           = var.tags
}

resource "aws_ssm_parameter" "bar_intra_route_table_ids" {
  name           = "/${var.env}/${var.component}/bar_intra_route_table_ids"
  type           = "String"
  tier           = "Standard"
  insecure_value = jsonencode(module.bar_vpc.intra_route_table_ids)
  tags           = var.tags
}

resource "aws_ssm_parameter" "bar_intra_subnet_arns" {
  name           = "/${var.env}/${var.component}/bar_intra_subnet_arns"
  type           = "String"
  tier           = "Standard"
  insecure_value = jsonencode(module.bar_vpc.intra_subnet_arns)
  tags           = var.tags
}

resource "aws_ssm_parameter" "bar_intra_subnets" {
  name           = "/${var.env}/${var.component}/bar_intra_subnets"
  type           = "String"
  tier           = "Standard"
  insecure_value = jsonencode(module.bar_vpc.intra_subnets)
  tags           = var.tags
}

resource "aws_ssm_parameter" "bar_intra_subnets_cidr_blocks" {
  name           = "/${var.env}/${var.component}/bar_intra_subnets_cidr_blocks"
  type           = "String"
  tier           = "Standard"
  insecure_value = jsonencode(module.bar_vpc.intra_subnets_cidr_blocks)
  tags           = var.tags
}

resource "aws_ssm_parameter" "bar_intra_subnets_ipv6_cidr_blocks" {
  name           = "/${var.env}/${var.component}/bar_intra_subnets_ipv6_cidr_blocks"
  type           = "String"
  tier           = "Standard"
  insecure_value = jsonencode(module.bar_vpc.intra_subnets_ipv6_cidr_blocks)
  tags           = var.tags
}

resource "aws_ssm_parameter" "bar_name" {
  name           = "/${var.env}/${var.component}/bar_name"
  type           = "String"
  tier           = "Standard"
  insecure_value = jsonencode(module.bar_vpc.name)
  tags           = var.tags
}

resource "aws_ssm_parameter" "bar_nat_ids" {
  name           = "/${var.env}/${var.component}/bar_nat_ids"
  type           = "String"
  tier           = "Standard"
  insecure_value = jsonencode(module.bar_vpc.nat_ids)
  tags           = var.tags
}

resource "aws_ssm_parameter" "bar_nat_public_ips" {
  name           = "/${var.env}/${var.component}/bar_nat_public_ips"
  type           = "String"
  tier           = "Standard"
  insecure_value = jsonencode(module.bar_vpc.nat_public_ips)
  tags           = var.tags
}

resource "aws_ssm_parameter" "bar_natgw_ids" {
  name           = "/${var.env}/${var.component}/bar_natgw_ids"
  type           = "String"
  tier           = "Standard"
  insecure_value = jsonencode(module.bar_vpc.natgw_ids)
  tags           = var.tags
}

resource "aws_ssm_parameter" "bar_outpost_network_acl_arn" {
  name           = "/${var.env}/${var.component}/bar_outpost_network_acl_arn"
  type           = "String"
  tier           = "Standard"
  insecure_value = jsonencode(module.bar_vpc.outpost_network_acl_arn)
  tags           = var.tags
}

resource "aws_ssm_parameter" "bar_outpost_network_acl_id" {
  name           = "/${var.env}/${var.component}/bar_outpost_network_acl_id"
  type           = "String"
  tier           = "Standard"
  insecure_value = jsonencode(module.bar_vpc.outpost_network_acl_id)
  tags           = var.tags
}

resource "aws_ssm_parameter" "bar_outpost_subnet_arns" {
  name           = "/${var.env}/${var.component}/bar_outpost_subnet_arns"
  type           = "String"
  tier           = "Standard"
  insecure_value = jsonencode(module.bar_vpc.outpost_subnet_arns)
  tags           = var.tags
}

resource "aws_ssm_parameter" "bar_outpost_subnets" {
  name           = "/${var.env}/${var.component}/bar_outpost_subnets"
  type           = "String"
  tier           = "Standard"
  insecure_value = jsonencode(module.bar_vpc.outpost_subnets)
  tags           = var.tags
}

resource "aws_ssm_parameter" "bar_outpost_subnets_cidr_blocks" {
  name           = "/${var.env}/${var.component}/bar_outpost_subnets_cidr_blocks"
  type           = "String"
  tier           = "Standard"
  insecure_value = jsonencode(module.bar_vpc.outpost_subnets_cidr_blocks)
  tags           = var.tags
}

resource "aws_ssm_parameter" "bar_outpost_subnets_ipv6_cidr_blocks" {
  name           = "/${var.env}/${var.component}/bar_outpost_subnets_ipv6_cidr_blocks"
  type           = "String"
  tier           = "Standard"
  insecure_value = jsonencode(module.bar_vpc.outpost_subnets_ipv6_cidr_blocks)
  tags           = var.tags
}

resource "aws_ssm_parameter" "bar_private_ipv6_egress_route_ids" {
  name           = "/${var.env}/${var.component}/bar_private_ipv6_egress_route_ids"
  type           = "String"
  tier           = "Standard"
  insecure_value = jsonencode(module.bar_vpc.private_ipv6_egress_route_ids)
  tags           = var.tags
}

resource "aws_ssm_parameter" "bar_private_nat_gateway_route_ids" {
  name           = "/${var.env}/${var.component}/bar_private_nat_gateway_route_ids"
  type           = "String"
  tier           = "Standard"
  insecure_value = jsonencode(module.bar_vpc.private_nat_gateway_route_ids)
  tags           = var.tags
}

resource "aws_ssm_parameter" "bar_private_network_acl_arn" {
  name           = "/${var.env}/${var.component}/bar_private_network_acl_arn"
  type           = "String"
  tier           = "Standard"
  insecure_value = jsonencode(module.bar_vpc.private_network_acl_arn)
  tags           = var.tags
}

resource "aws_ssm_parameter" "bar_private_network_acl_id" {
  name           = "/${var.env}/${var.component}/bar_private_network_acl_id"
  type           = "String"
  tier           = "Standard"
  insecure_value = jsonencode(module.bar_vpc.private_network_acl_id)
  tags           = var.tags
}

resource "aws_ssm_parameter" "bar_private_route_table_association_ids" {
  name           = "/${var.env}/${var.component}/bar_private_route_table_association_ids"
  type           = "String"
  tier           = "Standard"
  insecure_value = jsonencode(module.bar_vpc.private_route_table_association_ids)
  tags           = var.tags
}

resource "aws_ssm_parameter" "bar_private_route_table_ids" {
  name           = "/${var.env}/${var.component}/bar_private_route_table_ids"
  type           = "String"
  tier           = "Standard"
  insecure_value = jsonencode(module.bar_vpc.private_route_table_ids)
  tags           = var.tags
}

resource "aws_ssm_parameter" "bar_private_subnet_arns" {
  name           = "/${var.env}/${var.component}/bar_private_subnet_arns"
  type           = "String"
  tier           = "Standard"
  insecure_value = jsonencode(module.bar_vpc.private_subnet_arns)
  tags           = var.tags
}

resource "aws_ssm_parameter" "bar_private_subnets" {
  name           = "/${var.env}/${var.component}/bar_private_subnets"
  type           = "String"
  tier           = "Standard"
  insecure_value = jsonencode(module.bar_vpc.private_subnets)
  tags           = var.tags
}

resource "aws_ssm_parameter" "bar_private_subnets_cidr_blocks" {
  name           = "/${var.env}/${var.component}/bar_private_subnets_cidr_blocks"
  type           = "String"
  tier           = "Standard"
  insecure_value = jsonencode(module.bar_vpc.private_subnets_cidr_blocks)
  tags           = var.tags
}

resource "aws_ssm_parameter" "bar_private_subnets_ipv6_cidr_blocks" {
  name           = "/${var.env}/${var.component}/bar_private_subnets_ipv6_cidr_blocks"
  type           = "String"
  tier           = "Standard"
  insecure_value = jsonencode(module.bar_vpc.private_subnets_ipv6_cidr_blocks)
  tags           = var.tags
}

resource "aws_ssm_parameter" "bar_public_internet_gateway_ipv6_route_id" {
  name           = "/${var.env}/${var.component}/bar_public_internet_gateway_ipv6_route_id"
  type           = "String"
  tier           = "Standard"
  insecure_value = jsonencode(module.bar_vpc.public_internet_gateway_ipv6_route_id)
  tags           = var.tags
}

resource "aws_ssm_parameter" "bar_public_internet_gateway_route_id" {
  name           = "/${var.env}/${var.component}/bar_public_internet_gateway_route_id"
  type           = "String"
  tier           = "Standard"
  insecure_value = jsonencode(module.bar_vpc.public_internet_gateway_route_id)
  tags           = var.tags
}

resource "aws_ssm_parameter" "bar_public_network_acl_arn" {
  name           = "/${var.env}/${var.component}/bar_public_network_acl_arn"
  type           = "String"
  tier           = "Standard"
  insecure_value = jsonencode(module.bar_vpc.public_network_acl_arn)
  tags           = var.tags
}

resource "aws_ssm_parameter" "bar_public_network_acl_id" {
  name           = "/${var.env}/${var.component}/bar_public_network_acl_id"
  type           = "String"
  tier           = "Standard"
  insecure_value = jsonencode(module.bar_vpc.public_network_acl_id)
  tags           = var.tags
}

resource "aws_ssm_parameter" "bar_public_route_table_association_ids" {
  name           = "/${var.env}/${var.component}/bar_public_route_table_association_ids"
  type           = "String"
  tier           = "Standard"
  insecure_value = jsonencode(module.bar_vpc.public_route_table_association_ids)
  tags           = var.tags
}

resource "aws_ssm_parameter" "bar_public_route_table_ids" {
  name           = "/${var.env}/${var.component}/bar_public_route_table_ids"
  type           = "String"
  tier           = "Standard"
  insecure_value = jsonencode(module.bar_vpc.public_route_table_ids)
  tags           = var.tags
}

resource "aws_ssm_parameter" "bar_public_subnet_arns" {
  name           = "/${var.env}/${var.component}/bar_public_subnet_arns"
  type           = "String"
  tier           = "Standard"
  insecure_value = jsonencode(module.bar_vpc.public_subnet_arns)
  tags           = var.tags
}

resource "aws_ssm_parameter" "bar_public_subnets" {
  name           = "/${var.env}/${var.component}/bar_public_subnets"
  type           = "String"
  tier           = "Standard"
  insecure_value = jsonencode(module.bar_vpc.public_subnets)
  tags           = var.tags
}

resource "aws_ssm_parameter" "bar_public_subnets_cidr_blocks" {
  name           = "/${var.env}/${var.component}/bar_public_subnets_cidr_blocks"
  type           = "String"
  tier           = "Standard"
  insecure_value = jsonencode(module.bar_vpc.public_subnets_cidr_blocks)
  tags           = var.tags
}

resource "aws_ssm_parameter" "bar_public_subnets_ipv6_cidr_blocks" {
  name           = "/${var.env}/${var.component}/bar_public_subnets_ipv6_cidr_blocks"
  type           = "String"
  tier           = "Standard"
  insecure_value = jsonencode(module.bar_vpc.public_subnets_ipv6_cidr_blocks)
  tags           = var.tags
}

resource "aws_ssm_parameter" "bar_redshift_network_acl_arn" {
  name           = "/${var.env}/${var.component}/bar_redshift_network_acl_arn"
  type           = "String"
  tier           = "Standard"
  insecure_value = jsonencode(module.bar_vpc.redshift_network_acl_arn)
  tags           = var.tags
}

resource "aws_ssm_parameter" "bar_redshift_network_acl_id" {
  name           = "/${var.env}/${var.component}/bar_redshift_network_acl_id"
  type           = "String"
  tier           = "Standard"
  insecure_value = jsonencode(module.bar_vpc.redshift_network_acl_id)
  tags           = var.tags
}

resource "aws_ssm_parameter" "bar_redshift_public_route_table_association_ids" {
  name           = "/${var.env}/${var.component}/bar_redshift_public_route_table_association_ids"
  type           = "String"
  tier           = "Standard"
  insecure_value = jsonencode(module.bar_vpc.redshift_public_route_table_association_ids)
  tags           = var.tags
}

resource "aws_ssm_parameter" "bar_redshift_route_table_association_ids" {
  name           = "/${var.env}/${var.component}/bar_redshift_route_table_association_ids"
  type           = "String"
  tier           = "Standard"
  insecure_value = jsonencode(module.bar_vpc.redshift_route_table_association_ids)
  tags           = var.tags
}

resource "aws_ssm_parameter" "bar_redshift_route_table_ids" {
  name           = "/${var.env}/${var.component}/bar_redshift_route_table_ids"
  type           = "String"
  tier           = "Standard"
  insecure_value = jsonencode(module.bar_vpc.redshift_route_table_ids)
  tags           = var.tags
}

resource "aws_ssm_parameter" "bar_redshift_subnet_arns" {
  name           = "/${var.env}/${var.component}/bar_redshift_subnet_arns"
  type           = "String"
  tier           = "Standard"
  insecure_value = jsonencode(module.bar_vpc.redshift_subnet_arns)
  tags           = var.tags
}

resource "aws_ssm_parameter" "bar_redshift_subnet_group" {
  name           = "/${var.env}/${var.component}/bar_redshift_subnet_group"
  type           = "String"
  tier           = "Standard"
  insecure_value = jsonencode(module.bar_vpc.redshift_subnet_group)
  tags           = var.tags
}

resource "aws_ssm_parameter" "bar_redshift_subnets" {
  name           = "/${var.env}/${var.component}/bar_redshift_subnets"
  type           = "String"
  tier           = "Standard"
  insecure_value = jsonencode(module.bar_vpc.redshift_subnets)
  tags           = var.tags
}

resource "aws_ssm_parameter" "bar_redshift_subnets_cidr_blocks" {
  name           = "/${var.env}/${var.component}/bar_redshift_subnets_cidr_blocks"
  type           = "String"
  tier           = "Standard"
  insecure_value = jsonencode(module.bar_vpc.redshift_subnets_cidr_blocks)
  tags           = var.tags
}

resource "aws_ssm_parameter" "bar_redshift_subnets_ipv6_cidr_blocks" {
  name           = "/${var.env}/${var.component}/bar_redshift_subnets_ipv6_cidr_blocks"
  type           = "String"
  tier           = "Standard"
  insecure_value = jsonencode(module.bar_vpc.redshift_subnets_ipv6_cidr_blocks)
  tags           = var.tags
}

resource "aws_ssm_parameter" "bar_this_customer_gateway" {
  name           = "/${var.env}/${var.component}/bar_this_customer_gateway"
  type           = "String"
  tier           = "Standard"
  insecure_value = jsonencode(module.bar_vpc.this_customer_gateway)
  tags           = var.tags
}

resource "aws_ssm_parameter" "bar_vgw_arn" {
  name           = "/${var.env}/${var.component}/bar_vgw_arn"
  type           = "String"
  tier           = "Standard"
  insecure_value = jsonencode(module.bar_vpc.vgw_arn)
  tags           = var.tags
}

resource "aws_ssm_parameter" "bar_vgw_id" {
  name           = "/${var.env}/${var.component}/bar_vgw_id"
  type           = "String"
  tier           = "Standard"
  insecure_value = jsonencode(module.bar_vpc.vgw_id)
  tags           = var.tags
}

resource "aws_ssm_parameter" "bar_vpc_arn" {
  name           = "/${var.env}/${var.component}/bar_vpc_arn"
  type           = "String"
  tier           = "Standard"
  insecure_value = jsonencode(module.bar_vpc.vpc_arn)
  tags           = var.tags
}

resource "aws_ssm_parameter" "bar_vpc_cidr_block" {
  name           = "/${var.env}/${var.component}/bar_vpc_cidr_block"
  type           = "String"
  tier           = "Standard"
  insecure_value = jsonencode(module.bar_vpc.vpc_cidr_block)
  tags           = var.tags
}

resource "aws_ssm_parameter" "bar_vpc_enable_dns_hostnames" {
  name           = "/${var.env}/${var.component}/bar_vpc_enable_dns_hostnames"
  type           = "String"
  tier           = "Standard"
  insecure_value = jsonencode(module.bar_vpc.vpc_enable_dns_hostnames)
  tags           = var.tags
}

resource "aws_ssm_parameter" "bar_vpc_enable_dns_support" {
  name           = "/${var.env}/${var.component}/bar_vpc_enable_dns_support"
  type           = "String"
  tier           = "Standard"
  insecure_value = jsonencode(module.bar_vpc.vpc_enable_dns_support)
  tags           = var.tags
}

resource "aws_ssm_parameter" "bar_vpc_flow_log_cloudwatch_iam_role_arn" {
  name           = "/${var.env}/${var.component}/bar_vpc_flow_log_cloudwatch_iam_role_arn"
  type           = "String"
  tier           = "Standard"
  insecure_value = jsonencode(module.bar_vpc.vpc_flow_log_cloudwatch_iam_role_arn)
  tags           = var.tags
}

resource "aws_ssm_parameter" "bar_vpc_flow_log_destination_arn" {
  name           = "/${var.env}/${var.component}/bar_vpc_flow_log_destination_arn"
  type           = "String"
  tier           = "Standard"
  insecure_value = jsonencode(module.bar_vpc.vpc_flow_log_destination_arn)
  tags           = var.tags
}

resource "aws_ssm_parameter" "bar_vpc_flow_log_destination_type" {
  name           = "/${var.env}/${var.component}/bar_vpc_flow_log_destination_type"
  type           = "String"
  tier           = "Standard"
  insecure_value = jsonencode(module.bar_vpc.vpc_flow_log_destination_type)
  tags           = var.tags
}

resource "aws_ssm_parameter" "bar_vpc_flow_log_id" {
  name           = "/${var.env}/${var.component}/bar_vpc_flow_log_id"
  type           = "String"
  tier           = "Standard"
  insecure_value = jsonencode(module.bar_vpc.vpc_flow_log_id)
  tags           = var.tags
}

resource "aws_ssm_parameter" "bar_vpc_id" {
  name           = "/${var.env}/${var.component}/bar_vpc_id"
  type           = "String"
  tier           = "Standard"
  insecure_value = jsonencode(module.bar_vpc.vpc_id)
  tags           = var.tags
}

resource "aws_ssm_parameter" "bar_vpc_instance_tenancy" {
  name           = "/${var.env}/${var.component}/bar_vpc_instance_tenancy"
  type           = "String"
  tier           = "Standard"
  insecure_value = jsonencode(module.bar_vpc.vpc_instance_tenancy)
  tags           = var.tags
}

resource "aws_ssm_parameter" "bar_vpc_ipv6_association_id" {
  name           = "/${var.env}/${var.component}/bar_vpc_ipv6_association_id"
  type           = "String"
  tier           = "Standard"
  insecure_value = jsonencode(module.bar_vpc.vpc_ipv6_association_id)
  tags           = var.tags
}

resource "aws_ssm_parameter" "bar_vpc_ipv6_cidr_block" {
  name           = "/${var.env}/${var.component}/bar_vpc_ipv6_cidr_block"
  type           = "String"
  tier           = "Standard"
  insecure_value = jsonencode(module.bar_vpc.vpc_ipv6_cidr_block)
  tags           = var.tags
}

resource "aws_ssm_parameter" "bar_vpc_main_route_table_id" {
  name           = "/${var.env}/${var.component}/bar_vpc_main_route_table_id"
  type           = "String"
  tier           = "Standard"
  insecure_value = jsonencode(module.bar_vpc.vpc_main_route_table_id)
  tags           = var.tags
}

resource "aws_ssm_parameter" "bar_vpc_owner_id" {
  name           = "/${var.env}/${var.component}/bar_vpc_owner_id"
  type           = "String"
  tier           = "Standard"
  insecure_value = jsonencode(module.bar_vpc.vpc_owner_id)
  tags           = var.tags
}

resource "aws_ssm_parameter" "bar_vpc_secondary_cidr_blocks" {
  name           = "/${var.env}/${var.component}/bar_vpc_secondary_cidr_blocks"
  type           = "String"
  tier           = "Standard"
  insecure_value = jsonencode(module.bar_vpc.vpc_secondary_cidr_blocks)
  tags           = var.tags
}

// module "baz_vpc" ssm Parameter Store integration registry entries (non sensitive)
resource "aws_ssm_parameter" "baz_azs" {
  name           = "/${var.env}/${var.component}/network/baz/azs"
  type           = "String"
  tier           = "Standard"
  insecure_value = jsonencode(module.baz_vpc.azs)
  tags           = var.tags
}

resource "aws_ssm_parameter" "baz_database_subnets" {
  for_each       = module.baz_vpc.database_subnets
  name           = "/${var.env}/${var.component}/network/baz/subnets/database/${each.key}"
  type           = "String"
  tier           = "Standard"
  insecure_value = jsonencode(each.value)
  tags           = var.tags
}

resource "aws_ssm_parameter" "baz_private_subnets" {
  for_each       = module.baz_vpc.private_subnets
  name           = "/${var.env}/${var.component}/network/baz/subnets/private/${each.key}"
  type           = "String"
  tier           = "Standard"
  insecure_value = jsonencode(each.value)
  tags           = var.tags
}

resource "aws_ssm_parameter" "baz_public_subnets" {
  for_each       = module.baz_vpc.public_subnets
  name           = "/${var.env}/${var.component}/network/baz/subnets/public/${each.key}"
  type           = "String"
  tier           = "Standard"
  insecure_value = jsonencode(each.value)
  tags           = var.tags
}

resource "aws_ssm_parameter" "baz_vpc_id" {
  name           = "/${var.env}/${var.component}/network/baz/vpc_id"
  type           = "String"
  tier           = "Standard"
  insecure_value = module.baz_vpc.vpc_id
  tags           = var.tags
}

// module "corge_vpc" ssm Parameter Store integration registry entries (non sensitive)
resource "aws_ssm_parameter" "corge_azs" {
  name           = "/${var.env}/network/corge_azs"
  type           = "String"
  tier           = "Standard"
  insecure_value = jsonencode(module.corge_vpc.azs)
  tags           = var.tags
}

resource "aws_ssm_parameter" "corge_database_subnets" {
  for_each       = module.corge_vpc.database_subnets
  name           = "/${var.env}/network/subnets/database/${each.key}"
  type           = "String"
  tier           = "Standard"
  insecure_value = each.value
  tags           = var.tags
}

resource "aws_ssm_parameter" "corge_private_subnets" {
  for_each       = module.corge_vpc.private_subnets
  name           = "/${var.env}/network/subnets/private/${each.key}"
  type           = "String"
  tier           = "Standard"
  insecure_value = each.value
  tags           = var.tags
}

resource "aws_ssm_parameter" "corge_public_subnets" {
  for_each       = module.corge_vpc.public_subnets
  name           = "/${var.env}/network/subnets/public/${each.key}"
  type           = "String"
  tier           = "Standard"
  insecure_value = each.value
  tags           = var.tags
}

resource "aws_ssm_parameter" "corge_vpc_id" {
  name           = "/${var.env}/${var.component}/network/corge_vpc_id"
  type           = "String"
  tier           = "Standard"
  insecure_value = module.corge_vpc.vpc_id
  tags           = var.tags
}

// module "grault_vpc" ssm Parameter Store integration registry entries (non sensitive)
resource "aws_ssm_parameter" "grault_azs" {
  name           = "/${var.env}/network/vpc_azs"
  type           = "String"
  tier           = "Standard"
  insecure_value = jsonencode(module.grault_vpc.azs)
  tags           = var.tags
}

resource "aws_ssm_parameter" "grault_database_subnets" {
  for_each       = module.grault_vpc.database_subnets
  name           = "/${var.env}/${var.component}/network/subnets/database/${each.key}"
  type           = "String"
  tier           = "Standard"
  insecure_value = each.value
  tags           = var.tags
}

resource "aws_ssm_parameter" "grault_private_subnets" {
  for_each       = module.grault_vpc.private_subnets
  name           = "/${var.env}/${var.component}/network/subnets/private/${each.key}"
  type           = "String"
  tier           = "Standard"
  insecure_value = each.value
  tags           = var.tags
}

resource "aws_ssm_parameter" "grault_public_subnets" {
  for_each       = module.grault_vpc.public_subnets
  name           = "/${var.env}/${var.component}/network/subnets/public/${each.key}"
  type           = "String"
  tier           = "Standard"
  insecure_value = each.value
  tags           = var.tags
}

resource "aws_ssm_parameter" "grault_vpc_id" {
  name           = "/${var.env}/${var.component}/network/vpc_id"
  type           = "String"
  tier           = "Standard"
  insecure_value = module.grault_vpc.vpc_id
  tags           = var.tags
}

// module "qux_vpc" ssm Parameter Store integration registry entries (non sensitive)
