# Auto-generated by fogg. Do not edit
# Make improvements in fogg, so that everyone can benefit.

# module "network" outputs
output "azs" {
  value     = module.network.azs
  sensitive = false
}
output "cgw_arns" {
  value     = module.network.cgw_arns
  sensitive = false
}
output "cgw_ids" {
  value     = module.network.cgw_ids
  sensitive = false
}
output "database_internet_gateway_route_id" {
  value     = module.network.database_internet_gateway_route_id
  sensitive = false
}
output "database_ipv6_egress_route_id" {
  value     = module.network.database_ipv6_egress_route_id
  sensitive = false
}
output "database_nat_gateway_route_ids" {
  value     = module.network.database_nat_gateway_route_ids
  sensitive = false
}
output "database_network_acl_arn" {
  value     = module.network.database_network_acl_arn
  sensitive = false
}
output "database_network_acl_id" {
  value     = module.network.database_network_acl_id
  sensitive = false
}
output "database_route_table_association_ids" {
  value     = module.network.database_route_table_association_ids
  sensitive = false
}
output "database_route_table_ids" {
  value     = module.network.database_route_table_ids
  sensitive = false
}
output "database_subnet_arns" {
  value     = module.network.database_subnet_arns
  sensitive = false
}
output "database_subnet_group" {
  value     = module.network.database_subnet_group
  sensitive = false
}
output "database_subnet_group_name" {
  value     = module.network.database_subnet_group_name
  sensitive = false
}
output "database_subnets" {
  value     = module.network.database_subnets
  sensitive = false
}
output "database_subnets_cidr_blocks" {
  value     = module.network.database_subnets_cidr_blocks
  sensitive = false
}
output "database_subnets_ipv6_cidr_blocks" {
  value     = module.network.database_subnets_ipv6_cidr_blocks
  sensitive = false
}
output "default_network_acl_id" {
  value     = module.network.default_network_acl_id
  sensitive = false
}
output "default_route_table_id" {
  value     = module.network.default_route_table_id
  sensitive = false
}
output "default_security_group_id" {
  value     = module.network.default_security_group_id
  sensitive = false
}
output "default_vpc_arn" {
  value     = module.network.default_vpc_arn
  sensitive = false
}
output "default_vpc_cidr_block" {
  value     = module.network.default_vpc_cidr_block
  sensitive = false
}
output "default_vpc_default_network_acl_id" {
  value     = module.network.default_vpc_default_network_acl_id
  sensitive = false
}
output "default_vpc_default_route_table_id" {
  value     = module.network.default_vpc_default_route_table_id
  sensitive = false
}
output "default_vpc_default_security_group_id" {
  value     = module.network.default_vpc_default_security_group_id
  sensitive = false
}
output "default_vpc_enable_dns_hostnames" {
  value     = module.network.default_vpc_enable_dns_hostnames
  sensitive = false
}
output "default_vpc_enable_dns_support" {
  value     = module.network.default_vpc_enable_dns_support
  sensitive = false
}
output "default_vpc_id" {
  value     = module.network.default_vpc_id
  sensitive = false
}
output "default_vpc_instance_tenancy" {
  value     = module.network.default_vpc_instance_tenancy
  sensitive = false
}
output "default_vpc_main_route_table_id" {
  value     = module.network.default_vpc_main_route_table_id
  sensitive = false
}
output "dhcp_options_id" {
  value     = module.network.dhcp_options_id
  sensitive = false
}
output "egress_only_internet_gateway_id" {
  value     = module.network.egress_only_internet_gateway_id
  sensitive = false
}
output "elasticache_network_acl_arn" {
  value     = module.network.elasticache_network_acl_arn
  sensitive = false
}
output "elasticache_network_acl_id" {
  value     = module.network.elasticache_network_acl_id
  sensitive = false
}
output "elasticache_route_table_association_ids" {
  value     = module.network.elasticache_route_table_association_ids
  sensitive = false
}
output "elasticache_route_table_ids" {
  value     = module.network.elasticache_route_table_ids
  sensitive = false
}
output "elasticache_subnet_arns" {
  value     = module.network.elasticache_subnet_arns
  sensitive = false
}
output "elasticache_subnet_group" {
  value     = module.network.elasticache_subnet_group
  sensitive = false
}
output "elasticache_subnet_group_name" {
  value     = module.network.elasticache_subnet_group_name
  sensitive = false
}
output "elasticache_subnets" {
  value     = module.network.elasticache_subnets
  sensitive = false
}
output "elasticache_subnets_cidr_blocks" {
  value     = module.network.elasticache_subnets_cidr_blocks
  sensitive = false
}
output "elasticache_subnets_ipv6_cidr_blocks" {
  value     = module.network.elasticache_subnets_ipv6_cidr_blocks
  sensitive = false
}
output "igw_arn" {
  value     = module.network.igw_arn
  sensitive = false
}
output "igw_id" {
  value     = module.network.igw_id
  sensitive = false
}
output "intra_network_acl_arn" {
  value     = module.network.intra_network_acl_arn
  sensitive = false
}
output "intra_network_acl_id" {
  value     = module.network.intra_network_acl_id
  sensitive = false
}
output "intra_route_table_association_ids" {
  value     = module.network.intra_route_table_association_ids
  sensitive = false
}
output "intra_route_table_ids" {
  value     = module.network.intra_route_table_ids
  sensitive = false
}
output "intra_subnet_arns" {
  value     = module.network.intra_subnet_arns
  sensitive = false
}
output "intra_subnets" {
  value     = module.network.intra_subnets
  sensitive = false
}
output "intra_subnets_cidr_blocks" {
  value     = module.network.intra_subnets_cidr_blocks
  sensitive = false
}
output "intra_subnets_ipv6_cidr_blocks" {
  value     = module.network.intra_subnets_ipv6_cidr_blocks
  sensitive = false
}
output "name" {
  value     = module.network.name
  sensitive = false
}
output "nat_ids" {
  value     = module.network.nat_ids
  sensitive = false
}
output "nat_public_ips" {
  value     = module.network.nat_public_ips
  sensitive = false
}
output "natgw_ids" {
  value     = module.network.natgw_ids
  sensitive = false
}
output "outpost_network_acl_arn" {
  value     = module.network.outpost_network_acl_arn
  sensitive = false
}
output "outpost_network_acl_id" {
  value     = module.network.outpost_network_acl_id
  sensitive = false
}
output "outpost_subnet_arns" {
  value     = module.network.outpost_subnet_arns
  sensitive = false
}
output "outpost_subnets" {
  value     = module.network.outpost_subnets
  sensitive = false
}
output "outpost_subnets_cidr_blocks" {
  value     = module.network.outpost_subnets_cidr_blocks
  sensitive = false
}
output "outpost_subnets_ipv6_cidr_blocks" {
  value     = module.network.outpost_subnets_ipv6_cidr_blocks
  sensitive = false
}
output "private_ipv6_egress_route_ids" {
  value     = module.network.private_ipv6_egress_route_ids
  sensitive = false
}
output "private_nat_gateway_route_ids" {
  value     = module.network.private_nat_gateway_route_ids
  sensitive = false
}
output "private_network_acl_arn" {
  value     = module.network.private_network_acl_arn
  sensitive = false
}
output "private_network_acl_id" {
  value     = module.network.private_network_acl_id
  sensitive = false
}
output "private_route_table_association_ids" {
  value     = module.network.private_route_table_association_ids
  sensitive = false
}
output "private_route_table_ids" {
  value     = module.network.private_route_table_ids
  sensitive = false
}
output "private_subnet_arns" {
  value     = module.network.private_subnet_arns
  sensitive = false
}
output "private_subnets" {
  value     = module.network.private_subnets
  sensitive = false
}
output "private_subnets_cidr_blocks" {
  value     = module.network.private_subnets_cidr_blocks
  sensitive = false
}
output "private_subnets_ipv6_cidr_blocks" {
  value     = module.network.private_subnets_ipv6_cidr_blocks
  sensitive = false
}
output "public_internet_gateway_ipv6_route_id" {
  value     = module.network.public_internet_gateway_ipv6_route_id
  sensitive = false
}
output "public_internet_gateway_route_id" {
  value     = module.network.public_internet_gateway_route_id
  sensitive = false
}
output "public_network_acl_arn" {
  value     = module.network.public_network_acl_arn
  sensitive = false
}
output "public_network_acl_id" {
  value     = module.network.public_network_acl_id
  sensitive = false
}
output "public_route_table_association_ids" {
  value     = module.network.public_route_table_association_ids
  sensitive = false
}
output "public_route_table_ids" {
  value     = module.network.public_route_table_ids
  sensitive = false
}
output "public_subnet_arns" {
  value     = module.network.public_subnet_arns
  sensitive = false
}
output "public_subnets" {
  value     = module.network.public_subnets
  sensitive = false
}
output "public_subnets_cidr_blocks" {
  value     = module.network.public_subnets_cidr_blocks
  sensitive = false
}
output "public_subnets_ipv6_cidr_blocks" {
  value     = module.network.public_subnets_ipv6_cidr_blocks
  sensitive = false
}
output "redshift_network_acl_arn" {
  value     = module.network.redshift_network_acl_arn
  sensitive = false
}
output "redshift_network_acl_id" {
  value     = module.network.redshift_network_acl_id
  sensitive = false
}
output "redshift_public_route_table_association_ids" {
  value     = module.network.redshift_public_route_table_association_ids
  sensitive = false
}
output "redshift_route_table_association_ids" {
  value     = module.network.redshift_route_table_association_ids
  sensitive = false
}
output "redshift_route_table_ids" {
  value     = module.network.redshift_route_table_ids
  sensitive = false
}
output "redshift_subnet_arns" {
  value     = module.network.redshift_subnet_arns
  sensitive = false
}
output "redshift_subnet_group" {
  value     = module.network.redshift_subnet_group
  sensitive = false
}
output "redshift_subnets" {
  value     = module.network.redshift_subnets
  sensitive = false
}
output "redshift_subnets_cidr_blocks" {
  value     = module.network.redshift_subnets_cidr_blocks
  sensitive = false
}
output "redshift_subnets_ipv6_cidr_blocks" {
  value     = module.network.redshift_subnets_ipv6_cidr_blocks
  sensitive = false
}
output "this_customer_gateway" {
  value     = module.network.this_customer_gateway
  sensitive = false
}
output "vgw_arn" {
  value     = module.network.vgw_arn
  sensitive = false
}
output "vgw_id" {
  value     = module.network.vgw_id
  sensitive = false
}
output "vpc_arn" {
  value     = module.network.vpc_arn
  sensitive = false
}
output "vpc_cidr_block" {
  value     = module.network.vpc_cidr_block
  sensitive = false
}
output "vpc_enable_dns_hostnames" {
  value     = module.network.vpc_enable_dns_hostnames
  sensitive = false
}
output "vpc_enable_dns_support" {
  value     = module.network.vpc_enable_dns_support
  sensitive = false
}
output "vpc_flow_log_cloudwatch_iam_role_arn" {
  value     = module.network.vpc_flow_log_cloudwatch_iam_role_arn
  sensitive = false
}
output "vpc_flow_log_destination_arn" {
  value     = module.network.vpc_flow_log_destination_arn
  sensitive = false
}
output "vpc_flow_log_destination_type" {
  value     = module.network.vpc_flow_log_destination_type
  sensitive = false
}
output "vpc_flow_log_id" {
  value     = module.network.vpc_flow_log_id
  sensitive = false
}
output "vpc_id" {
  value     = module.network.vpc_id
  sensitive = false
}
output "vpc_instance_tenancy" {
  value     = module.network.vpc_instance_tenancy
  sensitive = false
}
output "vpc_ipv6_association_id" {
  value     = module.network.vpc_ipv6_association_id
  sensitive = false
}
output "vpc_ipv6_cidr_block" {
  value     = module.network.vpc_ipv6_cidr_block
  sensitive = false
}
output "vpc_main_route_table_id" {
  value     = module.network.vpc_main_route_table_id
  sensitive = false
}
output "vpc_owner_id" {
  value     = module.network.vpc_owner_id
  sensitive = false
}
output "vpc_secondary_cidr_blocks" {
  value     = module.network.vpc_secondary_cidr_blocks
  sensitive = false
}
# module "my_module" outputs
