# Auto-generated by fogg. Do not edit
# Make improvements in fogg, so that everyone can benefit.
# tflint-ignore: terraform_unused_declarations
data "terraform_remote_state" "global" {
  backend = "http"
  config = {


    address        = "http://localhost:8080/tfstate/00000000-1111-2222-3333-444444444444"
    lock_address   = "http://localhost:8080/tfstate/00000000-1111-2222-3333-444444444444/lock"
    unlock_address = "http://localhost:8080/tfstate/00000000-1111-2222-3333-444444444444/unlock"






  }
}
# tflint-ignore: terraform_unused_declarations
data "terraform_remote_state" "cluster" {
  backend = "http"
  config = {


    address        = "http://localhost:8080/tfstate/44444444-5555-6666-7777-888888888888"
    lock_address   = "http://localhost:8080/tfstate/44444444-5555-6666-7777-888888888888/lock"
    unlock_address = "http://localhost:8080/tfstate/44444444-5555-6666-7777-888888888888/unlock"






  }
}
# tflint-ignore: terraform_unused_declarations
data "terraform_remote_state" "db" {
  backend = "http"
  config = {


    address        = "http://localhost:8080/tfstate/33333333-4444-5555-6666-777777777777"
    lock_address   = "http://localhost:8080/tfstate/33333333-4444-5555-6666-777777777777/lock"
    unlock_address = "http://localhost:8080/tfstate/33333333-4444-5555-6666-777777777777/unlock"






  }
}
# tflint-ignore: terraform_unused_declarations
data "terraform_remote_state" "legacy" {
  backend = "s3"
  config = {


    bucket = "some-bucket"

    key     = "terraform/proj/envs/test/components/legacy.tfstate"
    region  = "us-west-2"
    profile = "profile"


  }
}
# tflint-ignore: terraform_unused_declarations
data "terraform_remote_state" "vpc" {
  backend = "http"
  config = {


    address        = "http://localhost:8080/tfstate/11111111-2222-3333-4444-555555555555"
    lock_address   = "http://localhost:8080/tfstate/11111111-2222-3333-4444-555555555555/lock"
    unlock_address = "http://localhost:8080/tfstate/11111111-2222-3333-4444-555555555555/unlock"






  }
}
