# Auto-generated by fogg. Do not edit
# Make improvements in fogg, so that everyone can benefit.


  # Default Provider
  provider "aws" {
    version = "~> 0.12.0"
    region = "us-west-foo1"
    profile = "czi-foo"
    allowed_account_ids = [2]
  }

  # Aliased Providers (for doing things in every region).
  
    provider "aws" {
      alias = "us-east-foo2"
      version = "~> 0.12.0"
      region = "us-east-foo2"
      profile = "czi-foo"
      allowed_account_ids = [2]
    }
  




