# Auto-generated by fogg. Do not edit
# Make improvements in fogg, so that everyone can benefit.








provider "bless" {
  version = "~>0.0.0"
  region  = "bar"
  profile = "foofoofoo"
}


provider "bless" {
  alias   = "a"
  version = "~>0.0.0"
  region  = "a"
  profile = "foofoofoo"
}

provider "bless" {
  alias   = "b"
  version = "~>0.0.0"
  region  = "b"
  profile = "foofoofoo"
}








terraform {
  required_version = "=1.1.1"

  backend "s3" {
    bucket = "bucket"

    key     = "terraform/foofoo/accounts/foo.tfstate"
    encrypt = true
    region  = "region"
    profile = "foofoo"
  }
}

variable "project" {
  type    = "string"
  default = "foofoo"
}





variable "owner" {
  type    = "string"
  default = "foo@example.com"
}

variable "aws_accounts" {
  type = "map"
  default = {



  }
}



data "terraform_remote_state" "global" {
  backend = "s3"

  config = {
    bucket = "bucket"

    key     = "terraform/foofoo/global.tfstate"
    region  = "region"
    profile = "foofoo"
  }
}





