# Auto-generated by fogg. Do not edit
# Make improvements in fogg, so that everyone can benefit.















terraform {
  required_version = "=1.1.1"


  backend "remote" {



    hostname     = "tfe.example.com"
    organization = "test-org"
    workspaces {
      name = "accounts/acct1"
    }



  }

}

variable "project" {
  type    = string
  default = "foo"
}





variable "owner" {
  type    = string
  default = "foo@example.com"
}

variable "aws_accounts" {
  type = map
  default = {



  }
}



data "terraform_remote_state" "global" {
  backend = "remote"

  config = {



    hostname     = "tfe.example.com"
    organization = "test-org"
    workspaces {
      name = "global"
    }



  }
}




provider random {
  version = "~> 2.2"
}

provider template {
  version = "~> 2.1"
}

provider archive {
  version = "~> 1.3"
}

provider null {
  version = "~> 2.1"
}

provider local {
  version = "~> 1.4"
}

provider tls {
  version = "~> 2.1"
}
