# Auto-generated by fogg. Do not edit
# Make improvements in fogg, so that everyone can benefit.



provider "aws" {
  
  region = "us-west-2"
  
  
  assume_role {
    role_arn     = "arn:aws:iam::00456:role/foo"
  }
  
  allowed_account_ids = ["00456"]
  default_tags {
    tags = {
      