# Auto-generated by fogg. Do not edit
# Make improvements in fogg, so that everyone can benefit.
provider "aws" {

  region = "us-west-2"


  assume_role {
    role_arn = "arn:aws:iam::123456789012:role/role"
  }

  allowed_account_ids = ["123456789012"]
}
# Aliased Providers (for doing things in every region).


provider "aws" {
  alias  = "shared_services"
  region = "ap-southeast-1"


  assume_role {
    role_arn = "arn:aws:iam::210987654321:role/role"
  }

  allowed_account_ids = ["210987654321"]
}


provider "assert" {}
terraform {
  required_version = "=1.7.5"

  backend "s3" {

    bucket = "buck"

    key     = "terraform/proj/envs/test/components/network-old.tfstate"
    encrypt = true
    region  = "us-west-2"

    assume_role = {
      role_arn = "arn:aws:iam::123456789012:role/role"
    }

  }
  required_providers {
    archive = {
      source  = "hashicorp/archive"
      version = "~> 2.0"
    }
    assert = {
      source  = "bwoznicki/assert"
      version = "0.0.1"
    }
    aws = {
      source  = "hashicorp/aws"
      version = "0.12.0"
    }
    local = {
      source  = "hashicorp/local"
      version = "~> 2.0"
    }
    null = {
      source  = "hashicorp/null"
      version = "~> 3.0"
    }
    okta-head = {
      source  = "okta/okta"
      version = "~> 3.30"
    }
    random = {
      source  = "hashicorp/random"
      version = "~> 3.4"
    }
    tls = {
      source  = "hashicorp/tls"
      version = "~> 3.0"
    }
  }
}
# tflint-ignore: terraform_unused_declarations
variable "env" {
  type    = string
  default = "test"
}
# tflint-ignore: terraform_unused_declarations
variable "project" {
  type    = string
  default = "proj"
}
# tflint-ignore: terraform_unused_declarations
variable "region" {
  type    = string
  default = "us-west-2"
}
# tflint-ignore: terraform_unused_declarations
variable "component" {
  type    = string
  default = "network-old"
}
# tflint-ignore: terraform_unused_declarations
variable "owner" {
  type    = string
  default = "foo@example.com"
}
# tflint-ignore: terraform_unused_declarations
variable "tags" {
  type = object({ project : string, env : string, service : string, owner : string, managedBy : string, tfstateKey : string })
  default = {
    project    = "proj"
    env        = "test"
    service    = "network-old"
    owner      = "foo@example.com"
    tfstateKey = "terraform/proj/envs/test/components/network-old.tfstate"

    managedBy = "terraform"
  }
}
# tflint-ignore: terraform_unused_declarations
variable "aws_accounts" {
  type = map(string)
  default = {

  }
}
