// Auto-generated by fogg. Do not edit
// Make improvements in fogg, so that everyone can benefit.

/**
 * Outputs for:
 * - Environment: "test"
 * - Component: "network-old"
 */
export interface NetworkOldOutputs {
  // module "vpc" outputs
  /**
    * A list of availability zones specified as argument to this module
    */
  azs: any;
  /**
    * List of ARNs of Customer Gateway
    */
  cgw_arns: any;
  /**
    * List of IDs of Customer Gateway
    */
  cgw_ids: any;
  /**
    * ID of the database internet gateway route
    */
  database_internet_gateway_route_id: any;
  /**
    * ID of the database IPv6 egress route
    */
  database_ipv6_egress_route_id: any;
  /**
    * List of IDs of the database nat gateway route
    */
  database_nat_gateway_route_ids: any;
  /**
    * ARN of the database network ACL
    */
  database_network_acl_arn: any;
  /**
    * ID of the database network ACL
    */
  database_network_acl_id: any;
  /**
    * List of IDs of the database route table association
    */
  database_route_table_association_ids: any;
  /**
    * List of IDs of database route tables
    */
  database_route_table_ids: any;
  /**
    * List of ARNs of database subnets
    */
  database_subnet_arns: any;
  /**
    * ID of database subnet group
    */
  database_subnet_group: any;
  /**
    * Name of database subnet group
    */
  database_subnet_group_name: any;
  /**
    * List of IDs of database subnets
    */
  database_subnets: any;
  /**
    * List of cidr_blocks of database subnets
    */
  database_subnets_cidr_blocks: any;
  /**
    * List of IPv6 cidr_blocks of database subnets in an IPv6 enabled VPC
    */
  database_subnets_ipv6_cidr_blocks: any;
  /**
    * The ID of the default network ACL
    */
  default_network_acl_id: any;
  /**
    * The ID of the default route table
    */
  default_route_table_id: any;
  /**
    * The ID of the security group created by default on VPC creation
    */
  default_security_group_id: any;
  /**
    * The ARN of the Default VPC
    */
  default_vpc_arn: any;
  /**
    * The CIDR block of the Default VPC
    */
  default_vpc_cidr_block: any;
  /**
    * The ID of the default network ACL of the Default VPC
    */
  default_vpc_default_network_acl_id: any;
  /**
    * The ID of the default route table of the Default VPC
    */
  default_vpc_default_route_table_id: any;
  /**
    * The ID of the security group created by default on Default VPC creation
    */
  default_vpc_default_security_group_id: any;
  /**
    * Whether or not the Default VPC has DNS hostname support
    */
  default_vpc_enable_dns_hostnames: any;
  /**
    * Whether or not the Default VPC has DNS support
    */
  default_vpc_enable_dns_support: any;
  /**
    * The ID of the Default VPC
    */
  default_vpc_id: any;
  /**
    * Tenancy of instances spin up within Default VPC
    */
  default_vpc_instance_tenancy: any;
  /**
    * The ID of the main route table associated with the Default VPC
    */
  default_vpc_main_route_table_id: any;
  /**
    * The ID of the DHCP options
    */
  dhcp_options_id: any;
  /**
    * The ID of the egress only Internet Gateway
    */
  egress_only_internet_gateway_id: any;
  /**
    * ARN of the elasticache network ACL
    */
  elasticache_network_acl_arn: any;
  /**
    * ID of the elasticache network ACL
    */
  elasticache_network_acl_id: any;
  /**
    * List of IDs of the elasticache route table association
    */
  elasticache_route_table_association_ids: any;
  /**
    * List of IDs of elasticache route tables
    */
  elasticache_route_table_ids: any;
  /**
    * List of ARNs of elasticache subnets
    */
  elasticache_subnet_arns: any;
  /**
    * ID of elasticache subnet group
    */
  elasticache_subnet_group: any;
  /**
    * Name of elasticache subnet group
    */
  elasticache_subnet_group_name: any;
  /**
    * List of IDs of elasticache subnets
    */
  elasticache_subnets: any;
  /**
    * List of cidr_blocks of elasticache subnets
    */
  elasticache_subnets_cidr_blocks: any;
  /**
    * List of IPv6 cidr_blocks of elasticache subnets in an IPv6 enabled VPC
    */
  elasticache_subnets_ipv6_cidr_blocks: any;
  /**
    * The ARN of the Internet Gateway
    */
  igw_arn: any;
  /**
    * The ID of the Internet Gateway
    */
  igw_id: any;
  /**
    * ARN of the intra network ACL
    */
  intra_network_acl_arn: any;
  /**
    * ID of the intra network ACL
    */
  intra_network_acl_id: any;
  /**
    * List of IDs of the intra route table association
    */
  intra_route_table_association_ids: any;
  /**
    * List of IDs of intra route tables
    */
  intra_route_table_ids: any;
  /**
    * List of ARNs of intra subnets
    */
  intra_subnet_arns: any;
  /**
    * List of IDs of intra subnets
    */
  intra_subnets: any;
  /**
    * List of cidr_blocks of intra subnets
    */
  intra_subnets_cidr_blocks: any;
  /**
    * List of IPv6 cidr_blocks of intra subnets in an IPv6 enabled VPC
    */
  intra_subnets_ipv6_cidr_blocks: any;
  /**
    * The name of the VPC specified as argument to this module
    */
  name: any;
  /**
    * List of allocation ID of Elastic IPs created for AWS NAT Gateway
    */
  nat_ids: any;
  /**
    * List of public Elastic IPs created for AWS NAT Gateway
    */
  nat_public_ips: any;
  /**
    * List of NAT Gateway IDs
    */
  natgw_ids: any;
  /**
    * ARN of the outpost network ACL
    */
  outpost_network_acl_arn: any;
  /**
    * ID of the outpost network ACL
    */
  outpost_network_acl_id: any;
  /**
    * List of ARNs of outpost subnets
    */
  outpost_subnet_arns: any;
  /**
    * List of IDs of outpost subnets
    */
  outpost_subnets: any;
  /**
    * List of cidr_blocks of outpost subnets
    */
  outpost_subnets_cidr_blocks: any;
  /**
    * List of IPv6 cidr_blocks of outpost subnets in an IPv6 enabled VPC
    */
  outpost_subnets_ipv6_cidr_blocks: any;
  /**
    * List of IDs of the ipv6 egress route
    */
  private_ipv6_egress_route_ids: any;
  /**
    * List of IDs of the private nat gateway route
    */
  private_nat_gateway_route_ids: any;
  /**
    * ARN of the private network ACL
    */
  private_network_acl_arn: any;
  /**
    * ID of the private network ACL
    */
  private_network_acl_id: any;
  /**
    * List of IDs of the private route table association
    */
  private_route_table_association_ids: any;
  /**
    * List of IDs of private route tables
    */
  private_route_table_ids: any;
  /**
    * List of ARNs of private subnets
    */
  private_subnet_arns: any;
  /**
    * List of IDs of private subnets
    */
  private_subnets: any;
  /**
    * List of cidr_blocks of private subnets
    */
  private_subnets_cidr_blocks: any;
  /**
    * List of IPv6 cidr_blocks of private subnets in an IPv6 enabled VPC
    */
  private_subnets_ipv6_cidr_blocks: any;
  /**
    * ID of the IPv6 internet gateway route
    */
  public_internet_gateway_ipv6_route_id: any;
  /**
    * ID of the internet gateway route
    */
  public_internet_gateway_route_id: any;
  /**
    * ARN of the public network ACL
    */
  public_network_acl_arn: any;
  /**
    * ID of the public network ACL
    */
  public_network_acl_id: any;
  /**
    * List of IDs of the public route table association
    */
  public_route_table_association_ids: any;
  /**
    * List of IDs of public route tables
    */
  public_route_table_ids: any;
  /**
    * List of ARNs of public subnets
    */
  public_subnet_arns: any;
  /**
    * List of IDs of public subnets
    */
  public_subnets: any;
  /**
    * List of cidr_blocks of public subnets
    */
  public_subnets_cidr_blocks: any;
  /**
    * List of IPv6 cidr_blocks of public subnets in an IPv6 enabled VPC
    */
  public_subnets_ipv6_cidr_blocks: any;
  /**
    * ARN of the redshift network ACL
    */
  redshift_network_acl_arn: any;
  /**
    * ID of the redshift network ACL
    */
  redshift_network_acl_id: any;
  /**
    * List of IDs of the public redshift route table association
    */
  redshift_public_route_table_association_ids: any;
  /**
    * List of IDs of the redshift route table association
    */
  redshift_route_table_association_ids: any;
  /**
    * List of IDs of redshift route tables
    */
  redshift_route_table_ids: any;
  /**
    * List of ARNs of redshift subnets
    */
  redshift_subnet_arns: any;
  /**
    * ID of redshift subnet group
    */
  redshift_subnet_group: any;
  /**
    * List of IDs of redshift subnets
    */
  redshift_subnets: any;
  /**
    * List of cidr_blocks of redshift subnets
    */
  redshift_subnets_cidr_blocks: any;
  /**
    * List of IPv6 cidr_blocks of redshift subnets in an IPv6 enabled VPC
    */
  redshift_subnets_ipv6_cidr_blocks: any;
  /**
    * Map of Customer Gateway attributes
    */
  this_customer_gateway: any;
  /**
    * The ARN of the VPN Gateway
    */
  vgw_arn: any;
  /**
    * The ID of the VPN Gateway
    */
  vgw_id: any;
  /**
    * The ARN of the VPC
    */
  vpc_arn: any;
  /**
    * The CIDR block of the VPC
    */
  vpc_cidr_block: any;
  /**
    * Whether or not the VPC has DNS hostname support
    */
  vpc_enable_dns_hostnames: any;
  /**
    * Whether or not the VPC has DNS support
    */
  vpc_enable_dns_support: any;
  /**
    * The ARN of the IAM role used when pushing logs to Cloudwatch log group
    */
  vpc_flow_log_cloudwatch_iam_role_arn: any;
  /**
    * The ARN of the destination for VPC Flow Logs
    */
  vpc_flow_log_destination_arn: any;
  /**
    * The type of the destination for VPC Flow Logs
    */
  vpc_flow_log_destination_type: any;
  /**
    * The ID of the Flow Log resource
    */
  vpc_flow_log_id: any;
  /**
    * The ID of the VPC
    */
  vpc_id: any;
  /**
    * Tenancy of instances spin up within VPC
    */
  vpc_instance_tenancy: any;
  /**
    * The association ID for the IPv6 CIDR block
    */
  vpc_ipv6_association_id: any;
  /**
    * The IPv6 CIDR block
    */
  vpc_ipv6_cidr_block: any;
  /**
    * The ID of the main route table associated with this VPC
    */
  vpc_main_route_table_id: any;
  /**
    * The ID of the AWS account that owns the VPC
    */
  vpc_owner_id: any;
  /**
    * List of secondary CIDR blocks of the VPC
    */
  vpc_secondary_cidr_blocks: any;
}
