on: push

jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          token: ${{ secrets.CZIBUILDBOT_GITHUB_TOKEN }}
      - uses: actions/setup-go@v2
        with:
          go-version: '1.15.2'
      - name: fix go modules
        run: |
          go mod tidy
          git add go.*
          git config --global user.name "github-actions[bot]"
          git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git commit -m "tidy modules" || true
          git push

